import type { CommandHandler } from './commandTypes';
import { cmdAccessList, cmdNoAccessList } from './interface/cmd.misc';
import { cmdIpDhcpPool, cmdNoIpDhcpPool, cmdIpv6DhcpPool, cmdIpDhcpExcludedAddress, cmdNoIpDhcpExcludedAddress, cmdIpDhcpSnoopingVlan, cmdNoIpDhcpSnooping, cmdIpDhcpSnoopingInformationOption } from './globalConfigDhcpCommands';
import { cmdIpNatPool, cmdIpNatInsideSourceStatic, cmdIpNatInsideSourceList, cmdLoggingHost, cmdLoggingTrap, cmdNtpServer, cmdNtpMaster, cmdNoNtpServer, cmdClockTimezone, cmdIpNameServer, cmdIpHost, cmdAliasExec, cmdNoAliasExec, cmdIpSla, cmdTrack, cmdLldpTlvSelect, cmdSpanningTreeMst, cmdIpPrefixList, cmdRouteMap, cmdIpv6RouterEigrp, cmdSpanningTreeLoopguardDefault, cmdIpFlowExport, cmdNoIpPrefixList, cmdNoIpv6PrefixList, cmdNoRouteMap, cmdVrfDefinition, cmdVrfRd, cmdVrfRouteTarget, cmdMplsLdpRouterId, cmdMplsLdpGracefulRestart, cmdMplsLdpSessionProtection, cmdVxlanInterface, cmdZoneSecurity, cmdZonePairSecurity, cmdRestconfEnable, cmdMplsIpGlobal, cmdArchive, cmdMacroName, cmdMacroApply, cmdConfigureReplace, cmdMacAccessList, cmdTemplate, cmdLispRouter, cmdLispEidTable, cmdControlPlane } from './globalConfigNetworkCommands';

import { cmdClassMap, cmdPolicyMap, cmdClass, cmdSetDscp, cmdSetCoS, cmdPolice, cmdNoClassMap, cmdNoPolicyMap } from './qosMqcCommands';
import { cmdAaaNewModel, cmdNoAaaNewModel, cmdAaaAuthentication, cmdRadiusServerHost, cmdTacacsServerHost, cmdRadiusServerKey, cmdTacacsServerKey, cmdDot1xSystem } from './globalConfigAaaCommands';
import { cmdFlowRecord, cmdNoFlowRecord, cmdFlowExporter, cmdNoFlowExporter, cmdFlowMonitor, cmdNoFlowMonitor } from './flowCommands';
import {
  cmdNoIpHttpServer,
  cmdNoIpDomainLookup,
  cmdNoIpDomainName,
  cmdNoIpSshTimeOut,
  cmdNoMlsQos,
  cmdIpSshVersion,
  cmdIpDomainLookup,
  cmdSystemMtu,
  cmdSdmPrefer,
  cmdIpSshAuthRetries
} from './globalConfigServiceCommands';
import {
  cmdNoSpanningTree,
  cmdNoUsername,
  cmdUsername,
  cmdNoInterface,
  cmdSpanningTreeVlan,
  cmdSpanningTreePortfastDefault,
  cmdErrdisableRecovery,
  cmdVtpPassword,
  cmdIpArpInspection,
  cmdNoIpArpInspection,
  cmdCryptoKeyGenerateRsa,
  cmdCryptoKeyZeroizeRsa,
  cmdServicePasswordEncryption,
  cmdNoServicePasswordEncryption,
  cmdEnableSecret,
  cmdEnablePassword,
  cmdNoEnableSecret,
  cmdNoEnablePassword,
  cmdBannerMotd,
  cmdNoBannerMotd,
  cmdBannerLogin,
  cmdNoBannerLogin,
  cmdBannerExec,
  cmdNoBannerExec
} from './globalConfigSecurityCommands';
import {
  cmdIpAccessList,
  cmdIpv6AccessList,
  cmdIpv6AclPermit,
  cmdIpv6AclDeny,
  cmdNamedAclPermit,
  cmdNamedAclDeny,
  cmdNamedAclNoPermit,
  cmdNamedAclNoDeny,
  cmdExtAclPermit,
  cmdExtAclDeny,
  cmdExtAclNoPermit,
  cmdExtAclNoDeny,
  cmdNoIpAccessList,
  cmdSeqNamedAcl,
  cmdNoNamedAcl,
  cmdNoIpv6AccessList
} from './globalConfigAclCommands';

import {
  cmdMstName,
  cmdMstRevision,
  cmdMstInstance,
  cmdNoMstInstance,
  cmdMstShowPending,
  cmdSpanningTreeMstPriority
} from './globalConfigMstpCommands';
import {
  cmdIpv6UnicastRouting,
  cmdNoIpv6UnicastRouting,
  cmdIpv6Route,
  cmdNoIpv6Route,
  cmdIpv6RouterRip,
  cmdIpv6RouterOspf,
  cmdNoIpv6RouterRip,
  cmdNoIpv6RouterOspf
} from './globalConfigIpv6Commands';

import {
  cmdHostname,
  cmdNoHostname,
  cmdVlan,
  cmdNoVlan,
  cmdVlanName,
  cmdNoVlanName,
  cmdVlanState,
  cmdVtpMode,
  cmdVtpDomain,
  cmdSpanningTreeMode
} from './globalConfigVlanCommands';

import {
  cmdIpRouting,
  cmdNoIpRouting,
  cmdIpRoute,
  cmdNoIpRoute,
  cmdRouterRip,
  cmdNoRouterRip,
  cmdRouterOspf,
  cmdNoRouterOspf,
  cmdRouterEigrp,
  cmdNoRouterEigrp,
  cmdRouterBgp,
  cmdNoRouterBgp
} from './globalConfigRoutingCommands';

import {
  cmdNoIpHost,
  cmdNoIpv6DhcpPool,
  cmdIpDomainName,
  cmdIpDefaultGateway,
  cmdNoIpDefaultGateway,
  cmdIpSshTimeOut,
  cmdIpDhcpSnooping,
  cmdMlsQos,
  cmdCdpRun,
  cmdNoCdpRun,
  cmdLldpRun,
  cmdNoLldpRun,
  cmdIpHttpServer,
  cmdCdpTimer,
  cmdCdpHoldtime,
  cmdLldpTimer,
  cmdLldpHoldtime,
  cmdLldpReinit,
  cmdSnmpCommunity,
  cmdSnmpContact,
  cmdSnmpLocation,
  cmdDefaultInterface
} from './globalConfigMiscCommands';

export { cmdIpRoute, cmdNoIpRoute };

// Global config (hostname, vlan, vtp, spanning-tree, security, ip domain-name, etc.)

export const globalConfigHandlers: Record<string, CommandHandler> = {
  'hostname': cmdHostname,
  'no hostname': cmdNoHostname,
  'vlan': cmdVlan,
  'no vlan': cmdNoVlan,
  'name': (state, input, ctx) => {
    if (state.currentMode === 'config-mst') return cmdMstName(state, input);
    return cmdVlanName(state, input, ctx);
  },
  'no name': cmdNoVlanName,
  'revision': cmdMstRevision,
  'instance': cmdMstInstance,
  'no instance': cmdNoMstInstance,
  'show pending': cmdMstShowPending,
  'spanning-tree mst priority': cmdSpanningTreeMstPriority,
  'aaa new-model': cmdAaaNewModel,
  'no aaa new-model': cmdNoAaaNewModel,
  'aaa authentication login': cmdAaaAuthentication,
  'radius-server host': cmdRadiusServerHost,
  'tacacs-server host': cmdTacacsServerHost,
  'radius-server key': cmdRadiusServerKey,
  'tacacs-server key': cmdTacacsServerKey,
  'state': cmdVlanState,
  'vtp mode': cmdVtpMode,
  'vtp domain': cmdVtpDomain,
  'spanning-tree mode': cmdSpanningTreeMode,
  'spanning-tree vlan': cmdSpanningTreeVlan,
  'spanning-tree portfast': cmdSpanningTreePortfastDefault,
  'no spanning-tree': cmdNoSpanningTree,
  'service password-encryption': cmdServicePasswordEncryption,
  'no service password-encryption': cmdNoServicePasswordEncryption,
  'enable secret': cmdEnableSecret,
  'no enable secret': cmdNoEnableSecret,
  'enable password': cmdEnablePassword,
  'no enable password': cmdNoEnablePassword,
  'banner motd': cmdBannerMotd,
  'no banner motd': cmdNoBannerMotd,
  'banner login': cmdBannerLogin,
  'no banner login': cmdNoBannerLogin,
  'banner exec': cmdBannerExec,
  'no banner exec': cmdNoBannerExec,
  'ip default-gateway': cmdIpDefaultGateway,
  'no ip default-gateway': cmdNoIpDefaultGateway,
  'ip domain-name': cmdIpDomainName,
  'ip domain lookup': cmdIpDomainLookup,
  'ip domain-lookup': cmdIpDomainLookup,
  'no ip domain-lookup': cmdNoIpDomainLookup,
  'no ip domain-name': cmdNoIpDomainName,
  'ip routing': cmdIpRouting,
  'no ip routing': cmdNoIpRouting,
  'ip route': cmdIpRoute,
  'no ip route': cmdNoIpRoute,
  'ip ssh time-out': cmdIpSshTimeOut,
  'no ip ssh time-out': cmdNoIpSshTimeOut,
  'ip dhcp snooping': cmdIpDhcpSnooping,
  'no ip dhcp snooping': cmdNoIpDhcpSnooping,
  'mls qos': cmdMlsQos,
  'dot1x system-auth-control': cmdDot1xSystem,
  'no mls qos': cmdNoMlsQos,
  'cdp run': cmdCdpRun,
  'no cdp run': cmdNoCdpRun,
  'lldp run': cmdLldpRun,
  'lldp tlv-select': cmdLldpTlvSelect,
  'no lldp run': cmdNoLldpRun,
  'username': cmdUsername,
  'no username': cmdNoUsername,
  // 'interface' command handler is in interfaceCommands.ts for proper port validation
  // We handle VLAN interfaces here
  'no interface': cmdNoInterface,
  // Routing protocols
  'router rip': cmdRouterRip,
  'router ospf': cmdRouterOspf,
  'router eigrp': cmdRouterEigrp,
  'router bgp': cmdRouterBgp,
  'no router rip': cmdNoRouterRip,
  'no router ospf': cmdNoRouterOspf,
  'no router eigrp': cmdNoRouterEigrp,
  'no router bgp': cmdNoRouterBgp,
  // HTTP Server
  'ip http server': cmdIpHttpServer,
  'no ip http server': cmdNoIpHttpServer,
  // SSH version
  'ip ssh version': cmdIpSshVersion,
  'ip dhcp snooping vlan': cmdIpDhcpSnoopingVlan,
  'ip dhcp snooping information option': cmdIpDhcpSnoopingInformationOption,
  'no ip dhcp snooping information option': cmdIpDhcpSnoopingInformationOption,
  'ip arp inspection': cmdIpArpInspection,
  'no ip arp inspection': cmdNoIpArpInspection,
  'errdisable recovery': cmdErrdisableRecovery,
  'errdisable recovery cause': cmdErrdisableRecovery,
  'vtp password': cmdVtpPassword,
  'ntp server': cmdNtpServer,
  'no ntp server': cmdNoNtpServer,
  'ntp master': cmdNtpMaster,
  'clock timezone': cmdClockTimezone,
  'ip name-server': cmdIpNameServer,
  'system mtu': cmdSystemMtu,
  'sdm prefer': cmdSdmPrefer,
  'ipv6 unicast-routing': cmdIpv6UnicastRouting,
  'no ipv6 unicast-routing': cmdNoIpv6UnicastRouting,
  'ipv6 route': cmdIpv6Route,
  'no ipv6 route': cmdNoIpv6Route,
  'ipv6 router rip': cmdIpv6RouterRip,
  'ipv6 router ospf': cmdIpv6RouterOspf,
  'ipv6 router eigrp': cmdIpv6RouterEigrp,
  'no ipv6 router rip': cmdNoIpv6RouterRip,
  'no ipv6 router ospf': cmdNoIpv6RouterOspf,
  'ip prefix-list': cmdIpPrefixList,
  'ipv6 prefix-list': cmdIpPrefixList,
  'no ip prefix-list': cmdNoIpPrefixList,
  'no ipv6 prefix-list': cmdNoIpv6PrefixList,
  'route-map': cmdRouteMap,
  'no route-map': cmdNoRouteMap,
  'vrf definition': cmdVrfDefinition,
  'ip vrf': cmdVrfDefinition,
  'rd': cmdVrfRd,
  'route-target': cmdVrfRouteTarget,
  'mpls ldp router-id': cmdMplsLdpRouterId,
  'mpls ldp graceful-restart': cmdMplsLdpGracefulRestart,
  'no mpls ldp graceful-restart': cmdMplsLdpGracefulRestart,
  'mpls ldp session protection': cmdMplsLdpSessionProtection,
  'no mpls ldp session protection': cmdMplsLdpSessionProtection,
  'interface nve': cmdVxlanInterface,
  'zone security': cmdZoneSecurity,
  'zone-pair security': cmdZonePairSecurity,
  'spanning-tree loopguard default': cmdSpanningTreeLoopguardDefault,
  'no spanning-tree loopguard default': cmdSpanningTreeLoopguardDefault,
  'ip flow-export': cmdIpFlowExport,
  'no ip flow-export': cmdIpFlowExport,
  'flow record': cmdFlowRecord,
  'no flow record': cmdNoFlowRecord,
  'flow exporter': cmdFlowExporter,
  'no flow exporter': cmdNoFlowExporter,
  'flow monitor': cmdFlowMonitor,
  'no flow monitor': cmdNoFlowMonitor,
  'ip ssh authentication-retries': cmdIpSshAuthRetries,
  'crypto key generate rsa': cmdCryptoKeyGenerateRsa,
  'crypto key zeroize rsa': cmdCryptoKeyZeroizeRsa,
  'ip dhcp pool': cmdIpDhcpPool,
  'no ip dhcp pool': cmdNoIpDhcpPool,
  'ipv6 dhcp pool': cmdIpv6DhcpPool,
  'ip dhcp excluded-address': cmdIpDhcpExcludedAddress,
  'no ip dhcp excluded-address': cmdNoIpDhcpExcludedAddress,
  'cdp timer': cmdCdpTimer,
  'cdp holdtime': cmdCdpHoldtime,
  'lldp timer': cmdLldpTimer,
  'lldp holdtime': cmdLldpHoldtime,
  'lldp reinit': cmdLldpReinit,
  'snmp-server community': cmdSnmpCommunity,
  'snmp-server contact': cmdSnmpContact,
  'snmp-server location': cmdSnmpLocation,
  'archive': cmdArchive,
  'alias': cmdAliasExec,
  'no alias': cmdNoAliasExec,
  'macro': cmdMacroName,
  'macro name': cmdMacroName,
  'macro apply': cmdMacroApply,
  'default interface': cmdDefaultInterface,
  'configure replace': cmdConfigureReplace,
  'mac access-list': cmdMacAccessList,
  'mac access-list extended': cmdMacAccessList,
  'class-map': cmdClassMap,
  'no class-map': cmdNoClassMap,
  'policy-map': cmdPolicyMap,
  'no policy-map': cmdNoPolicyMap,
  'class': cmdClass,
  'police': cmdPolice,
  'set dscp': cmdSetDscp,
  'set cos': cmdSetCoS,
  'template': cmdTemplate,
  'access-list': cmdAccessList,
  'no access-list': cmdNoAccessList,
  'ip access-list': cmdIpAccessList,
  'permit (named-acl)': cmdNamedAclPermit,
  'deny (named-acl)': cmdNamedAclDeny,
  'no permit (named-acl)': cmdNamedAclNoPermit,
  'no deny (named-acl)': cmdNamedAclNoDeny,
  'permit (ext-named-acl)': cmdExtAclPermit,
  'deny (ext-named-acl)': cmdExtAclDeny,
  'no permit (ext-named-acl)': cmdExtAclNoPermit,
  'no deny (ext-named-acl)': cmdExtAclNoDeny,
  'no ip access-list': cmdNoIpAccessList,
  'ipv6 access-list': cmdIpv6AccessList,
  'permit (ipv6-acl)': cmdIpv6AclPermit,
  'deny (ipv6-acl)': cmdIpv6AclDeny,
  'seq permit/deny (named-acl)': cmdSeqNamedAcl,
  'no (named-acl)': cmdNoNamedAcl,
  'no ipv6 access-list': cmdNoIpv6AccessList,
  'ip host': cmdIpHost,
  'no ip host': cmdNoIpHost,
  'no ipv6 dhcp pool': cmdNoIpv6DhcpPool,

  'ip nat pool': cmdIpNatPool,
  'ip nat inside source static': cmdIpNatInsideSourceStatic,
  'ip nat inside source list': cmdIpNatInsideSourceList,
  'logging host': cmdLoggingHost,
  'logging trap': cmdLoggingTrap,
  'ip sla': cmdIpSla,
  'track': cmdTrack,
  'no track': cmdTrack,
  'spanning-tree mst configuration': cmdSpanningTreeMst,
  'restconf': cmdRestconfEnable,
  'no restconf': cmdRestconfEnable,
  'mpls ip': cmdMplsIpGlobal,
  'router lisp': cmdLispRouter,
  'no router lisp': cmdLispRouter,
  'database-mapping': cmdLispEidTable,
  'control-plane': cmdControlPlane,
};
