import { Terminal, Globe, Wifi, Settings, Eye, Server, Router, Network, Book, Zap, Keyboard, LucideIcon, Lightbulb, FileText, Layers } from 'lucide-react';

export interface CommandDefinition {
  id: string;
  icon: LucideIcon;
  title: string;
  cmds: [string, string, string?][];
  type?: 'commands' | 'info' | 'examples';
}

export function getCommandCategories(isTR: boolean): CommandDefinition[] {
  return [
    {
      id: 'system',
      icon: Terminal,
      title: isTR ? 'Oturum' : 'Session',
      type: 'commands',
      cmds: [
        ['enable', isTR ? 'Ayrıcalıklı moda geç' : 'Enter privileged mode', '>'],
        ['disable', isTR ? 'Kullanıcı moduna dön' : 'Return to user mode', '#'],
        ['configure terminal', isTR ? 'Yapılandırma modu' : 'Enter config mode', '#'],
        ['exit', isTR ? 'Moddan çık' : 'Exit current mode'],
        ['end', isTR ? 'Ayrıcalıklı moda dön' : 'Return to privileged mode'],
        ['help', isTR ? 'Yardım sistemini göster' : 'Display help system'],
      ]
    },
    {
      id: 'privileged',
      icon: Server,
      title: isTR ? 'Privileged EXEC' : 'Privileged EXEC',
      type: 'commands',
      cmds: [
        ['ping <host> [s] [c]', isTR ? 'Bağlantı testi (ICMP)' : 'Ping host (ICMP)', '#'],
        ['traceroute <host>', isTR ? 'Rota izleme' : 'Trace route', '#'],
        ['clock set <hh:mm:ss> <day> <month> <year>', isTR ? 'Sistem saatini ayarla' : 'Set system clock', '#'],
        ['telnet <host> [port]', isTR ? 'Telnet bağlantısı' : 'Telnet connection', '#'],
        ['ssh [-l user] <host>', isTR ? 'SSH bağlantısı' : 'SSH connection', '#'],
        ['write memory', isTR ? 'Yapılandırmayı kaydet' : 'Save configuration', '#'],
        ['copy running-config startup-config', isTR ? 'Yapılandırmayı kaydet' : 'Save config', '#'],
        ['copy running-config flash:', isTR ? 'Flash\'a kaydet' : 'Save to flash', '#'],
        ['copy flash: startup-config', isTR ? 'Flash\'tan geri yükle' : 'Restore from flash', '#'],
        ['delete flash:vlan.dat', isTR ? 'VLAN veritabanı sil' : 'Delete VLAN database', '#'],
        ['erase startup-config', isTR ? 'Startup config sil' : 'Erase startup config', '#'],
        ['erase nvram', isTR ? 'NVRAM dosya sistemini sil' : 'Erase NVRAM', '#'],
        ['reload', isTR ? 'Cihazı yeniden yükle' : 'Reload device', '#'],
        ['ip route <n> <mask> <h>', isTR ? 'Statik rota ekle' : 'Add static route', '#'],
        ['no ip route <n> <mask> <h>', isTR ? 'Statik rotayı sil' : 'Remove static route', '#'],
        ['debug <type>', isTR ? 'Hata ayıklamayı aç' : 'Enable debugging', '#'],
        ['undebug all', isTR ? 'Tüm hataları kapat' : 'Disable all debugging', '#'],
        ['terminal length <0-512>', isTR ? 'Terminal satır uzunluğu' : 'Set terminal length', '#'],
        ['clear arp-cache', isTR ? 'ARP önbelleğini sil' : 'Clear ARP cache', '#'],
        ['clear mac address-table', isTR ? 'MAC tablosunu sil' : 'Clear MAC table', '#'],
        ['clear counters', isTR ? 'Sayaçları sıfırla' : 'Clear counters', '#'],
        ['do <command>', isTR ? 'Ayrıcalıklı komut çalıştır' : 'Execute privileged command', '(config)#'],
      ]
    },
    {
      id: 'global',
      icon: Globe,
      title: isTR ? 'Global Yapılandırma' : 'Global Config',
      type: 'commands',
      cmds: [
        ['hostname <name>', isTR ? 'Cihaz adı' : 'Set hostname', '(config)#'],
        ['vlan <id>', isTR ? 'VLAN oluştur' : 'Create VLAN', '(config)#'],
        ['no vlan <id>', isTR ? 'VLAN sil' : 'Delete VLAN', '(config)#'],
        ['name <name>', isTR ? 'VLAN adı (vlan modunda)' : 'Set VLAN name', '(config-vlan)#'],
        ['interface <name>', isTR ? 'Arayüz seç' : 'Select interface', '(config)#'],
        ['interface range <r>', isTR ? 'Arayüz aralığı' : 'Interface range', '(config)#'],
        ['no interface vlan <id>', isTR ? 'VLAN arayüzünü sil' : 'Delete VLAN interface', '(config)#'],
        ['ip routing', isTR ? 'IP yönlendirme (L3)' : 'Enable IP routing (L3)', '(config)#'],
        ['no ip routing', isTR ? 'IP yönlendirmeyi kapat' : 'Disable IP routing', '(config)#'],
        ['ip default-gateway <ip>', isTR ? 'Varsayılan ağ geçidi' : 'Set default gateway', '(config)#'],
        ['ip domain-name <name>', isTR ? 'Alan adı' : 'Set domain name', '(config)#'],
        ['no ip domain lookup', isTR ? 'DNS aramayı kapat' : 'Disable DNS lookup', '(config)#'],
        ['ip http server', isTR ? 'HTTP sunucusunu aç' : 'Enable HTTP server', '(config)#'],
        ['no ip http server', isTR ? 'HTTP sunucusunu kapat' : 'Disable HTTP server', '(config)#'],
        ['ip ssh version {1|2}', isTR ? 'SSH versiyonu' : 'Set SSH version', '(config)#'],
        ['ip ssh time-out <s>', isTR ? 'SSH zaman aşımı' : 'Set SSH timeout', '(config)#'],
        ['ip ssh authentication-retries <n>', isTR ? 'SSH deneme sayısı' : 'SSH retry limit', '(config)#'],
        ['ip dhcp snooping', isTR ? 'DHCP snooping aç' : 'Enable DHCP snooping', '(config)#'],
        ['ip dhcp snooping vlan <ids>', isTR ? 'VLANlarda DHCP snooping' : 'DHCP snooping on VLANs', '(config)#'],
        ['service password-enc', isTR ? 'Parolaları şifrele' : 'Encrypt passwords', '(config)#'],
        ['enable secret <pass>', isTR ? 'Enable secret parolası' : 'Set enable secret', '(config)#'],
        ['enable password <pass>', isTR ? 'Enable password parolası' : 'Set enable password', '(config)#'],
        ['banner motd #<msg>#', isTR ? 'MOTD banner' : 'MOTD banner', '(config)#'],
        ['banner login #<msg>#', isTR ? 'Login banner' : 'Login banner', '(config)#'],
        ['no banner {motd|login}', isTR ? 'Banner sil' : 'Remove banner', '(config)#'],
        ['vtp mode {server|client}', isTR ? 'VTP modu' : 'Set VTP mode', '(config)#'],
        ['vtp domain <name>', isTR ? 'VTP etki alanı' : 'Set VTP domain', '(config)#'],
        ['vtp password <pass>', isTR ? 'VTP parolası' : 'Set VTP password', '(config)#'],
        ['spanning-tree mode {m}', isTR ? 'STP modu' : 'Set STP mode', '(config)#'],
        ['spanning-tree vlan <id> priority <val>', isTR ? 'VLAN STP önceliği' : 'VLAN STP priority', '(config)#'],
        ['spanning-tree vlan <id> root', isTR ? 'VLAN STP root' : 'VLAN STP root', '(config)#'],
        ['no spanning-tree', isTR ? 'STP\'yi kapat' : 'Disable spanning-tree', '(config)#'],
        ['username <n> pass <p>', isTR ? 'Kullanıcı oluştur' : 'Create user', '(config)#'],
        ['no username <name>', isTR ? 'Kullanıcıyı sil' : 'Remove user', '(config)#'],
        ['cdp run', isTR ? 'CDP\'yi aç' : 'Enable CDP globally', '(config)#'],
        ['mls qos', isTR ? 'QoS\'u aç' : 'Enable MLS QoS', '(config)#'],
        ['ip dhcp pool <name>', isTR ? 'DHCP havuzu' : 'Create DHCP pool', '(config)#'],
        ['no ip dhcp pool <name>', isTR ? 'DHCP havuzunu sil' : 'Remove DHCP pool', '(config)#'],
        ['ip dhcp excluded <ip>', isTR ? 'DHCP hariç tut' : 'Exclude DHCP addr', '(config)#'],
        ['ntp server <ip>', isTR ? 'NTP sunucusu' : 'Set NTP server', '(config)#'],
        ['clock timezone <n> <o>', isTR ? 'Zaman dilimi' : 'Set timezone', '(config)#'],
        ['ip name-server <ip>', isTR ? 'DNS sunucusu' : 'Set DNS server', '(config)#'],
        ['system mtu <size>', isTR ? 'Sistem MTU' : 'Set system MTU', '(config)#'],
        ['errdisable recovery', isTR ? 'Hata kurtarma' : 'Errdisable recovery', '(config)#'],
        ['spanning-tree portfast default', isTR ? 'Global PortFast' : 'Global PortFast', '(config)#'],
        ['ipv6 unicast-routing', isTR ? 'IPv6 yönlendirme' : 'Enable IPv6 routing', '(config)#'],
        ['crypto key generate rsa', isTR ? 'RSA anahtarı üret (SSH)' : 'Generate RSA keys', '(config)#'],
        ['snmp-server community <c>', isTR ? 'SNMP topluluğu' : 'Set SNMP community', '(config)#'],
        ['archive', isTR ? 'Arşiv yapılandırması' : 'Archive configuration', '(config)#'],
        ['alias <mode> <n> <c>', isTR ? 'Komut takma adı' : 'Command alias', '(config)#'],
        ['macro name <name>', isTR ? 'Komut makrosu' : 'Define command macro', '(config)#'],
        ['sdm prefer <template>', isTR ? 'SDM şablonu' : 'Set SDM template', '(config)#'],
        ['ip arp inspection vlan <id>', isTR ? 'DAI (ARP Denetimi)' : 'Enable DAI on VLAN', '(config)#'],
      ]
    },
    {
      id: 'examples-dhcp',
      icon: Lightbulb,
      title: isTR ? 'Örnek: DHCP Sunucusu' : 'Example: DHCP Server',
      type: 'examples',
      cmds: [
        ['ip dhcp pool MY_POOL', isTR ? '1. DHCP havuzu oluştur' : '1. Create DHCP pool', '(config)#'],
        ['network 192.168.1.0 255.255.255.0', isTR ? '2. Havuz ağını ve maskesini belirle' : '2. Define pool network and mask', '(config-dhcp)#'],
        ['default-router 192.168.1.1', isTR ? '3. Varsayılan ağ geçidini belirle' : '3. Set default gateway', '(config-dhcp)#'],
        ['dns-server 8.8.8.8', isTR ? '4. DNS sunucusunu belirle' : '4. Set DNS server', '(config-dhcp)#'],
        ['exit', isTR ? '5. Havuz modundan çık' : '5. Exit pool mode', '(config-dhcp)#'],
        ['ip dhcp excluded-address 192.168.1.1', isTR ? '6. Dağıtılmayacak adresleri hariç tut' : '6. Exclude addresses from pool', '(config)#'],
      ]
    },
    {
      id: 'examples-wifi',
      icon: Wifi,
      title: isTR ? 'Örnek: Wi-Fi Ayarları' : 'Example: Wi-Fi Setup',
      type: 'examples',
      cmds: [
        ['dot11 ssid MY_WIFI', isTR ? '1. SSID yapılandırmasına gir' : '1. Enter SSID config', '(config)#'],
        ['authentication open', isTR ? '2. Açık kimlik doğrulama (veya WPA)' : '2. Open authentication (or WPA)', '(config-ssid)#'],
        ['guest-mode', isTR ? '3. SSID\'yi yayınla (Beacon)' : '3. Broadcast SSID (Beacon)', '(config-ssid)#'],
        ['exit', isTR ? '4. SSID modundan çık' : '4. Exit SSID mode', '(config-ssid)#'],
        ['interface Dot11Radio 0', isTR ? '5. Radyo arayüzüne gir' : '5. Enter radio interface', '(config)#'],
        ['ssid MY_WIFI', isTR ? '6. SSID\'yi radyoya ata' : '6. Assign SSID to radio', '(config-if)#'],
        ['no shutdown', isTR ? '7. Radyoyu etkinleştir' : '7. Enable radio', '(config-if)#'],
      ]
    },
    {
      id: 'examples-vlan',
      icon: Layers,
      title: isTR ? 'Örnek: VLAN & Trunk' : 'Example: VLAN & Trunk',
      type: 'examples',
      cmds: [
        ['vlan 10', isTR ? '1. VLAN 10 oluştur' : '1. Create VLAN 10', '(config)#'],
        ['name SALES', isTR ? '2. VLAN adını "SALES" yap' : '2. Name VLAN "SALES"', '(config-vlan)#'],
        ['interface range fa0/1 - 10', isTR ? '3. İlk 10 portu seç' : '3. Select first 10 ports', '(config)#'],
        ['switchport mode access', isTR ? '4. Portları erişim moduna al' : '4. Set ports to access mode', '(config-if)#'],
        ['switchport access vlan 10', isTR ? '5. Portları VLAN 10\'a ata' : '5. Assign ports to VLAN 10', '(config-if)#'],
        ['interface gi0/1', isTR ? '6. Uplink portunu seç' : '6. Select uplink port', '(config)#'],
        ['switchport mode trunk', isTR ? '7. Portu Trunk moduna al' : '7. Set port to Trunk mode', '(config-if)#'],
      ]
    },
    {
      id: 'knowledge-stp',
      icon: Book,
      title: isTR ? 'Bilgi: STP Nedir?' : 'Knowledge: What is STP?',
      type: 'info',
      cmds: [
        ['Spanning Tree Protocol', isTR ? 'STP (Spanning Tree Protocol), yerel ağlarda (LAN) fiziksel döngüleri (loop) önlemek için kullanılan bir Layer 2 protokolüdür. Eğer ağda yedekli bağlantılar varsa ve STP yoksa, paketler sonsuz bir döngüye girerek ağı kilitleyebilir (Broadcast Storm). STP, bazı portları bloklayarak döngüsüz bir yapı oluşturur.' : 'STP (Spanning Tree Protocol) is a Layer 2 protocol used to prevent physical loops in local area networks (LANs). If there are redundant links in a network without STP, packets can enter an infinite loop, crashing the network (Broadcast Storm). STP creates a loop-free topology by blocking certain ports.'],
      ]
    },
    {
      id: 'knowledge-dhcp',
      icon: FileText,
      title: isTR ? 'Bilgi: DHCP Nedir?' : 'Knowledge: What is DHCP?',
      type: 'info',
      cmds: [
        ['Dynamic Host Configuration Protocol', isTR ? 'DHCP, ağdaki cihazlara otomatik olarak IP adresi, alt ağ maskesi, varsayılan ağ geçidi ve DNS gibi yapılandırma bilgilerini dağıtan bir protokoldür. Bu sayede her cihazı manuel olarak yapılandırma zahmeti ortadan kalkar ve IP çakışmaları önlenir.' : 'DHCP is a protocol that automatically assigns IP addresses, subnet masks, default gateways, and DNS information to devices on a network. This eliminates the need for manual configuration of each device and helps prevent IP address conflicts.'],
      ]
    },
    {
      id: 'knowledge-vlan',
      icon: Network,
      title: isTR ? 'Bilgi: VLAN Nedir?' : 'Knowledge: What is VLAN?',
      type: 'info',
      cmds: [
        ['Virtual Local Area Network', isTR ? 'VLAN, fiziksel bir yerel ağı mantıksal olarak daha küçük parçalara bölen teknolojidir. Aynı switch üzerindeki kullanıcıları farklı VLAN\'lara ayırarak güvenliği artırabilir ve ağ trafiğini (broadcast) optimize edebilirsiniz. Farklı VLAN\'lar arasındaki iletişim için bir Router veya L3 Switch gerekir.' : 'VLAN is a technology that logically partitions a physical LAN into smaller segments. By placing users on the same switch into different VLANs, you can improve security and optimize network traffic (broadcast). Communication between different VLANs requires a Router or L3 Switch.'],
      ]
    },
    {
      id: 'interface',
      icon: Settings,
      title: isTR ? 'Arayüz Yapılandırması' : 'Interface Config',
      type: 'commands',
      cmds: [
        ['shutdown', isTR ? 'Arayüzü kapat' : 'Disable interface', '(config-if)#'],
        ['no shutdown', isTR ? 'Arayüzü aç' : 'Enable interface', '(config-if)#'],
        ['speed {10|100|1000|10000|auto}', isTR ? 'Hız ayarla' : 'Set speed', '(config-if)#'],
        ['duplex {half|full|auto}', isTR ? 'Duplex ayarla' : 'Set duplex', '(config-if)#'],
        ['description <text>', isTR ? 'Arayüz açıklaması' : 'Set description', '(config-if)#'],
        ['no description', isTR ? 'Açıklamayı sil' : 'Clear description', '(config-if)#'],
        ['switchport mode access', isTR ? 'Erişim modu' : 'Access mode', '(config-if)#'],
        ['switchport mode trunk', isTR ? 'Trunk modu' : 'Trunk mode', '(config-if)#'],
        ['switchport trunk encapsulation dot1q', isTR ? 'Trunk kapsülleme' : 'Trunk encapsulation', '(config-if)#'],
        ['encapsulation dot1q <vlan>', isTR ? 'Subinterface VLANı' : 'Subinterface VLAN', '(config-subif)#'],
        ['switchport mode dynamic {m}', isTR ? 'DTP modu' : 'Set DTP mode', '(config-if)#'],
        ['switchport mode dot1q-tunnel', isTR ? 'Dot1q tunnel' : 'Dot1q tunnel mode', '(config-if)#'],
        ['no switchport mode', isTR ? 'Modu sıfırla' : 'Reset switchport mode', '(config-if)#'],
        ['switchport access vlan <id>', isTR ? 'VLAN ata' : 'Assign VLAN', '(config-if)#'],
        ['no switchport access vlan', isTR ? 'VLAN atamasını sil' : 'Remove VLAN assign', '(config-if)#'],
        ['switchport trunk native <id>', isTR ? 'Native VLAN' : 'Set native VLAN', '(config-if)#'],
        ['switchport trunk allowed <l>', isTR ? 'İzinli VLANlar' : 'Set allowed VLANs', '(config-if)#'],
        ['switchport nonegotiate', isTR ? 'DTP\'yi kapat' : 'Disable DTP', '(config-if)#'],
        ['switchport voice vlan <id>', isTR ? 'Ses VLAN\'ı' : 'Set voice VLAN', '(config-if)#'],
        ['switchport port-security', isTR ? 'Port güvenliği' : 'Port security', '(config-if)#'],
        ['switchport port-security max <n>', isTR ? 'Maksimum MAC' : 'Set max MACs', '(config-if)#'],
        ['switchport port-security violation {a}', isTR ? 'İhlal aksiyonu' : 'Violation action', '(config-if)#'],
        ['switchport port-security sticky', isTR ? 'Sticky MAC' : 'Enable sticky MAC', '(config-if)#'],
        ['switchport port-security aging time <n>', isTR ? 'Güvenlik yaşlanma süresi' : 'Port-security aging time', '(config-if)#'],
        ['no switchport port-security', isTR ? 'Güvenliği kapat' : 'Disable port security', '(config-if)#'],
        ['switchport protected', isTR ? 'Korumalı port' : 'Protected port', '(config-if)#'],
        ['switchport block {unicast|multicast}', isTR ? 'Trafik bloklama' : 'Block traffic', '(config-if)#'],
        ['no switchport', isTR ? 'L3 portuna dönüştür' : 'Convert to L3 port', '(config-if)#'],
        ['spanning-tree portfast', isTR ? 'PortFast aç' : 'Enable PortFast', '(config-if)#'],
        ['spanning-tree bpduguard {e|d}', isTR ? 'BPDU Guard' : 'BPDU Guard', '(config-if)#'],
        ['spanning-tree cost <cost>', isTR ? 'STP maliyeti' : 'Set STP cost', '(config-if)#'],
        ['spanning-tree priority <p>', isTR ? 'STP önceliği' : 'Set STP priority', '(config-if)#'],
        ['ip address <ip> <mask>', isTR ? 'IP adresi ata' : 'Set IP address', '(config-if)#'],
        ['ipv6 address <ip>/<p>', isTR ? 'IPv6 adresi ata' : 'Set IPv6 address', '(config-if)#'],
        ['no ip address', isTR ? 'IP adresini sil' : 'Remove IP address', '(config-if)#'],
        ['ip default-gateway <ip>', isTR ? 'Arayüz gateway' : 'Interface gateway', '(config-if)#'],
        ['no ip default-gateway', isTR ? 'Gateway sil' : 'Remove gateway', '(config-if)#'],
        ['ip helper-address <ip>', isTR ? 'DHCP relay' : 'Set DHCP relay', '(config-if)#'],
        ['no ip helper-address', isTR ? 'DHCP relay sil' : 'Remove DHCP relay', '(config-if)#'],
        ['ip verify source', isTR ? 'IP Source Guard' : 'Enable Source Guard', '(config-if)#'],
        ['ip dhcp snooping trust', isTR ? 'Güvenli DHCP portu' : 'DHCP snooping trust', '(config-if)#'],
        ['ip arp inspection trust', isTR ? 'Güvenli ARP portu' : 'ARP inspection trust', '(config-if)#'],
        ['storm-control {b|m|u} lvl', isTR ? 'Fırtına kontrolü' : 'Storm control', '(config-if)#'],
        ['power inline {auto|static}', isTR ? 'PoE yapılandırması' : 'Configure PoE', '(config-if)#'],
        ['bandwidth <kbps>', isTR ? 'Bant genişliği' : 'Set bandwidth', '(config-if)#'],
        ['delay <tens-of-ms>', isTR ? 'Gecikme süresi' : 'Set delay', '(config-if)#'],
        ['mls qos trust {cos|dscp}', isTR ? 'QoS güven durumu' : 'Set QoS trust', '(config-if)#'],
        ['mls qos cos <val>', isTR ? 'Default CoS değeri' : 'Set default CoS', '(config-if)#'],
        ['cdp enable', isTR ? 'CDP\'yi aç (arayüz)' : 'Enable CDP (interface)', '(config-if)#'],
        ['no udld', isTR ? 'UDLD\'yi kapat' : 'Disable UDLD', '(config-if)#'],
        ['no ip proxy-arp', isTR ? 'Proxy ARP kapat' : 'Disable proxy ARP', '(config-if)#'],
        ['no keepalive', isTR ? 'Keepalive kapat' : 'Disable keepalive', '(config-if)#'],
        ['load-interval <sec>', isTR ? 'İstatistik aralığı' : 'Set load interval', '(config-if)#'],
        ['carrier-delay <ms>', isTR ? 'Carrier gecikmesi' : 'Set carrier delay', '(config-if)#'],
        ['channel-group <n> mode', isTR ? 'EtherChannel' : 'EtherChannel', '(config-if)#'],
        ['no channel-group', isTR ? 'EtherChannel sil' : 'Remove from channel', '(config-if)#'],
        ['access-list <acl>', isTR ? 'Erişim listesi' : 'Apply access list', '(config-if)#'],
        ['monitor session <n>', isTR ? 'SPAN/RSPAN' : 'Configure SPAN/RSPAN', '(config-if)#'],
      ]
    },
    {
      id: 'wireless',
      icon: Wifi,
      title: isTR ? 'Kablosuz (WiFi)' : 'Wireless (WiFi)',
      type: 'commands',
      cmds: [
        ['wlan <name> <id> <ssid>', isTR ? 'WLAN oluştur' : 'Create WLAN', '(config)#'],
        ['security wpa psk set-key ascii 0 <pass>', isTR ? 'WPA şifresi ayarla' : 'Set WPA password', '(config-wlan)#'],
        ['channel <num>', isTR ? 'RF kanalı ayarla' : 'Set RF channel', '(config-if)#'],
        ['station-role root', isTR ? 'Erişim noktası modunu ayarla' : 'Set AP mode', '(config-if)#'],
        ['show wlan summary', isTR ? 'WLAN özetini göster' : 'Show WLAN summary', '#'],
        ['show ap summary', isTR ? 'AP özetini göster' : 'Show AP summary', '#'],
      ]
    },
    {
      id: 'line',
      icon: Router,
      title: isTR ? 'Hat Yapılandırması' : 'Line Config',
      type: 'commands',
      cmds: [
        ['line console 0', isTR ? 'Konsol hattı' : 'Console line', '(config)#'],
        ['line vty 0 4', isTR ? 'VTY hatları' : 'VTY lines', '(config)#'],
        ['password <pass>', isTR ? 'Şifre ayarla' : 'Set password', '(config-line)#'],
        ['no password', isTR ? 'Şifreyi sil' : 'Remove password', '(config-line)#'],
        ['login', isTR ? 'Giriş kontrolü' : 'Enable login', '(config-line)#'],
        ['no login', isTR ? 'Giriş kontrolü kapat' : 'Disable login', '(config-line)#'],
        ['transport input {p}', isTR ? 'Giriş protokolleri' : 'Input protocols', '(config-line)#'],
        ['transport output {p}', isTR ? 'Çıkış protokolleri' : 'Output protocols', '(config-line)#'],
        ['no transport input', isTR ? 'Girişleri sıfırla' : 'Reset transport input', '(config-line)#'],
        ['logging synchronous', isTR ? 'Senkron loglama' : 'Sync logging', '(config-line)#'],
        ['no logging synchronous', isTR ? 'Senkron log kapat' : 'Disable sync logging', '(config-line)#'],
        ['exec-timeout <m> [s]', isTR ? 'Zaman aşımı' : 'Exec timeout', '(config-line)#'],
        ['no exec-timeout', isTR ? 'Zaman aşımı sıfırla' : 'Reset exec timeout', '(config-line)#'],
        ['history size <n>', isTR ? 'Geçmiş boyutu' : 'Set history size', '(config-line)#'],
        ['no history', isTR ? 'Geçmişi kapat' : 'Disable history', '(config-line)#'],
        ['exec', isTR ? 'EXEC aktif' : 'Enable EXEC', '(config-line)#'],
        ['no exec', isTR ? 'EXEC pasif' : 'Disable EXEC', '(config-line)#'],
        ['autocommand <cmd>', isTR ? 'Otomatik komut' : 'Set auto-command', '(config-line)#'],
        ['no autocommand', isTR ? 'Otomatik komut sil' : 'Remove auto-command', '(config-line)#'],
        ['transport preferred {ssh|telnet|none}', isTR ? 'Tercih edilen protokol' : 'Preferred protocol', '(config-line)#'],
        ['privilege level <0-15>', isTR ? 'Yetki seviyesi' : 'Set privilege level', '(config-line)#'],
        ['session-limit <n>', isTR ? 'Oturum sınırı' : 'Session limit', '(config-line)#'],
        ['access-class <n> {in|out}', isTR ? 'ACL uygula (line)' : 'Apply access-class', '(config-line)#'],
        ['lockable', isTR ? 'Kilitlenebilir hat' : 'Enable lockable', '(config-line)#'],
      ]
    },
    {
      id: 'router',
      icon: Network,
      title: isTR ? 'Yönlendirme (Routing)' : 'Routing Config',
      type: 'commands',
      cmds: [
        ['router rip', isTR ? 'RIP yönlendirmesi' : 'Enable RIP', '(config)#'],
        ['router ospf [<id>]', isTR ? 'OSPF yönlendirmesi' : 'Enable OSPF', '(config)#'],
        ['no router {rip|ospf}', isTR ? 'Yönlendirmeyi kapat' : 'Disable routing', '(config)#'],
        ['network <ip> [wildcard]', isTR ? 'Ağ ekle' : 'Add network', '(config-router)#'],
        ['network <ip> area <id>', isTR ? 'OSPF ağı ekle' : 'Add OSPF network', '(config-router)#'],
        ['router-id <ip>', isTR ? 'Router ID ayarla' : 'Set router ID', '(config-router)#'],
        ['passive-interface <int>', isTR ? 'Pasif arayüz' : 'Passive interface', '(config-router)#'],
        ['default-info originate', isTR ? 'Varsayılan rota' : 'Default route', '(config-router)#'],
      ]
    },
    {
      id: 'dhcp',
      icon: Server,
      title: isTR ? 'DHCP Havuzu' : 'DHCP Pool Config',
      type: 'commands',
      cmds: [
        ['network <net> <mask>', isTR ? 'Havuz ağı' : 'Pool network', '(config-dhcp)#'],
        ['default-router <ip>', isTR ? 'Varsayılan geçit' : 'Default router', '(config-dhcp)#'],
        ['dns-server <ip>', isTR ? 'DNS sunucusu' : 'DNS server', '(config-dhcp)#'],
        ['lease {days|infinite}', isTR ? 'Kira süresi' : 'Lease duration', '(config-dhcp)#'],
        ['domain-name <name>', isTR ? 'Alan adı' : 'Domain name', '(config-dhcp)#'],
      ]
    },
    {
      id: 'show',
      icon: Eye,
      title: isTR ? 'Show Komutları' : 'Show Commands',
      type: 'commands',
      cmds: [
        ['show', isTR ? 'Özet bilgi' : 'Display summary', '#'],
        ['show running-config', isTR ? 'Çalışan yapılandırma' : 'Running config', '#'],
        ['show startup-config', isTR ? 'Başlangıç yapılandırması' : 'Startup config', '#'],
        ['show version', isTR ? 'Sistem bilgisi' : 'System version', '#'],
        ['show interfaces', isTR ? 'Tüm arayüzler' : 'Display all interfaces', '#'],
        ['show interfaces trunk', isTR ? 'Trunk arayüzler' : 'Display trunks', '#'],
        ['show interface <name>', isTR ? 'Arayüz ayrıntısı' : 'Interface details', '#'],
        ['show ip interface brief', isTR ? 'Arayüz özeti' : 'IP interface brief', '#'],
        ['show ip interface', isTR ? 'IP arayüz detay' : 'IP interface details', '#'],
        ['show ip protocols', isTR ? 'Yönlendirme protokolleri' : 'IP routing protocols', '#'],
        ['show ip ospf [neighbor|interface]', isTR ? 'OSPF detayları' : 'OSPF details', '#'],
        ['show ip arp', isTR ? 'ARP tablosu' : 'ARP table', '#'],
        ['show ipv6 interface brief', isTR ? 'IPv6 arayüz özeti' : 'IPv6 interface brief', '#'],
        ['show vlan [brief]', isTR ? 'VLAN listesi' : 'VLAN list', '#'],
        ['show mac address-table', isTR ? 'MAC tablosunu göster' : 'Show MAC address table', '#'],
        ['show cdp neighbors', isTR ? 'CDP komşuları' : 'CDP neighbors', '#'],
        ['show ip route', isTR ? 'Yönlendirme tablosu' : 'Routing table', '#'],
        ['show clock', isTR ? 'Sistem saati' : 'Display system clock', '#'],
        ['show flash', isTR ? 'Flash içeriği' : 'Display flash', '#'],
        ['show boot', isTR ? 'Boot bilgisi' : 'Display boot info', '#'],
        ['show spanning-tree', isTR ? 'STP durumu' : 'STP status', '#'],
        ['show port-security', isTR ? 'Port güvenliği' : 'Port security status', '#'],
        ['show ssh', isTR ? 'SSH durumu' : 'SSH status', '#'],
        ['show wireless', isTR ? 'Kablosuz durumu' : 'Display wireless status', '#'],
        ['show ip dhcp snooping', isTR ? 'DHCP snooping' : 'Display DHCP snooping', '#'],
        ['show ip dhcp pool', isTR ? 'DHCP havuzları' : 'Display DHCP pools', '#'],
        ['show ip dhcp binding', isTR ? 'DHCP atamaları' : 'DHCP bindings', '#'],
        ['show ip verify source', isTR ? 'Source Guard durumu' : 'IP source guard status', '#'],
        ['show ip source binding', isTR ? 'Source bindingleri' : 'IP source bindings', '#'],
        ['show ip arp inspection', isTR ? 'ARP denetimi' : 'ARP inspection status', '#'],
        ['show interfaces status', isTR ? 'Arayüz durumu' : 'Display port status', '#'],
        ['show storm-control', isTR ? 'Fırtına kontrolü' : 'Storm control status', '#'],
        ['show monitor', isTR ? 'SPAN oturumları' : 'SPAN sessions', '#'],
        ['show udld', isTR ? 'UDLD durumu' : 'UDLD status', '#'],
        ['show cdp', isTR ? 'CDP bilgisi' : 'Display CDP info', '#'],
        ['show vtp status', isTR ? 'VTP durumu' : 'Display VTP status', '#'],
        ['show etherchannel', isTR ? 'EtherChannel' : 'Display EtherChannel', '#'],
        ['show arp', isTR ? 'ARP tablosu' : 'ARP table', '#'],
        ['show mls qos', isTR ? 'QoS durumu' : 'Display QoS status', '#'],
        ['show sdm prefer', isTR ? 'SDM şablonu' : 'Display SDM template', '#'],
        ['show access-lists', isTR ? 'Erişim listeleri' : 'Display access lists', '#'],
        ['show mac access-lists', isTR ? 'MAC erişim listeleri' : 'Display MAC ACLs', '#'],
        ['show history', isTR ? 'Komut geçmişi' : 'Display command history', '#'],
        ['show users', isTR ? 'Kullanıcılar' : 'Connected users', '#'],
        ['show environment', isTR ? 'Donanım durumu' : 'Display hardware status', '#'],
        ['show inventory', isTR ? 'Donanım envanteri' : 'Display inventory', '#'],
        ['show errdisable recovery', isTR ? 'Hata kurtarma' : 'Display errdisable', '#'],
        ['show debug', isTR ? 'Debug durumu' : 'Display debug status', '#'],
        ['show processes', isTR ? 'İşlemler (CPU)' : 'Display processes', '#'],
        ['show memory', isTR ? 'Bellek kullanımı' : 'Display memory usage', '#'],
        ['show system mtu', isTR ? 'MTU ayarları' : 'Display MTU settings', '#'],
        ['show ntp status', isTR ? 'NTP durumu' : 'Display NTP status', '#'],
        ['show snmp', isTR ? 'SNMP bilgisi' : 'Display SNMP info', '#'],
        ['show archive', isTR ? 'Arşiv durumu' : 'Display archive status', '#'],
        ['show alias', isTR ? 'Alias listesi' : 'Display command aliases', '#'],
        ['show diagnostic', isTR ? 'Teşhis sonuçları' : 'Display diagnostics', '#'],
        ['show lldp', isTR ? 'LLDP komşuları' : 'Display LLDP info', '#'],
        ['show authentication', isTR ? 'Kimlik doğrulama' : 'Display auth sessions', '#'],
      ]
    },
    {
      id: 'keyboard',
      icon: Keyboard,
      title: isTR ? 'Klavye Kısayolları' : 'Keyboard Shortcuts',
      type: 'info',
      cmds: [
        // Canvas
        ['Ctrl + Z', isTR ? 'Geri al' : 'Undo'],
        ['Ctrl + Y / Ctrl + Shift + Z', isTR ? 'Yeniden yap' : 'Redo'],
        ['Ctrl + C', isTR ? 'Seçili cihazı kopyala' : 'Copy selected device'],
        ['Ctrl + X', isTR ? 'Seçili cihazı kes' : 'Cut selected device'],
        ['Ctrl + V', isTR ? 'Yapıştır' : 'Paste'],
        ['Ctrl + A', isTR ? 'Tümünü seç' : 'Select all'],
        ['Delete / Backspace', isTR ? 'Seçili öğeyi sil' : 'Delete selected'],
        ['Escape', isTR ? 'Seçimi iptal et / Modu kapat' : 'Cancel selection / Close mode'],
        ['Ctrl + Scroll', isTR ? 'Yakınlaştır / Uzaklaştır' : 'Zoom in / out'],
        ['Space + Sürükle', isTR ? 'Canvas\'ı kaydır' : 'Pan canvas'],
        ['F1', isTR ? 'Yardım panelini aç / kapat' : 'Open / close help panel'],
        // Ping packet panel
        ['P', isTR ? 'Paket analizi: Oynat / Duraklat' : 'Packet analysis: Play / Pause'],
        ['N', isTR ? 'Paket analizi: Sonraki Hop (duraklatıldığında)' : 'Packet analysis: Next Hop (when paused)'],
      ]
    },
    {
      id: 'desktop',
      icon: Terminal,
      title: isTR ? 'Masaüstü Bilgisayar' : 'Desktop Computer',
      type: 'commands',
      cmds: [
        ['ipconfig [/all] [/release] [/renew]', isTR ? 'IP yapılandırması' : 'IP configuration'],
        ['ping <host>', isTR ? 'Bağlantı testi' : 'Test connectivity'],
        ['tracert <host>', isTR ? 'Rota izleme' : 'Trace route'],
        ['netstat', isTR ? 'Ağ istatistikleri' : 'Network statistics'],
        ['nslookup <domain>', isTR ? 'DNS sorgusu' : 'DNS lookup'],
        ['telnet <host> [port]', isTR ? 'Telnet bağlantısı' : 'Telnet connection'],
        ['ssh [-l user] <host>', isTR ? 'SSH bağlantısı' : 'SSH connection'],
        ['curl / wget <url>', isTR ? 'Web sayfası görüntüle' : 'View web page'],
        ['arp -a', isTR ? 'ARP tablosu' : 'ARP table'],
        ['hostname', isTR ? 'Bilgisayar adı' : 'Computer name'],
        ['dir', isTR ? 'Dosya listesi' : 'Directory listing'],
        ['ver', isTR ? 'Versiyon bilgisi' : 'Version info'],
        ['cls', isTR ? 'Ekranı temizle' : 'Clear screen'],
        ['snake / yilan', isTR ? 'Yılan Oyunu' : 'Snake Game'],
        ['help / ?', isTR ? 'PC komut yardımı' : 'Desktop command help'],
      ]
    },
    {
      id: 'network-terms',
      icon: Book,
      title: isTR ? 'Ağ Terimleri' : 'Network Terms',
      type: 'info',
      cmds: [
        ['IP Address', isTR ? 'Ağda cihazı tanımlayan benzersiz sayısal adres (örn: 192.168.1.1)' : 'Unique numerical address identifying a device on a network (e.g., 192.168.1.1)'],
        ['MAC Address', isTR ? 'Ağ kartının fiziksel adresi, 48-bit onaltılı format (örn: 00-1a-2b-3c-4d-5e)' : 'Physical address of network interface, 48-bit hex format (e.g., 00-1a-2b-3c-4d-5e)'],
        ['Gateway', isTR ? 'Farklı ağlara erişim sağlayan cihaz, genellikle router' : 'Device providing access to other networks, typically a router'],
        ['Subnet Mask', isTR ? 'IP adresinin ağ ve host kısımlarını ayıran sayı (örn: 255.255.255.0)' : 'Separates network and host portions of IP address (e.g., 255.255.255.0)'],
        ['Router', isTR ? 'Ağlar arasında veri yönlendiren cihaz' : 'Device that routes data between networks'],
        ['Switch', isTR ? 'Yerel ağda cihazları birbirine bağlayan cihaz' : 'Device connecting devices within local network'],
        ['Firewall', isTR ? 'Yetkisiz ağ erişimini engelleyen güvenlik sistemi' : 'Security system blocking unauthorized network access'],
        ['Port', isTR ? 'Hizmet ve protokolleri tanımlayan sayısal kimlik (SSH: 22, HTTP: 80, HTTPS: 443)' : 'Numerical identifier for services (SSH: 22, HTTP: 80, HTTPS: 443)'],
        ['Protocol', isTR ? 'Ağ iletişimi için kuralları tanımlayan standart' : 'Standard defining rules for network communication'],
        ['Bandwidth', isTR ? 'Ağ bağlantısının saniye cinsinden veri aktarım kapasitesi (Mbps, Gbps)' : 'Network link capacity measured in data transfer per second (Mbps, Gbps)'],
        ['Ping', isTR ? 'Cihazlar arasındaki iletişim hızı, milisaniye cinsinden' : 'Communication speed between devices, measured in milliseconds'],
        ['Packet', isTR ? 'Ağda iletilen veri biriminin adı' : 'Unit of data transmitted over network'],
        ['VLAN', isTR ? 'Fiziksel ağı mantıksal gruplara bölen sistem' : 'System partitioning physical network into logical groups'],
        ['Proxy', isTR ? 'İstemci ile sunucu arasında aracı görev yapan sunucu' : 'Server acting as intermediary between client and server'],
        ['VPN', isTR ? 'İnternet üzerinden güvenli ve şifreli bağlantı' : 'Secure encrypted connection over the internet'],
      ]
    },
    {
      id: 'abbreviations',
      icon: Zap,
      title: isTR ? 'Ağ Kısaltmaları' : 'Network Abbreviations',
      type: 'info',
      cmds: [
        ['DHCP', isTR ? 'Dynamic Host Configuration Protocol - IP adreslerini otomatik olarak atayan protokol' : 'Dynamic Host Configuration Protocol - automatically assigns IP addresses'],
        ['DNS', isTR ? 'Domain Name System - Alan adlarını IP adreslerine çeviren sistem' : 'Domain Name System - converts domain names to IP addresses'],
        ['ARP', isTR ? 'Address Resolution Protocol - IP adresini MAC adresine çeviren protokol' : 'Address Resolution Protocol - converts IP to MAC address'],
        ['TCP', isTR ? 'Transmission Control Protocol - Güvenilir, bağlantı tabanlı protokol' : 'Transmission Control Protocol - reliable, connection-based protocol'],
        ['UDP', isTR ? 'User Datagram Protocol - Hızlı, bağlantısız protokol' : 'User Datagram Protocol - fast, connectionless protocol'],
        ['SSH', isTR ? 'Secure Shell - Güvenli uzak bağlantı protokolü' : 'Secure Shell - secure remote connection protocol'],
        ['HTTP', isTR ? 'HyperText Transfer Protocol - Web sayfaları için protokol' : 'HyperText Transfer Protocol - protocol for web pages'],
        ['HTTPS', isTR ? 'HTTP Secure - Şifreli HTTP protokolü' : 'HTTP Secure - encrypted HTTP protocol'],
        ['FTP', isTR ? 'File Transfer Protocol - Dosya aktarımı protokolü' : 'File Transfer Protocol - file transfer protocol'],
        ['SFTP', isTR ? 'SSH File Transfer Protocol - Güvenli dosya aktarımı' : 'SSH File Transfer Protocol - secure file transfer'],
        ['SMTP', isTR ? 'Simple Mail Transfer Protocol - E-posta gönderme protokolü' : 'Simple Mail Transfer Protocol - email sending protocol'],
        ['POP3', isTR ? 'Post Office Protocol 3 - E-posta alma protokolü' : 'Post Office Protocol 3 - email receiving protocol'],
        ['IMAP', isTR ? 'Internet Message Access Protocol - E-posta yönetimi protokolü' : 'Internet Message Access Protocol - email management protocol'],
        ['QoS', isTR ? 'Quality of Service - Hizmet Kalitesi' : 'Quality of Service - network traffic priority'],
        ['MTU', isTR ? 'Maximum Transmission Unit - Maksimum Aktarım Birimi' : 'Maximum Transmission Unit - maximum packet size'],
        ['RFC', isTR ? 'Request for Comments - İnternet standartlarını tanımlayan dokümanlardır' : 'Request for Comments - internet standard documentation'],
        ['CIDR', isTR ? 'Classless Inter-Domain Routing - IP blokları gösterim yöntemi' : 'Classless Inter-Domain Routing - IP notation method'],
        ['ICMP', isTR ? 'Internet Control Message Protocol - Ağ diagnostik protokolü' : 'Internet Control Message Protocol - network diagnostic protocol'],
        ['MAC', isTR ? 'Media Access Control - Ağ kartının fiziksel adresi, 48-bit onaltılı format (örn: 00-1a-2b-3c-4d-5e)' : 'Media Access Control - physical address of network interface, 48-bit hex format (e.g., 00-1a-2b-3c-4d-5e)'],
        ['IP', isTR ? 'Internet Protocol - Ağda cihazı tanımlayan benzersiz sayısal adres (örn: 192.168.1.1)' : 'Internet Protocol - unique numerical address identifying a device on a network (e.g., 192.168.1.1)'],
        ['NAT', isTR ? 'Network Address Translation - Ağ adresi dönüştürme' : 'Network Address Translation - translates private IPs to public'],
        ['ACL', isTR ? 'Access Control List - Erişim kontrol listesi' : 'Access Control List - filters network traffic'],
        ['VPN', isTR ? 'Virtual Private Network - İnternet üzerinden güvenli ve şifreli bağlantı' : 'Virtual Private Network - secure encrypted connection over the internet'],
        ['WLAN', isTR ? 'Wireless Local Area Network - Kablosuz yerel ağ' : 'Wireless Local Area Network - wireless local network'],
        ['SSID', isTR ? 'Service Set Identifier - Kablosuz ağ adı' : 'Service Set Identifier - wireless network name'],
        ['STP', isTR ? 'Spanning Tree Protocol - Ağ halkalarını önleyen protokol' : 'Spanning Tree Protocol - prevents network loops'],
        ['OSPF', isTR ? 'Open Shortest Path First - Dinamik yönlendirme protokolü' : 'Open Shortest Path First - dynamic routing protocol'],
        ['RIP', isTR ? 'Routing Information Protocol - Basit yönlendirme protokolü' : 'Routing Information Protocol - basic routing protocol'],
        ['BGP', isTR ? 'Border Gateway Protocol - InterASA yönlendirme protokolü' : 'Border Gateway Protocol - inter-AS routing protocol'],
        ['SNMP', isTR ? 'Simple Network Management Protocol - Ağ yönetim protokolü' : 'Simple Network Management Protocol - network management protocol'],
        ['NTP', isTR ? 'Network Time Protocol - Ağ zaman senkronizasyon' : 'Network Time Protocol - network time synchronization'],
        ['LDAP', isTR ? 'Lightweight Directory Access Protocol - Kullanıcı dizin hizmeti' : 'Lightweight Directory Access Protocol - directory service protocol'],
        ['SSL/TLS', isTR ? 'Secure Socket Layer / Transport Layer Security - Şifreleme protokolü' : 'Secure Socket Layer / Transport Layer Security - encryption protocol'],
        ['L2TP', isTR ? 'Layer 2 Tunneling Protocol - Tünel oluşturma protokolü' : 'Layer 2 Tunneling Protocol - tunneling protocol'],
        ['GRE', isTR ? 'Generic Routing Encapsulation - Jenerik yönlendirme protokolü' : 'Generic Routing Encapsulation - generic tunneling protocol'],
      ]
    },
  ];
}
