import { Shield, Radio, Settings, Wifi, Router, Server, Network, Eye, LucideIcon } from 'lucide-react';

export interface CommandDefinition {
  id: string;
  icon: LucideIcon;
  title: string;
  cmds: [string, string, string?][];
  type?: 'commands' | 'info' | 'examples';
}

export function getNetSimCommands(isTR: boolean): CommandDefinition[] {
  return [
    {
      id: 'firewall',
      icon: Shield,
      title: isTR ? 'Güvenlik Duvarı' : 'Firewall',
      type: 'commands',
      cmds: [
        ['nameif <name>', isTR ? 'Arayüz adını belirle' : 'Set interface name', '(config-if)#'],
        ['no nameif', isTR ? 'Arayüz adını sil' : 'Remove interface name', '(config-if)#'],
        ['security-level <0-100>', isTR ? 'Güvenlik seviyesi ata' : 'Set security level', '(config-if)#'],
        ['ip access-group <id> {in|out}', isTR ? 'ACL\'yi arayüze uygula' : 'Apply ACL to interface', '(config-if)#'],
        ['show nameif', isTR ? 'Arayüz adlarını göster' : 'Show interface names', '#'],
        ['show ip access-group', isTR ? 'ACL uygulamalarını göster' : 'Show applied ACLs', '#'],
      ]
    },
    {
      id: 'acl',
      icon: Shield,
      title: isTR ? 'Erişim Kontrol Listeleri (ACL)' : 'Access Control Lists (ACL)',
      type: 'commands',
      cmds: [
        ['access-list <1-99> {permit|deny} <source> [wildcard]', isTR ? 'Standart numaralı ACL kuralı oluştur' : 'Create standard numbered ACL rule', '(config)#'],
        ['access-list <100-199> {permit|deny} <protocol> <source> <dest> [operator port]', isTR ? 'Genişletilmiş numaralı ACL kuralı oluştur' : 'Create extended numbered ACL rule', '(config)#'],
        ['no access-list <id>', isTR ? 'Numaralı ACL\'yi sil' : 'Remove numbered ACL', '(config)#'],
        ['ip access-list {standard|extended} <name>', isTR ? 'Adlandırılmış ACL oluştur' : 'Create named ACL', '(config)#'],
        ['no ip access-list {standard|extended} <name>', isTR ? 'Adlandırılmış ACL\'yi sil' : 'Remove named ACL', '(config)#'],
        ['permit <rule>', isTR ? 'İzin verme kuralı (ACL modunda)' : 'Permit rule (in ACL mode)', '(config-std-nacl)#'],
        ['deny <rule>', isTR ? 'Engelleme kuralı (ACL modunda)' : 'Deny rule (in ACL mode)', '(config-std-nacl)#'],
        ['ip access-group <id|name> {in|out}', isTR ? 'ACL\'yi IP arayüzüne uygula' : 'Apply ACL to IP interface', '(config-if)#'],
        ['show access-lists [<id|name>]', isTR ? 'Tanımlı ACL\'leri ve kuralları göster' : 'Display defined ACLs and rules', '#'],
      ]
    },
    {
      id: 'wlc',
      icon: Radio,
      title: isTR ? 'WLC / AP Yönetimi' : 'WLC / AP Management',
      type: 'commands',
      cmds: [
        ['ap name <name>', isTR ? 'Access Point adlandır' : 'Name the Access Point', '(config)#'],
        ['ap auth-mac <mac>', isTR ? 'AP MAC adres yetkilendirmesi' : 'AP MAC address authorization', '(config)#'],
        ['ap rf-channel <num>', isTR ? 'AP RF kanalını ayarla' : 'Set AP RF channel', '(config)#'],
        ['show ap summary', isTR ? 'AP özetini göster' : 'Show AP summary', '#'],
        ['show ap config [name]', isTR ? 'AP yapılandırmasını göster' : 'Show AP configuration', '#'],
        ['show ap join statistics [name]', isTR ? 'AP katılım istatistiklerini göster' : 'Show AP join statistics', '#'],
        ['show wlan summary', isTR ? 'WLAN özetini göster' : 'Show WLAN summary', '#'],
        ['show wlan <id>', isTR ? 'WLAN detaylarını göster' : 'Show WLAN details', '#'],
      ]
    },
    {
      id: 'interface',
      icon: Settings,
      title: isTR ? 'Arayüz Yapılandırması' : 'Interface Config',
      type: 'commands',
      cmds: [
        ['shutdown', isTR ? 'Arayüzü kapat' : 'Disable interface', '(config-if)#'],
        ['no shutdown', isTR ? 'Arayüzü aç' : 'Enable interface', '(config-if)#'],
        ['speed {10|100|1000|10000|auto}', isTR ? 'Hız ayarla' : 'Set speed', '(config-if)#'],
        ['duplex {half|full|auto}', isTR ? 'Duplex ayarla' : 'Set duplex', '(config-if)#'],
        ['description <text>', isTR ? 'Arayüz açıklaması' : 'Set description', '(config-if)#'],
        ['no description', isTR ? 'Açıklamayı sil' : 'Clear description', '(config-if)#'],
        ['switchport mode access', isTR ? 'Erişim modu' : 'Access mode', '(config-if)#'],
        ['switchport mode trunk', isTR ? 'Trunk modu' : 'Trunk mode', '(config-if)#'],
        ['switchport trunk encapsulation dot1q', isTR ? 'Trunk kapsülleme' : 'Trunk encapsulation', '(config-if)#'],
        ['encapsulation dot1q <vlan>', isTR ? 'Subinterface VLANı' : 'Subinterface VLAN', '(config-subif)#'],
        ['switchport mode dynamic {m}', isTR ? 'DTP modu' : 'Set DTP mode', '(config-if)#'],
        ['switchport mode dot1q-tunnel', isTR ? 'Dot1q tunnel' : 'Dot1q tunnel mode', '(config-if)#'],
        ['no switchport mode', isTR ? 'Modu sıfırla' : 'Reset switchport mode', '(config-if)#'],
        ['switchport access vlan <id>', isTR ? 'VLAN ata' : 'Assign VLAN', '(config-if)#'],
        ['no switchport access vlan', isTR ? 'VLAN atamasını sil' : 'Remove VLAN assign', '(config-if)#'],
        ['switchport trunk native <id>', isTR ? 'Native VLAN' : 'Set native VLAN', '(config-if)#'],
        ['switchport trunk allowed <l>', isTR ? 'İzinli VLANlar' : 'Set allowed VLANs', '(config-if)#'],
        ['switchport nonegotiate', isTR ? 'DTP\'yi kapat' : 'Disable DTP', '(config-if)#'],
        ['switchport voice vlan <id>', isTR ? 'Ses VLAN\'ı' : 'Set voice VLAN', '(config-if)#'],
        ['switchport port-security', isTR ? 'Port güvenliği' : 'Port security', '(config-if)#'],
        ['switchport port-security max <n>', isTR ? 'Maksimum MAC' : 'Set max MACs', '(config-if)#'],
        ['switchport port-security violation {a}', isTR ? 'İhlal aksiyonu' : 'Violation action', '(config-if)#'],
        ['switchport port-security sticky', isTR ? 'Sticky MAC' : 'Enable sticky MAC', '(config-if)#'],
        ['switchport port-security aging time <n>', isTR ? 'Güvenlik yaşlanma süresi' : 'Port-security aging time', '(config-if)#'],
        ['no switchport port-security', isTR ? 'Güvenliği kapat' : 'Disable port security', '(config-if)#'],
        ['switchport protected', isTR ? 'Korumalı port' : 'Protected port', '(config-if)#'],
        ['switchport block {unicast|multicast}', isTR ? 'Trafik bloklama' : 'Block traffic', '(config-if)#'],
        ['no switchport', isTR ? 'L3 portuna dönüştür' : 'Convert to L3 port', '(config-if)#'],
        ['spanning-tree portfast', isTR ? 'PortFast aç' : 'Enable PortFast', '(config-if)#'],
        ['spanning-tree bpduguard {e|d}', isTR ? 'BPDU Guard' : 'BPDU Guard', '(config-if)#'],
        ['spanning-tree cost <cost>', isTR ? 'STP maliyeti' : 'Set STP cost', '(config-if)#'],
        ['spanning-tree priority <p>', isTR ? 'STP önceliği' : 'Set STP priority', '(config-if)#'],
        ['ip address <ip> <mask>', isTR ? 'IP adresi ata' : 'Set IP address', '(config-if)#'],
        ['ipv6 address <ip>/<p>', isTR ? 'IPv6 adresi ata' : 'Set IPv6 address', '(config-if)#'],
        ['no ip address', isTR ? 'IP adresini sil' : 'Remove IP address', '(config-if)#'],
        ['ip default-gateway <ip>', isTR ? 'Arayüz gateway' : 'Interface gateway', '(config-if)#'],
        ['no ip default-gateway', isTR ? 'Gateway sil' : 'Remove gateway', '(config-if)#'],
        ['ip helper-address <ip>', isTR ? 'DHCP relay' : 'Set DHCP relay', '(config-if)#'],
        ['no ip helper-address', isTR ? 'DHCP relay sil' : 'Remove DHCP relay', '(config-if)#'],
        ['ip verify source', isTR ? 'IP Source Guard' : 'Enable Source Guard', '(config-if)#'],
        ['ip dhcp snooping trust', isTR ? 'Güvenli DHCP portu' : 'DHCP snooping trust', '(config-if)#'],
        ['ip arp inspection trust', isTR ? 'Güvenli ARP portu' : 'ARP inspection trust', '(config-if)#'],
        ['storm-control {b|m|u} lvl', isTR ? 'Fırtına kontrolü' : 'Storm control', '(config-if)#'],
        ['power inline {auto|static}', isTR ? 'PoE yapılandırması' : 'Configure PoE', '(config-if)#'],
        ['bandwidth <kbps>', isTR ? 'Bant genişliği' : 'Set bandwidth', '(config-if)#'],
        ['delay <tens-of-ms>', isTR ? 'Gecikme süresi' : 'Set delay', '(config-if)#'],
        ['mls qos trust {cos|dscp}', isTR ? 'QoS güven durumu' : 'Set QoS trust', '(config-if)#'],
        ['mls qos cos <val>', isTR ? 'Default CoS değeri' : 'Set default CoS', '(config-if)#'],
        ['cdp enable', isTR ? 'CDP\'yi aç (arayüz)' : 'Enable CDP (interface)', '(config-if)#'],
        ['no udld', isTR ? 'UDLD\'yi kapat' : 'Disable UDLD', '(config-if)#'],
        ['no ip proxy-arp', isTR ? 'Proxy ARP kapat' : 'Disable proxy ARP', '(config-if)#'],
        ['no keepalive', isTR ? 'Keepalive kapat' : 'Disable keepalive', '(config-if)#'],
        ['load-interval <sec>', isTR ? 'İstatistik aralığı' : 'Set load interval', '(config-if)#'],
        ['carrier-delay <ms>', isTR ? 'Carrier gecikmesi' : 'Set carrier delay', '(config-if)#'],
        ['channel-group <n> mode', isTR ? 'EtherChannel' : 'EtherChannel', '(config-if)#'],
        ['no channel-group', isTR ? 'EtherChannel sil' : 'Remove from channel', '(config-if)#'],
        ['encapsulation hdlc', isTR ? 'HDLC kapsülleme (seri)' : 'HDLC encapsulation (serial)', '(config-if)#'],
        ['encapsulation ppp', isTR ? 'PPP kapsülleme (seri)' : 'PPP encapsulation (serial)', '(config-if)#'],
        ['clock rate <bps>', isTR ? 'Saat hızı (DCE seri)' : 'Clock rate (DCE serial)', '(config-if)#'],
        ['ppp authentication pap', isTR ? 'PPP PAP kimlik doğrulama' : 'PPP PAP authentication', '(config-if)#'],
        ['ppp authentication chap', isTR ? 'PPP CHAP kimlik doğrulama' : 'PPP CHAP authentication', '(config-if)#'],
        ['ppp pap sent-username <u> <p>', isTR ? 'PAP kullanıcı adı/şifre' : 'PAP username/password', '(config-if)#'],
        ['ip access-group <id> {in|out}', isTR ? 'ACL uygula' : 'Apply ACL', '(config-if)#'],
        ['ip nat {inside|outside}', isTR ? 'NAT tarafı seç' : 'Set NAT side', '(config-if)#'],
        ['ip vrf forwarding <name>', isTR ? 'Arayüzü VRF sanal yönlendirmesine ata' : 'Assign interface to VRF instance', '(config-if)#'],
        ['zone-member security <name>', isTR ? 'Arayüzü ZBF güvenlik bölgesine ata' : 'Assign interface to ZBF security zone', '(config-if)#'],
        ['interface nve<id>', isTR ? 'VXLAN NVE arayüzü oluştur / gir' : 'Create/enter VXLAN NVE interface', '(config)#'],
        ['member vni <vni> [vlan <vlan-id>]', isTR ? 'VXLAN VNI - VLAN eşlemesi tanımla' : 'Map VXLAN VNI to VLAN', '(config-if-nve)#'],
        ['standby <g> ip <vip>', isTR ? 'HSRP Sanal IP' : 'HSRP Virtual IP', '(config-if)#'],
        ['standby <g> priority <p>', isTR ? 'HSRP Önceliği' : 'HSRP Priority', '(config-if)#'],
        ['glbp <g> ip <vip>', isTR ? 'GLBP Sanal IP Adresi' : 'GLBP Virtual IP Address', '(config-if)#'],
        ['glbp <g> priority <p>', isTR ? 'GLBP Önceliği (AVG seçimi)' : 'GLBP Priority (AVG election)', '(config-if)#'],
        ['glbp <g> preempt', isTR ? 'GLBP Preemption (Geri devralma)' : 'GLBP Preemption mode', '(config-if)#'],
        ['ip flow {ingress|egress}', isTR ? 'Arayüzde NetFlow izleme aç' : 'Enable NetFlow monitoring on interface', '(config-if)#'],
        ['ip flow monitor <name>', isTR ? 'Arayüzde esnek NetFlow monitor uygula' : 'Apply Flexible NetFlow monitor on interface', '(config-if)#'],
        ['spanning-tree guard loop', isTR ? 'Arayüzde Loop Guard aç' : 'Enable Loop Guard on interface', '(config-if)#'],
        ['ipv6 eigrp <as>', isTR ? 'IPv6 EIGRP\'yi arayüzde etkinleştir' : 'Enable IPv6 EIGRP on interface', '(config-if)#'],
        ['monitor session <n>', isTR ? 'SPAN/RSPAN' : 'Configure SPAN/RSPAN', '(config-if)#'],
      ]
    },
    {
      id: 'wireless',
      icon: Wifi,
      title: isTR ? 'Kablosuz (WiFi / Dot11)' : 'Wireless (WiFi / Dot11)',
      type: 'commands',
      cmds: [
        ['dot11 ssid <name>', isTR ? 'SSID yapılandırmasına gir' : 'Enter SSID config', '(config)#'],
        ['authentication open', isTR ? 'Açık kimlik doğrulama' : 'Open authentication', '(config-ssid)#'],
        ['authentication shared', isTR ? 'Paylaşımlı kimlik doğrulama' : 'Shared authentication', '(config-ssid)#'],
        ['authentication network-eap', isTR ? 'EAP kimlik doğrulama' : 'EAP authentication', '(config-ssid)#'],
        ['authentication key-management wpa version {1|2}', isTR ? 'WPA anahtar yönetimi' : 'WPA key management', '(config-ssid)#'],
        ['wpa-psk ascii <key>', isTR ? 'WPA ön-paylaşımlı anahtar' : 'WPA pre-shared key', '(config-ssid)#'],
        ['guest-mode', isTR ? 'SSID\'yi yayınla (Beacon)' : 'Broadcast SSID (Beacon)', '(config-ssid)#'],
        ['no guest-mode', isTR ? 'SSID yayınını kapat' : 'Stop SSID broadcast', '(config-ssid)#'],
        ['wlan <name> <id> <ssid>', isTR ? 'WLAN oluştur (kontrol cihazı)' : 'Create WLAN (controller)', '(config)#'],
        ['no wlan <id>', isTR ? 'WLAN sil' : 'Delete WLAN', '(config)#'],
        ['security wpa psk set-key ascii 0 <pass>', isTR ? 'WPA şifresi ayarla (WLAN)' : 'Set WPA password (WLAN)', '(config-wlan)#'],
        ['interface Dot11Radio <n>', isTR ? 'Radyo arayüzüne gir' : 'Enter radio interface', '(config)#'],
        ['encryption mode ciphers {aes-ccm|tkip}', isTR ? 'şifreleme yöntemi' : 'Encryption method', '(config-if)#'],
        ['ssid <name>', isTR ? 'SSID\'yi radyo arayüzüne bağla' : 'Bind SSID to radio interface', '(config-if)#'],
        ['no ssid <name>', isTR ? 'SSID bağlantısını kaldır' : 'Remove SSID binding', '(config-if)#'],
        ['channel <num>', isTR ? 'RF kanalı ayarla' : 'Set RF channel', '(config-if)#'],
        ['power local <mw>', isTR ? 'İletim gücü ayarla' : 'Set transmit power', '(config-if)#'],
        ['station-role {root|repeater|client}', isTR ? 'AP çalışma modu' : 'AP role mode', '(config-if)#'],
        ['mac-filter', isTR ? 'MAC filtrelemeyi aç' : 'Enable MAC filtering', '(config-if)#'],
        ['no mac-filter', isTR ? 'MAC filtrelemeyi kapat' : 'Disable MAC filtering', '(config-if)#'],
        ['show dot11 associations', isTR ? 'Kablosuz istemcileri göster' : 'Show wireless clients', '#'],
        ['show dot11 statistics', isTR ? 'Kablosuz istatistikleri' : 'Show wireless statistics', '#'],
      ]
    },
    {
      id: 'line',
      icon: Router,
      title: isTR ? 'Hat Yapılandırması' : 'Line Config',
      type: 'commands',
      cmds: [
        ['line console 0', isTR ? 'Konsol hattı' : 'Console line', '(config)#'],
        ['line vty 0 4', isTR ? 'VTY hatları (0-4)' : 'VTY lines (0-4)', '(config)#'],
        ['line vty 5 15', isTR ? 'VTY hatları (5-15)' : 'VTY lines (5-15)', '(config)#'],
        ['line aux 0', isTR ? 'Aux hattı' : 'Auxiliary line', '(config)#'],
        ['password <pass>', isTR ? 'şifre ayarla' : 'Set password', '(config-line)#'],
        ['no password', isTR ? 'şifreyi sil' : 'Remove password', '(config-line)#'],
        ['login', isTR ? 'Giriş kontrolü' : 'Enable login', '(config-line)#'],
        ['no login', isTR ? 'Giriş kontrolü kapat' : 'Disable login', '(config-line)#'],
        ['transport input {p}', isTR ? 'Giriş protokolleri' : 'Input protocols', '(config-line)#'],
        ['transport output {p}', isTR ? 'Çıkış protokolleri' : 'Output protocols', '(config-line)#'],
        ['no transport input', isTR ? 'Girişleri sıfırla' : 'Reset transport input', '(config-line)#'],
        ['logging synchronous', isTR ? 'Senkron loglama' : 'Sync logging', '(config-line)#'],
        ['no logging synchronous', isTR ? 'Senkron log kapat' : 'Disable sync logging', '(config-line)#'],
        ['exec-timeout <m> [s]', isTR ? 'Zaman aşımı' : 'Exec timeout', '(config-line)#'],
        ['no exec-timeout', isTR ? 'Zaman aşımı sıfırla' : 'Reset exec timeout', '(config-line)#'],
        ['history size <n>', isTR ? 'Geçmiş boyutu' : 'Set history size', '(config-line)#'],
        ['no history', isTR ? 'Geçmişi kapat' : 'Disable history', '(config-line)#'],
        ['exec', isTR ? 'EXEC aktif' : 'Enable EXEC', '(config-line)#'],
        ['no exec', isTR ? 'EXEC pasif' : 'Disable EXEC', '(config-line)#'],
        ['autocommand <cmd>', isTR ? 'Otomatik komut' : 'Set auto-command', '(config-line)#'],
        ['no autocommand', isTR ? 'Otomatik komut sil' : 'Remove auto-command', '(config-line)#'],
        ['transport preferred {ssh|telnet|none}', isTR ? 'Tercih edilen protokol' : 'Preferred protocol', '(config-line)#'],
        ['privilege level <0-15>', isTR ? 'Yetki seviyesi' : 'Set privilege level', '(config-line)#'],
        ['session-limit <n>', isTR ? 'Oturum sınırı' : 'Session limit', '(config-line)#'],
        ['access-class <n> {in|out}', isTR ? 'ACL uygula (line)' : 'Apply access-class', '(config-line)#'],
        ['lockable', isTR ? 'Kilitlenebilir hat' : 'Enable lockable', '(config-line)#'],
      ]
    },
    {
      id: 'administration',
      icon: Server,
      title: isTR ? 'Yönetim' : 'Administration',
      type: 'commands',
      cmds: [
        ['disconnect <session>', isTR ? 'Oturumu kes' : 'Disconnect session', '(config)#'],
        ['resume <session>', isTR ? 'Oturuma devam et' : 'Resume session', '(config)#'],
        ['suspend', isTR ? 'Oturumu askıya al' : 'Suspend session', '(config)#'],
        ['setup', isTR ? 'Kurulum sihirbazı' : 'Setup wizard', '(config)#'],
        ['test', isTR ? 'Tanılama testi' : 'Diagnostic test', '(config)#'],
        ['configure replace <url>', isTR ? 'Yapılandırmayı dosyadan değiştir' : 'Replace config from file', '(config)#'],
        ['archive', isTR ? 'Arşiv yapılandırması' : 'Archive configuration', '(config)#'],
        ['terminal length <0-512>', isTR ? 'Terminal satır uzunluğu' : 'Set terminal length', '(config)#'],
        ['terminal width <n>', isTR ? 'Terminal genişliği' : 'Set terminal width', '(config)#'],
        ['terminal monitor', isTR ? 'Log mesajlarını görüntüle' : 'Monitor log messages', '(config)#'],
        ['terminal no monitor', isTR ? 'Log görüntülemeyi kapat' : 'Stop monitoring logs', '(config)#'],
        ['help', isTR ? 'Yardım sistemini göster' : 'Display help system', '(config)#'],
        ['alias <mode> <name> <cmd>', isTR ? 'Komut takma adı' : 'Create command alias', '(config)#'],
        ['no alias <name>', isTR ? 'Alias sil' : 'Remove command alias', '(config)#'],
        ['more <filename>', isTR ? 'Dosya içeriğini göster' : 'Display file contents', '(config)#'],
        ['clear terminal', isTR ? 'Terminalı temizle' : 'Clear terminal', '(config)#'],
        ['clear line <n>', isTR ? 'Hattı sil' : 'Clear line', '(config)#'],
        ['access-class <n> {in|out}', isTR ? 'ACL uygula' : 'Apply access-class', '(config)#'],
        ['lockable', isTR ? 'Kilitlenebilir hat' : 'Enable lockable', '(config)#'],
        ['exec', isTR ? 'EXEC aktif' : 'Enable EXEC', '(config)#'],
        ['no exec', isTR ? 'EXEC pasif' : 'Disable EXEC', '(config)#'],
        ['autocommand <cmd>', isTR ? 'Otomatik komut' : 'Set auto-command', '(config)#'],
        ['no autocommand', isTR ? 'Otomatik komut sil' : 'Remove auto-command', '(config)#'],
        ['transport preferred {ssh|telnet|none}', isTR ? 'Tercih edilen protokol' : 'Preferred protocol', '(config)#'],
        ['privilege level <0-15>', isTR ? 'Yetki seviyesi' : 'Set privilege level', '(config)#'],
        ['session-limit <n>', isTR ? 'Oturum sınırı' : 'Session limit', '(config)#'],
      ]
    },
    {
      id: 'router',
      icon: Network,
      title: isTR ? 'Yönlendirme (Routing)' : 'Routing Config',
      type: 'commands',
      cmds: [
        ['router rip', isTR ? 'RIP yönlendirmesi' : 'Enable RIP', '(config)#'],
        ['router ospf [<id>]', isTR ? 'OSPF yönlendirmesi' : 'Enable OSPF', '(config)#'],
        ['router eigrp <as>', isTR ? 'EIGRP yönlendirmesi' : 'Enable EIGRP', '(config)#'],
        ['router bgp <as>', isTR ? 'BGP yönlendirmesi' : 'Enable BGP', '(config)#'],
        ['no router {rip|ospf|eigrp|bgp}', isTR ? 'Yönlendirmeyi kapat' : 'Disable routing', '(config)#'],
        ['network <ip> [wildcard]', isTR ? 'Ağ ekle (RIP/EIGRP)' : 'Add network (RIP/EIGRP)', '(config-router)#'],
        ['network <ip> area <id>', isTR ? 'OSPF ağı ekle' : 'Add OSPF network', '(config-router)#'],
        ['neighbor <ip> remote-as <as>', isTR ? 'BGP komşusu ekle' : 'Add BGP neighbor', '(config-router)#'],
        ['neighbor <ip> route-map <map> {in|out}', isTR ? 'BGP komşusuna Route-Map kuralı bağla' : 'Bind Route-Map policy to BGP neighbor', '(config-router)#'],
        ['neighbor <ip> weight <value>', isTR ? 'BGP komşu rota ağırlığı (Weight) ata' : 'Set BGP neighbor route weight', '(config-router)#'],
        ['no neighbor <ip> remote-as', isTR ? 'BGP komşusunu sil' : 'Remove BGP neighbor', '(config-router)#'],
        ['router-id <ip>', isTR ? 'Router ID ayarla' : 'Set router ID', '(config-router)#'],
        ['passive-interface <int>', isTR ? 'Pasif arayüz' : 'Passive interface', '(config-router)#'],
        ['no passive-interface <int>', isTR ? 'Pasif arayüz kaldır' : 'Remove passive interface', '(config-router)#'],
        ['default-info originate', isTR ? 'Varsayılan rota' : 'Default route', '(config-router)#'],
        ['auto-summary', isTR ? 'Otomatik özetleme' : 'Auto-summary', '(config-router)#'],
        ['no auto-summary', isTR ? 'Otomatik özetlemeyi kapat' : 'Disable auto-summary', '(config-router)#'],
        ['ipv6 router rip <tag>', isTR ? 'IPv6 RIP yönlendirmesi' : 'Enable IPv6 RIP', '(config)#'],
        ['ipv6 router ospf <id>', isTR ? 'IPv6 OSPF yönlendirmesi' : 'Enable IPv6 OSPF', '(config)#'],
        ['no ipv6 router rip <tag>', isTR ? 'IPv6 RIP kapat' : 'Disable IPv6 RIP', '(config)#'],
        ['no ipv6 router ospf <id>', isTR ? 'IPv6 OSPF kapat' : 'Disable IPv6 OSPF', '(config)#'],
        ['show ip route', isTR ? 'Yönlendirme tablosu' : 'Show routing table', '#'],
        ['show ip ospf [neighbor|interface]', isTR ? 'OSPF detayları' : 'Show OSPF details', '#'],
        ['show ip protocols', isTR ? 'Yönlendirme protokolleri' : 'Show routing protocols', '#'],
        ['show ip eigrp neighbors', isTR ? 'EIGRP komşuları' : 'Show EIGRP neighbors', '#'],
        ['show ip bgp summary', isTR ? 'BGP özeti' : 'Show BGP summary', '#'],
        ['show ip bgp', isTR ? 'BGP tablosu' : 'Show BGP table', '#'],
        ['show ipv6 route', isTR ? 'IPv6 yönlendirme tablosu' : 'Show IPv6 routing table', '#'],
        ['show ipv6 rip', isTR ? 'IPv6 RIP durumu' : 'Show IPv6 RIP status', '#'],
        ['show ipv6 ospf', isTR ? 'IPv6 OSPF durumu' : 'Show IPv6 OSPF status', '#'],
      ]
    },
    {
      id: 'dhcp',
      icon: Server,
      title: isTR ? 'DHCP Havuzu' : 'DHCP Pool Config',
      type: 'commands',
      cmds: [
        ['network <net> <mask>', isTR ? 'Havuz ağı' : 'Pool network', '(config-dhcp)#'],
        ['default-router <ip>', isTR ? 'Varsayılan geçit' : 'Default router', '(config-dhcp)#'],
        ['dns-server <ip>', isTR ? 'DNS sunucusu' : 'DNS server', '(config-dhcp)#'],
        ['lease {days|infinite}', isTR ? 'Kira süresi' : 'Lease duration', '(config-dhcp)#'],
        ['domain-name <name>', isTR ? 'Alan adı' : 'Domain name', '(config-dhcp)#'],
      ]
    },
    {
      id: 'show',
      icon: Eye,
      title: isTR ? 'Show Komutları' : 'Show Commands',
      type: 'commands',
      cmds: [
        ['show', isTR ? 'Özet bilgi' : 'Display summary', '#'],
        ['show running-config', isTR ? 'Çalışan yapılandırma' : 'Running config', '#'],
        ['show startup-config', isTR ? 'Başlangıç yapılandırması' : 'Startup config', '#'],
        ['show version', isTR ? 'Sistem bilgisi' : 'System version', '#'],
        ['show interfaces', isTR ? 'Tüm arayüzler' : 'Display all interfaces', '#'],
        ['show interfaces trunk', isTR ? 'Trunk arayüzler' : 'Display trunks', '#'],
        ['show interface <name>', isTR ? 'Arayüz ayrıntısı' : 'Interface details', '#'],
        ['show ip interface brief', isTR ? 'Arayüz özeti' : 'IP interface brief', '#'],
        ['show ip interface', isTR ? 'IP arayüz detay' : 'IP interface details', '#'],
        ['show ip protocols', isTR ? 'Yönlendirme protokolleri' : 'IP routing protocols', '#'],
        ['show ip ospf [neighbor|interface]', isTR ? 'OSPF detayları' : 'OSPF details', '#'],
        ['show ip nat translations', isTR ? 'NAT çevirileri' : 'NAT translations', '#'],
        ['show ip nat statistics', isTR ? 'NAT istatistikleri' : 'NAT statistics', '#'],
        ['show standby [brief]', isTR ? 'HSRP durumu' : 'HSRP status', '#'],
        ['show ip arp', isTR ? 'ARP tablosu' : 'ARP table', '#'],
        ['show ipv6 interface brief', isTR ? 'IPv6 arayüz özeti' : 'IPv6 interface brief', '#'],
        ['show vlan [brief]', isTR ? 'VLAN listesi' : 'VLAN list', '#'],
        ['show mac address-table', isTR ? 'MAC tablosunu göster' : 'Show MAC address table', '#'],
        ['show cdp neighbors', isTR ? 'CDP komşuları' : 'CDP neighbors', '#'],
        ['show ip route', isTR ? 'Yönlendirme tablosu' : 'Routing table', '#'],
        ['show clock', isTR ? 'Sistem saati' : 'Display system clock', '#'],
        ['show flash', isTR ? 'Flash içeriği' : 'Display flash', '#'],
        ['show boot', isTR ? 'Boot bilgisi' : 'Display boot info', '#'],
        ['show spanning-tree', isTR ? 'STP durumu' : 'STP status', '#'],
        ['show port-security', isTR ? 'Port güvenliği' : 'Port security status', '#'],
        ['show ssh', isTR ? 'SSH durumu' : 'SSH status', '#'],
        ['show crypto isakmp sa', isTR ? 'ISAKMP SA güvenlik durumunu göster' : 'Show ISAKMP SA status', '#'],
        ['show crypto ipsec sa', isTR ? 'IPsec SA tünel istatistiklerini göster' : 'Show IPsec SA statistics', '#'],
        ['show crypto map', isTR ? 'Crypto Map haritalarını göster' : 'Show Crypto Map entries', '#'],
        ['show wireless', isTR ? 'Kablosuz durumu' : 'Display wireless status', '#'],
        ['show ip dhcp snooping', isTR ? 'DHCP snooping' : 'Display DHCP snooping', '#'],
        ['show ip dhcp pool', isTR ? 'DHCP havuzları' : 'Display DHCP pools', '#'],
        ['show ip dhcp binding', isTR ? 'DHCP atamaları' : 'DHCP bindings', '#'],
        ['show ip verify source', isTR ? 'Source Guard durumu' : 'IP source guard status', '#'],
        ['show ip source binding', isTR ? 'Source bindingleri' : 'IP source bindings', '#'],
        ['show ip arp inspection', isTR ? 'ARP denetimi' : 'ARP inspection status', '#'],
        ['show interfaces status', isTR ? 'Arayüz durumu' : 'Display port status', '#'],
        ['show storm-control', isTR ? 'Fırtına kontrolü' : 'Storm control status', '#'],
        ['show monitor', isTR ? 'SPAN oturumları' : 'SPAN sessions', '#'],
        ['show udld', isTR ? 'UDLD durumu' : 'UDLD status', '#'],
        ['show cdp', isTR ? 'CDP bilgisi' : 'Display CDP info', '#'],
        ['show vtp status', isTR ? 'VTP durumu' : 'Display VTP status', '#'],
        ['show etherchannel', isTR ? 'EtherChannel' : 'Display EtherChannel', '#'],
        ['show arp', isTR ? 'ARP tablosu' : 'ARP table', '#'],
        ['show mls qos', isTR ? 'QoS durumu' : 'Display QoS status', '#'],
        ['show sdm prefer', isTR ? 'SDM şablonu' : 'Display SDM template', '#'],
        ['show access-lists', isTR ? 'Erişim listeleri' : 'Display access lists', '#'],
        ['show mac access-lists', isTR ? 'MAC erişim listeleri' : 'Display MAC ACLs', '#'],
        ['show history', isTR ? 'Komut geçmişi' : 'Display command history', '#'],
        ['show users', isTR ? 'Kullanıcılar' : 'Connected users', '#'],
        ['show environment', isTR ? 'Donanım durumu' : 'Display hardware status', '#'],
        ['show inventory', isTR ? 'Donanım envanteri' : 'Display inventory', '#'],
        ['show errdisable recovery', isTR ? 'Hata kurtarma' : 'Display errdisable', '#'],
        ['show debug', isTR ? 'Debug durumu' : 'Display debug status', '#'],
        ['show processes', isTR ? 'İşlemler (CPU)' : 'Display processes', '#'],
        ['show memory', isTR ? 'Bellek kullanımı' : 'Display memory usage', '#'],
        ['show system mtu', isTR ? 'MTU ayarları' : 'Display MTU settings', '#'],
        ['show ntp status', isTR ? 'NTP durumu' : 'Display NTP status', '#'],
        ['show snmp', isTR ? 'SNMP bilgisi' : 'Display SNMP info', '#'],
        ['show archive', isTR ? 'Arşiv durumu' : 'Display archive status', '#'],
        ['show alias', isTR ? 'Alias listesi' : 'Display command aliases', '#'],
        ['show diagnostic', isTR ? 'Teşhis sonuçları' : 'Display diagnostics', '#'],
        ['show lldp', isTR ? 'LLDP komşuları' : 'Display LLDP info', '#'],
        ['show authentication', isTR ? 'Kimlik doğrulama' : 'Display auth sessions', '#'],
        ['show running-config interface <name>', isTR ? 'Arayüz yapılandırması' : 'Show interface config', '#'],
        ['show spanning-tree interface <name>', isTR ? 'Arayüz STP durumu' : 'Show interface STP status', '#'],
        ['show ip ssh', isTR ? 'SSH yapılandırması' : 'Show SSH configuration', '#'],
        ['show cdp neighbors detail', isTR ? 'CDP komşuları detaylı' : 'Show CDP neighbor details', '#'],
        ['show policy-map [name]', isTR ? 'Politika haritası' : 'Show policy map', '#'],
        ['show policy-map interface', isTR ? 'Arayüz politika haritası' : 'Show interface policy map', '#'],
        ['show class-map [name]', isTR ? 'Sınıf haritası' : 'Show class map', '#'],
        ['show qos interface <name>', isTR ? 'Arayüz QoS durumu' : 'Show interface QoS', '#'],
        ['show queuing interface <name>', isTR ? 'Arayüz kuyruk durumu' : 'Show interface queuing', '#'],
        ['show ip ospf interface <name>', isTR ? 'OSPF arayüz durumu' : 'Show OSPF interface', '#'],
        ['show ipv6 route', isTR ? 'IPv6 yönlendirme tablosu' : 'Show IPv6 routing table', '#'],
        ['show ipv6 dhcp pool', isTR ? 'IPv6 DHCP havuzu' : 'Show IPv6 DHCP pool', '#'],
        ['show mac address-table static', isTR ? 'Statik MAC adresleri' : 'Show static MAC addresses', '#'],
        ['show sessions', isTR ? 'Aktif oturumlar' : 'Show active sessions', '#'],
        ['show ntp associations', isTR ? 'NTP ilişkileri' : 'Show NTP associations', '#'],
        ['show hosts', isTR ? 'Host tablosu' : 'Show host table', '#'],
        ['show debugging', isTR ? 'Hata ayıklama durumu' : 'Show debug status', '#'],
        ['show errdisable detect', isTR ? 'Hata algılama ayarları' : 'Show errdisable detection', '#'],
        ['show redundancy', isTR ? 'Yedeklilik durumu' : 'Show redundancy status', '#'],
        ['show controllers <type/n>', isTR ? 'Denetleyici durumu' : 'Show controller status', '#'],
        ['show banner motd', isTR ? 'MOTD banner mesajı' : 'Show MOTD banner', '#'],
      ]
    },
    {
      id: 'bgp_mpls_commands',
      icon: Router,
      title: isTR ? 'BGP, MPLS & L3VPN Komutları' : 'BGP, MPLS & L3VPN Commands',
      type: 'commands',
      cmds: [
        ['router bgp <as>', isTR ? 'BGP yönlendirme sürecini başlat' : 'Start BGP routing process', '(config)'],
        ['neighbor <ip> remote-as <as>', isTR ? 'BGP komşusu ve AS numarası tanımla' : 'Define BGP peer and AS number', '(config-router)'],
        ['network <ip> mask <mask>', isTR ? 'BGP ağı anons et' : 'Advertise network in BGP', '(config-router)'],
        ['address-family vpnv4', isTR ? 'MP-BGP VPNv4 adres ailesine geç' : 'Enter MP-BGP VPNv4 address-family', '(config-router)'],
        ['mpls ip', isTR ? 'Arayüzde MPLS ve LDP etiketlemeyi etkinleştir' : 'Enable MPLS and LDP on interface', '(config-if)'],
        ['show ip bgp', isTR ? 'BGP yönlendirme bilgi tablosunu (RIB) görüntüle' : 'Display BGP routing table (RIB)', '#'],
        ['show ip bgp summary', isTR ? 'BGP komşuluk durumlarını ve sayaçlarını listele' : 'Display BGP neighbor states and counters', '#'],
        ['show mpls forwarding-table', isTR ? 'MPLS LFIB etiket tablosunu görüntüle' : 'Display MPLS LFIB table', '#'],
        ['show mpls ldp neighbor', isTR ? 'LDP komşuluk oturumlarını görüntüle' : 'Display LDP neighbor sessions', '#'],
      ]
    },
  ];
}
