// Komut kısaltmaları için eşleşme - TÜM NETWORK KOMUTLARI
export const commandAliases: Record<string, string> = {
  // Enable/Disable
  'en': 'enable',
  'ena': 'enable',
  'enab': 'enable',
  'dis': 'disable',
  'disa': 'disable',

  // Configure
  'conf': 'configure',
  'conf t': 'configure terminal',
  'config t': 'configure terminal',
  'conf te': 'configure terminal',
  'config te': 'configure terminal',
  'conf ter': 'configure terminal',
  'config ter': 'configure terminal',
  'conf term': 'configure terminal',
  'config term': 'configure terminal',
  'conf termi': 'configure terminal',
  'config termi': 'configure terminal',
  'conf termin': 'configure terminal',
  'config termin': 'configure terminal',
  'conf termina': 'configure terminal',
  'config termina': 'configure terminal',
  'configure t': 'configure terminal',
  'configure te': 'configure terminal',
  'configure ter': 'configure terminal',
  'configure term': 'configure terminal',
  'configure termi': 'configure terminal',
  'configure termin': 'configure terminal',
  'configure termina': 'configure terminal',

  // Show commands
  'sh': 'show',
  'sho': 'show',
  'sh r': 'show running-config',
  'sh ru': 'show running-config',
  'sh run': 'show running-config',
  'sh runn': 'show running-config',
  'sh runni': 'show running-config',
  'sh runnin': 'show running-config',
  'sh running': 'show running-config',
  'sh running-c': 'show running-config',
  'sh running-co': 'show running-config',
  'sh running-con': 'show running-config',
  'sh running-conf': 'show running-config',
  'sh runn-c': 'show running-config',
  'sh runn-co': 'show running-config',

  // Show startup-config commands
  'sh st': 'show startup-config',
  'sh sta': 'show startup-config',
  'sh star': 'show startup-config',
  'sh start': 'show startup-config',
  'sh startu': 'show startup-config',
  'sh startup': 'show startup-config',
  'sh startup-': 'show startup-config',
  'sh startup-c': 'show startup-config',
  'sh startup-co': 'show startup-config',
  'sh startup-con': 'show startup-config',
  'sh startup-conf': 'show startup-config',

  'sh i': 'show interfaces',
  'sh in': 'show interfaces',
  'sh int': 'show interfaces',
  'sh inte': 'show interfaces',
  'sh inter': 'show interfaces',
  'sh interf': 'show interfaces',
  'sh interfa': 'show interfaces',
  'sh interfac': 'show interfaces',
  'sh interface': 'show interfaces',
  'sh interfaces': 'show interfaces',

  'sh vl': 'show vlan',
  'sh vla': 'show vlan',
  'sh vlan': 'show vlan brief',
  'sh vlan b': 'show vlan brief',
  'sh vlan br': 'show vlan brief',
  'sh vlan bre': 'show vlan brief',
  'sh vlanbrie': 'show vlan brief',
  'sh vl b': 'show vlan brief',
  'sh vl br': 'show vlan brief',
  'sh vl bre': 'show vlan brief',

  'sh v': 'show version',
  'sh ve': 'show version',
  'sh ver': 'show version',
  'sh vers': 'show version',
  'sh versi': 'show version',
  'sh versio': 'show version',

  'sh m': 'show mac address-table',
  'sh ma': 'show mac address-table',
  'sh mac': 'show mac address-table',
  'sh mac-': 'show mac address-table',
  'sh mac-a': 'show mac address-table',
  'sh mac-ad': 'show mac address-table',
  'sh mac-addr': 'show mac address-table',
  'sh mac-addre': 'show mac address-table',
  'sh mac-addres': 'show mac address-table',
  'sh mac address': 'show mac address-table',
  'sh mac addres': 'show mac address-table',

  'sh cdp': 'show cdp neighbors',
  'sh cdp n': 'show cdp neighbors',
  'sh cdp ne': 'show cdp neighbors',
  'sh cdp nei': 'show cdp neighbors',
  'sh cdp neig': 'show cdp neighbors',
  'sh cdp neigh': 'show cdp neighbors',
  'sh cdp neighb': 'show cdp neighbors',
  'sh cdp neighbo': 'show cdp neighbors',
  'sh cdp neighbor': 'show cdp neighbors',

  'sh cdp ne de': 'show cdp neighbors detail',
  'sh cdp nei d': 'show cdp neighbors detail',
  'sh cdp det': 'show cdp neighbors detail',
  'sh cdp deta': 'show cdp neighbors detail',

  'sh lldp': 'show lldp neighbors',
  'sh lldp n': 'show lldp neighbors',
  'sh lldp ne': 'show lldp neighbors',
  'sh lldp nei': 'show lldp neighbors',
  'sh lldp neig': 'show lldp neighbors',
  'sh lldp neigh': 'show lldp neighbors',
  'sh lldp neighb': 'show lldp neighbors',
  'sh lldp neighbo': 'show lldp neighbors',
  'sh lldp neighbor': 'show lldp neighbors',

  'sh lldp ne de': 'show lldp neighbors detail',
  'sh lldp nei d': 'show lldp neighbors detail',
  'sh lldp det': 'show lldp neighbors detail',
  'sh lldp deta': 'show lldp neighbors detail',

  'sh ip int br': 'show ip interface brief',
  'sh ip int brie': 'show ip interface brief',
  'sh ip int brief': 'show ip interface brief',
  'sh ip ro': 'show ip route',
  'sh ip rou': 'show ip route',
  'sh ip rout': 'show ip route',
  'sh ip route': 'show ip route',
  'sh ip interface br': 'show ip interface brief',
  'sh ip interface brief': 'show ip interface brief',
  'show ip interfaces br': 'show ip interface brief',
  'show ip interfaces brief': 'show ip interface brief',
  'sh ip int': 'show ip interface brief',
  'show interface trunk': 'show interfaces trunk',
  'show cdp neighbor': 'show cdp neighbors',
  'show lldp neighbor': 'show lldp neighbors',
  'show mac address': 'show mac address-table',

  'sh int sta': 'show interfaces status',
  'sh int stat': 'show interfaces status',
  'sh int statu': 'show interfaces status',
  'sh inte sta': 'show interfaces status',
  'sh inter sta': 'show interfaces status',
  'sh interf sta': 'show interfaces status',

  // EtherChannel aliases
  'sh eth': 'show etherchannel',
  'sh ether': 'show etherchannel',
  'sh etherc': 'show etherchannel',
  'sh etherch': 'show etherchannel',
  'sh ethercha': 'show etherchannel',
  'sh etherchan': 'show etherchannel',
  'sh etherchann': 'show etherchannel',
  'sh etherchannel': 'show etherchannel',

  'sh eth sum': 'show etherchannel summary',
  'sh ether sum': 'show etherchannel summary',
  'sh etherch sum': 'show etherchannel summary',
  'sh ethercha sum': 'show etherchannel summary',
  'sh etherchan sum': 'show etherchannel summary',
  'sh etherchann sum': 'show etherchannel summary',
  'sh etherchannel sum': 'show etherchannel summary',

  'sh eth det': 'show etherchannel detail',
  'sh ether det': 'show etherchannel detail',
  'sh etherch det': 'show etherchannel detail',
  'sh ethercha det': 'show etherchannel detail',
  'sh etherchan det': 'show etherchannel detail',
  'sh etherchann det': 'show etherchannel detail',
  'sh etherchannel det': 'show etherchannel detail',

  'sh eth por': 'show etherchannel port',
  'sh ether por': 'show etherchannel port',
  'sh etherch por': 'show etherchannel port',
  'sh ethercha por': 'show etherchannel port',
  'sh etherchan por': 'show etherchannel port',
  'sh etherchann por': 'show etherchannel port',
  'sh etherchannel por': 'show etherchannel port',

  'sh eth load': 'show etherchannel load-balance',
  'sh ether load': 'show etherchannel load-balance',
  'sh etherch load': 'show etherchannel load-balance',
  'sh ethercha load': 'show etherchannel load-balance',
  'sh etherchan load': 'show etherchannel load-balance',
  'sh etherchann load': 'show etherchannel load-balance',
  'sh etherchannel load': 'show etherchannel load-balance',

  'sh spanning-tree': 'show spanning-tree',
  'sh span': 'show spanning-tree',
  'sh spann': 'show spanning-tree',
  'sh spanni': 'show spanning-tree',
  'sh spannin': 'show spanning-tree',
  'sh spanning': 'show spanning-tree',
  'sh spanning-t': 'show spanning-tree',
  'sh spanning-tr': 'show spanning-tree',
  'sh spanning-tre': 'show spanning-tree',
  'sh sp': 'show spanning-tree',

  'sh port-security': 'show port-security',
  'sh port': 'show port-security',
  'sh port-s': 'show port-security',
  'sh port-se': 'show port-security',
  'sh port-sec': 'show port-security',
  'sh port-secu': 'show port-security',
  'sh port-secur': 'show port-security',
  'sh port-securi': 'show port-security',
  'sh port-securit': 'show port-security',

  'sh run | include': 'show running-config | include',
  'sh run | inc': 'show running-config | include',
  'sh run | i': 'show running-config | include',
  'sh run | section': 'show running-config | section',
  'sh run | sec': 'show running-config | section',
  'sh run | begin': 'show running-config | begin',
  'sh run | beg': 'show running-config | begin',

  // Interface commands
  'int': 'interface',
  'inte': 'interface',
  'inter': 'interface',
  'interf': 'interface',
  'interfa': 'interface',
  'interfac': 'interface',

  // Interface range
  'int r': 'interface range',
  'int ra': 'interface range',
  'int ran': 'interface range',
  'int rang': 'interface range',
  'inter r': 'interface range',
  'inter ra': 'interface range',
  'inter ran': 'interface range',
  'inter rang': 'interface range',
  'inter range': 'interface range',
  'interf r': 'interface range',
  'interf ra': 'interface range',
  'interf ran': 'interface range',
  'interf rang': 'interface range',
  'interf range': 'interface range',
  'interface r': 'interface range',
  'interface ra': 'interface range',
  'interface ran': 'interface range',
  'interface rang': 'interface range',

  // Shutdown commands
  'no sh': 'no shutdown',
  'no shu': 'no shutdown',
  'no shut': 'no shutdown',
  'no shutd': 'no shutdown',
  'no shutdo': 'no shutdown',
  'no shutdow': 'no shutdown',
  'shut': 'shutdown',
  'shutd': 'shutdown',
  'shutdo': 'shutdown',
  'shutdow': 'shutdown',

  // Switchport commands
  'sw': 'switchport',
  'swi': 'switchport',
  'swit': 'switchport',
  'switc': 'switchport',
  'switch': 'switchport',
  'switchp': 'switchport',
  'switchpo': 'switchport',
  'switchpor': 'switchport',

  'sw m': 'switchport mode',
  'sw mo': 'switchport mode',
  'sw mod': 'switchport mode',
  'swi m': 'switchport mode',
  'swi mo': 'switchport mode',
  'swi mod': 'switchport mode',
  'swit m': 'switchport mode',
  'swit mo': 'switchport mode',
  'swit mod': 'switchport mode',
  'switch m': 'switchport mode',
  'switch mo': 'switchport mode',
  'switch mod': 'switchport mode',
  'switchp m': 'switchport mode',
  'switchp mo': 'switchport mode',
  'switchp mod': 'switchport mode',
  'switchpo m': 'switchport mode',
  'switchpo mo': 'switchport mode',
  'switchpo mod': 'switchport mode',
  'switchpor m': 'switchport mode',
  'switchpor mo': 'switchport mode',
  'switchpor mod': 'switchport mode',
  'switchport m': 'switchport mode',
  'switchport mo': 'switchport mode',

  'sw m a': 'switchport mode access',
  'sw mo a': 'switchport mode access',
  'sw mod a': 'switchport mode access',
  'sw m ac': 'switchport mode access',
  'sw mo ac': 'switchport mode access',
  'sw mod ac': 'switchport mode access',
  'sw m acc': 'switchport mode access',
  'sw mo acc': 'switchport mode access',
  'sw mod acc': 'switchport mode access',
  'sw m acce': 'switchport mode access',
  'sw mo acce': 'switchport mode access',
  'sw mod acce': 'switchport mode access',
  'sw m acces': 'switchport mode access',
  'sw mo acces': 'switchport mode access',
  'sw mod acces': 'switchport mode access',

  'sw m t': 'switchport mode trunk',
  'sw mo t': 'switchport mode trunk',
  'sw mod t': 'switchport mode trunk',
  'sw m tr': 'switchport mode trunk',
  'sw mo tr': 'switchport mode trunk',
  'sw mod tr': 'switchport mode trunk',
  'sw m tru': 'switchport mode trunk',
  'sw mo tru': 'switchport mode trunk',
  'sw mod tru': 'switchport mode trunk',
  'sw m trun': 'switchport mode trunk',
  'sw mo trun': 'switchport mode trunk',
  'sw mod trun': 'switchport mode trunk',

  'sw a': 'switchport access',
  'sw ac': 'switchport access',
  'sw acc': 'switchport access',
  'sw acce': 'switchport access',
  'sw acces': 'switchport access',
  'swi a': 'switchport access',
  'swi ac': 'switchport access',
  'swi acc': 'switchport access',
  'swi acce': 'switchport access',
  'swi acces': 'switchport access',

  'sw a v': 'switchport access vlan',
  'sw ac v': 'switchport access vlan',
  'sw acc v': 'switchport access vlan',
  'sw acce v': 'switchport access vlan',
  'sw acces v': 'switchport access vlan',
  'sw a vl': 'switchport access vlan',
  'sw ac vl': 'switchport access vlan',
  'sw acc vl': 'switchport access vlan',
  'sw acce vl': 'switchport access vlan',
  'sw acces vl': 'switchport access vlan',
  'sw a vla': 'switchport access vlan',
  'sw ac vla': 'switchport access vlan',
  'sw acc vla': 'switchport access vlan',
  'sw acce vla': 'switchport access vlan',
  'sw acces vla': 'switchport access vlan',
  'sw acc vlan': 'switchport access vlan',
  'sw acce vlan': 'switchport access vlan',
  'sw acces vlan': 'switchport access vlan',

  'sw t': 'switchport trunk',
  'sw tr': 'switchport trunk',
  'sw tru': 'switchport trunk',
  'sw trun': 'switchport trunk',
  'sw t a': 'switchport trunk allowed',
  'sw tr a': 'switchport trunk allowed',
  'sw tru a': 'switchport trunk allowed',
  'sw trun a': 'switchport trunk allowed',
  'sw t al': 'switchport trunk allowed',
  'sw tr al': 'switchport trunk allowed',
  'sw tru al': 'switchport trunk allowed',
  'sw trun al': 'switchport trunk allowed',
  'sw t all': 'switchport trunk allowed',
  'sw tr all': 'switchport trunk allowed',
  'sw tru all': 'switchport trunk allowed',
  'sw trun all': 'switchport trunk allowed',
  'sw t allo': 'switchport trunk allowed',
  'sw tr allo': 'switchport trunk allowed',
  'sw tru allo': 'switchport trunk allowed',
  'sw trun allo': 'switchport trunk allowed',
  'sw t allow': 'switchport trunk allowed',
  'sw tr allow': 'switchport trunk allowed',
  'sw tru allow': 'switchport trunk allowed',
  'sw trun allow': 'switchport trunk allowed',
  'sw t allowe': 'switchport trunk allowed',
  'sw tr allowe': 'switchport trunk allowed',
  'sw tru allowe': 'switchport trunk allowed',
  'sw trun allowe': 'switchport trunk allowed',
  'sw t allowed': 'switchport trunk allowed',
  'sw tr allowed': 'switchport trunk allowed',
  'sw tru allowed': 'switchport trunk allowed',
  'sw trun allowed': 'switchport trunk allowed',
  'sw t a v': 'switchport trunk allowed vlan',
  'sw tr a v': 'switchport trunk allowed vlan',
  'sw tru a v': 'switchport trunk allowed vlan',
  'sw trun a v': 'switchport trunk allowed vlan',
  'sw t al v': 'switchport trunk allowed vlan',
  'sw tr al v': 'switchport trunk allowed vlan',
  'sw tru al v': 'switchport trunk allowed vlan',
  'sw trun al v': 'switchport trunk allowed vlan',
  'show trunk all vlan': 'switchport trunk allowed vlan',

  // Speed and Duplex
  'spe': 'speed',
  'spee': 'speed',
  'dup': 'duplex',
  'dupl': 'duplex',
  'duple': 'duplex',

  // Reload
  'rel': 'reload',
  'relo': 'reload',
  'reloa': 'reload',

  // Ping
  'pi': 'ping',
  'pin': 'ping',

  // Traceroute
  'trac': 'traceroute',
  'trace': 'traceroute',
  'tracer': 'traceroute',
  'tracero': 'traceroute',
  'tracerou': 'traceroute',
  'tracerout': 'traceroute',

  // Telnet
  'tel': 'telnet',
  'teln': 'telnet',
  'telne': 'telnet',

  // SSH
  'ss': 'ssh',
  'ssh': 'ssh',

  // Crypto key generate
  'cry': 'crypto',
  'cryp': 'crypto',
  'crypt': 'crypto',
  'crypto': 'crypto',
  'cry k': 'crypto key',
  'cryp k': 'crypto key',
  'crypt k': 'crypto key',
  'crypto k': 'crypto key',
  'cry ke': 'crypto key',
  'cryp ke': 'crypto key',
  'crypt ke': 'crypto key',
  'crypto ke': 'crypto key',
  'crypto key': 'crypto key',
  'crypto key g': 'crypto key generate',
  'crypto key ge': 'crypto key generate',
  'crypto key gen': 'crypto key generate',
  'crypto key gene': 'crypto key generate',
  'crypto key gener': 'crypto key generate',
  'crypto key genera': 'crypto key generate',
  'crypto key generat': 'crypto key generate',
  'crypto key generate': 'crypto key generate',
  'crypto key generate r': 'crypto key generate rsa',
  'crypto key generate rs': 'crypto key generate rsa',
  'crypto key generate rsa': 'crypto key generate rsa',

  // Crypto key zeroize
  'crypto key z': 'crypto key zeroize',
  'crypto key ze': 'crypto key zeroize',
  'crypto key zer': 'crypto key zeroize',
  'crypto key zero': 'crypto key zeroize',
  'crypto key zeroi': 'crypto key zeroize',
  'crypto key zeroiz': 'crypto key zeroize',
  'crypto key zeroize': 'crypto key zeroize',
  'crypto key zeroize r': 'crypto key zeroize rsa',
  'crypto key zeroize rs': 'crypto key zeroize rsa',
  'crypto key zeroize rsa': 'crypto key zeroize rsa',

  // Ip domain-name
  'ip dn': 'ip domain-name',
  'ip dom': 'ip domain-name',
  'ip doma': 'ip domain-name',
  'ip domai': 'ip domain-name',
  'ip domain': 'ip domain-name',
  'ip domain-': 'ip domain-name',
  'ip domain-n': 'ip domain-name',
  'ip domain-na': 'ip domain-name',
  'ip domain-nam': 'ip domain-name',

  // Ip ssh version
  'ip ssh': 'ip ssh',
  'ip ssh v': 'ip ssh version',
  'ip ssh ve': 'ip ssh version',
  'ip ssh ver': 'ip ssh version',
  'ip ssh vers': 'ip ssh version',
  'ip ssh versi': 'ip ssh version',
  'ip ssh versio': 'ip ssh version',

  // Mac address-table static
  'mac a': 'mac address-table static',
  'mac ad': 'mac address-table static',
  'mac add': 'mac address-table static',
  'mac addr': 'mac address-table static',
  'mac addre': 'mac address-table static',
  'mac addres': 'mac address-table static',
  'mac address': 'mac address-table static',
  'mac address-': 'mac address-table static',
  'mac address-t': 'mac address-table static',
  'mac address-ta': 'mac address-table static',
  'mac address-tab': 'mac address-table static',
  'mac address-tabl': 'mac address-table static',
  'mac address-table': 'mac address-table static',
  'mac address-table s': 'mac address-table static',
  'mac address-table st': 'mac address-table static',
  'mac address-table sta': 'mac address-table static',
  'mac address-table stat': 'mac address-table static',
  'mac address-table stati': 'mac address-table static',

  // Alias command
  'ali': 'alias',
  'alia': 'alias',
  'alias': 'alias',

  // Default interface
  'def': 'default',
  'defa': 'default',
  'defau': 'default',
  'defaul': 'default',
  'default i': 'default interface',
  'default in': 'default interface',
  'default int': 'default interface',
  'default inte': 'default interface',
  'default inter': 'default interface',
  'default interf': 'default interface',
  'default interfa': 'default interface',
  'default interfac': 'default interface',

  // More commands
  'mo': 'more',
  'mor': 'more',

  // Debug
  'deb': 'debug',
  'debu': 'debug',
  'debug': 'debug',
  'no deb': 'no debug',
  'no debu': 'no debug',
  'no debug': 'no debug',
  'undeb': 'undebug',
  'undebu': 'undebug',
  'undebug': 'undebug',

  // Show debug
  'sh deb': 'show debug',
  'sh debu': 'show debug',
  'sh debug': 'show debug',

  // Show processes
  'sh pro': 'show processes',
  'sh proc': 'show processes',
  'sh proce': 'show processes',
  'sh proces': 'show processes',
  'sh process': 'show processes',
  'sh processes': 'show processes',

  // Show memory
  'sh mem': 'show memory',
  'sh memo': 'show memory',
  'sh memor': 'show memory',

  // Show clock
  'sh cl': 'show clock',
  'sh clo': 'show clock',
  'sh cloc': 'show clock',

  // Show flash
  'sh fl': 'show flash',
  'sh fla': 'show flash',
  'sh flas': 'show flash',

  // Show boot
  'sh bo': 'show boot',
  'sh boo': 'show boot',

  // Show environment
  'sh env': 'show environment',
  'sh envi': 'show environment',
  'sh envir': 'show environment',
  'sh enviro': 'show environment',
  'sh environ': 'show environment',
  'sh environm': 'show environment',
  'sh environme': 'show environment',
  'sh environmen': 'show environment',

  // Show inventory
  'sh inv': 'show inventory',
  'sh inve': 'show inventory',
  'sh inven': 'show inventory',
  'sh invent': 'show inventory',
  'sh invento': 'show inventory',
  'sh inventor': 'show inventory',

  // Show users
  'sh u': 'show users',
  'sh us': 'show users',
  'sh use': 'show users',
  'sh user': 'show users',

  // Show sessions
  'sh ses': 'show sessions',
  'sh sess': 'show sessions',
  'sh sessi': 'show sessions',
  'sh sessio': 'show sessions',
  'sh session': 'show sessions',

  // Disconnect
  'discon': 'disconnect',
  'disconn': 'disconnect',
  'discconne': 'disconnect',
  'disconnect': 'disconnect',

  // Clear commands
  'cle': 'clear',
  'clea': 'clear',
  'cle ar': 'clear arp-cache',
  'clea ar': 'clear arp-cache',
  'clear ar': 'clear arp-cache',
  'clear arp': 'clear arp-cache',
  'clear arp-': 'clear arp-cache',
  'clear arp-c': 'clear arp-cache',
  'clear arp-ca': 'clear arp-cache',
  'clear arp-cac': 'clear arp-cache',
  'clear arp-cache': 'clear arp-cache',

  'cle cou': 'clear counters',
  'clea cou': 'clear counters',
  'clear cou': 'clear counters',
  'clear coun': 'clear counters',
  'clear count': 'clear counters',
  'clear counte': 'clear counters',
  'clear counter': 'clear counters',

  'cle mac': 'clear mac address-table',
  'clea mac': 'clear mac address-table',
  'clear mac': 'clear mac address-table',
  'clear mac-': 'clear mac address-table',
  'clear mac-a': 'clear mac address-table',
  'clear mac-ad': 'clear mac address-table',
  'clear mac-addr': 'clear mac address-table',
  'clear mac-addre': 'clear mac address-table',
  'clear mac-addres': 'clear mac address-table',
  'clear mac-address': 'clear mac address-table',
  'clear mac-address-': 'clear mac address-table',
  'clear mac-address-t': 'clear mac address-table',
  'clear mac-address-ta': 'clear mac address-table',
  'clear mac-address-tab': 'clear mac address-table',
  'clear mac-address-tabl': 'clear mac address-table',
  'clear mac-address-table': 'clear mac address-table',

  // Archive
  'arc': 'archive',
  'arch': 'archive',
  'archi': 'archive',
  'archiv': 'archive',

  // Configure replace
  'conf r': 'configure replace',
  'conf re': 'configure replace',
  'conf rep': 'configure replace',
  'conf repl': 'configure replace',
  'conf repla': 'configure replace',
  'conf replac': 'configure replace',
  'configure r': 'configure replace',
  'configure re': 'configure replace',
  'configure rep': 'configure replace',
  'configure repl': 'configure replace',
  'configure repla': 'configure replace',
  'configure replac': 'configure replace',

  // Template
  'tem': 'template',
  'temp': 'template',
  'templ': 'template',
  'templa': 'template',
  'templat': 'template',

  // Policy-map
  'pol': 'policy-map',
  'poli': 'policy-map',
  'polic': 'policy-map',
  'policy': 'policy-map',
  'policy-': 'policy-map',
  'policy-m': 'policy-map',
  'policy-ma': 'policy-map',

  // Class-map
  'cla': 'class-map',
  'clas': 'class-map',
  'class-': 'class-map',
  'class-m': 'class-map',
  'class-ma': 'class-map',

  // Access-list
  'ac': 'access-list',
  'acc': 'access-list',
  'acce': 'access-list',
  'acces': 'access-list',
  'access': 'access-list',
  'access-': 'access-list',
  'access-l': 'access-list',
  'access-li': 'access-list',
  'access-lis': 'access-list',

  // Mac access-list
  'mac acc': 'mac access-list',
  'mac acce': 'mac access-list',
  'mac acces': 'mac access-list',
  'mac access': 'mac access-list',
  'mac access-': 'mac access-list',
  'mac access-l': 'mac access-list',
  'mac access-li': 'mac access-list',
  'mac access-lis': 'mac access-list',

  // Arp inspection
  'ip arp i': 'ip arp inspection',
  'ip arp in': 'ip arp inspection',
  'ip arp ins': 'ip arp inspection',
  'ip arp insp': 'ip arp inspection',
  'ip arp inspe': 'ip arp inspection',
  'ip arp inspec': 'ip arp inspection',
  'ip arp inspect': 'ip arp inspection',
  'ip arp inspecti': 'ip arp inspection',
  'ip arp inspectio': 'ip arp inspection',

  // IP verify source
  'ip ve': 'ip verify',
  'ip ver': 'ip verify',
  'ip veri': 'ip verify',
  'ip verif': 'ip verify',
  'ip verify': 'ip verify',
  'ip verify s': 'ip verify source',
  'ip verify so': 'ip verify source',
  'ip verify sou': 'ip verify source',
  'ip verify sour': 'ip verify source',
  'ip verify sourc': 'ip verify source',
  'ip verify source': 'ip verify source',

  // Show ip source binding
  'sh ip s': 'show ip source',
  'sh ip so': 'show ip source',
  'sh ip sou': 'show ip source',
  'sh ip sour': 'show ip source',
  'sh ip sourc': 'show ip source',
  'sh ip source': 'show ip source',
  'sh ip source b': 'show ip source binding',
  'sh ip source bi': 'show ip source binding',
  'sh ip source bin': 'show ip source binding',
  'sh ip source bind': 'show ip source binding',
  'sh ip source bindi': 'show ip source binding',
  'sh ip source bindin': 'show ip source binding',
  'sh ip source binding': 'show ip source binding',

  // Show ip verify source
  'sh ip v': 'show ip verify',
  'sh ip ve': 'show ip verify',
  'sh ip ver': 'show ip verify',
  'sh ip veri': 'show ip verify',
  'sh ip verif': 'show ip verify',
  'sh ip verify': 'show ip verify',
  'sh ip verify s': 'show ip verify source',
  'sh ip verify so': 'show ip verify source',
  'sh ip verify sou': 'show ip verify source',
  'sh ip verify sour': 'show ip verify source',
  'sh ip verify sourc': 'show ip verify source',
  'sh ip verify source': 'show ip verify source',

  // DHCP snooping
  'ip dhcp s': 'ip dhcp snooping',
  'ip dhcp sn': 'ip dhcp snooping',
  'ip dhcp sno': 'ip dhcp snooping',
  'ip dhcp snoo': 'ip dhcp snooping',
  'ip dhcp snoop': 'ip dhcp snooping',
  'ip dhcp snoopi': 'ip dhcp snooping',
  // DHCP helper-address
  'ip helper': 'ip helper-address',
  'ip helper-add': 'ip helper-address',
  'ip helper-addr': 'ip helper-address',
  'no ip helper': 'no ip helper-address',
  'no ip helper-add': 'no ip helper-address',
  'no ip helper-addr': 'no ip helper-address',

  // Storm control
  'sto': 'storm-control',
  'stor': 'storm-control',
  'storm': 'storm-control',
  'storm-': 'storm-control',
  'storm-c': 'storm-control',
  'storm-co': 'storm-control',
  'storm-con': 'storm-control',
  'storm-cont': 'storm-control',
  'storm-contr': 'storm-control',
  'storm-contro': 'storm-control',

  // UDLD
  'ud': 'udld',
  'udl': 'udld',
  'udld': 'udld',
  'udld e': 'udld enable',
  'udld en': 'udld enable',
  'udld ena': 'udld enable',
  'udld enab': 'udld enable',
  'udld enabl': 'udld enable',
  'udld enable': 'udld enable',

  // LACP
  'lacp': 'lacp',
  'lacp p': 'lacp port-priority',
  'lacp po': 'lacp port-priority',
  'lacp por': 'lacp port-priority',
  'lacp port': 'lacp port-priority',
  'lacp port-': 'lacp port-priority',
  'lacp port-p': 'lacp port-priority',
  'lacp port-pr': 'lacp port-priority',
  'lacp port-pri': 'lacp port-priority',
  'lacp port-prio': 'lacp port-priority',
  'lacp port-prior': 'lacp port-priority',
  'lacp port-priori': 'lacp port-priority',
  'lacp port-priorit': 'lacp port-priority',

  // PAgP
  'pagp': 'pagp',

  // Monitor (SPAN)
  'mon': 'monitor',
  'moni': 'monitor',
  'monit': 'monitor',
  'monito': 'monitor',
  'monitor s': 'monitor session',
  'monitor se': 'monitor session',
  'monitor ses': 'monitor session',
  'monitor sess': 'monitor session',
  'monitor sessi': 'monitor session',
  'monitor sessio': 'monitor session',

  // VTP
  'vtp': 'vtp',
  'vtp m': 'vtp mode',
  'vtp mo': 'vtp mode',
  'vtp mod': 'vtp mode',
  'vtp mode': 'vtp mode',
  'vtp mode s': 'vtp mode server',
  'vtp mode se': 'vtp mode server',
  'vtp mode ser': 'vtp mode server',
  'vtp mode serv': 'vtp mode server',
  'vtp mode serve': 'vtp mode server',
  'vtp mode c': 'vtp mode client',
  'vtp mode cl': 'vtp mode client',
  'vtp mode cli': 'vtp mode client',
  'vtp mode clien': 'vtp mode client',
  'vtp mode t': 'vtp mode transparent',
  'vtp mode tr': 'vtp mode transparent',
  'vtp mode tra': 'vtp mode transparent',
  'vtp mode tran': 'vtp mode transparent',
  'vtp mode trans': 'vtp mode transparent',
  'vtp mode transp': 'vtp mode transparent',
  'vtp mode transpa': 'vtp mode transparent',
  'vtp mode transpar': 'vtp mode transparent',
  'vtp mode transpare': 'vtp mode transparent',
  'vtp mode transparen': 'vtp mode transparent',
  'vtp d': 'vtp domain',
  'vtp do': 'vtp domain',
  'vtp dom': 'vtp domain',
  'vtp doma': 'vtp domain',
  'vtp domai': 'vtp domain',

  // Snmp
  'snmp': 'snmp-server',
  'snmp-': 'snmp-server',
  'snmp-s': 'snmp-server',
  'snmp-se': 'snmp-server',
  'snmp-ser': 'snmp-server',
  'snmp-serv': 'snmp-server',
  'snmp-serve': 'snmp-server',

  // Ntp
  'ntp': 'ntp',
  'ntp s': 'ntp server',
  'ntp se': 'ntp server',
  'ntp ser': 'ntp server',
  'ntp serv': 'ntp server',
  'ntp serve': 'ntp server',

  // Clock
  'clo': 'clock',
  'cloc': 'clock',
  'clock t': 'clock timezone',
  'clock ti': 'clock timezone',
  'clock tim': 'clock timezone',
  'clock time': 'clock timezone',
  'clock timez': 'clock timezone',
  'clock timezo': 'clock timezone',
  'clock timezon': 'clock timezone',

  // System MTU
  'sys': 'system',
  'syst': 'system',
  'syste': 'system',
  'system m': 'system mtu',
  'system mt': 'system mtu',
  'system mtu': 'system mtu',

  // SDM prefer
  'sdm': 'sdm',
  'sdm p': 'sdm prefer',
  'sdm pr': 'sdm prefer',
  'sdm pre': 'sdm prefer',
  'sdm pref': 'sdm prefer',
  'sdm prefe': 'sdm prefer',

  // Power inline (PoE)
  'pow': 'power',
  'powe': 'power',
  'power i': 'power inline',
  'power in': 'power inline',
  'power inl': 'power inline',
  'power inli': 'power inline',
  'power inlin': 'power inline',
  'power inline': 'power inline',
  'power inline n': 'power inline never',
  'power inline ne': 'power inline never',
  'power inline nev': 'power inline never',
  'power inline neve': 'power inline never',
  'power inline s': 'power inline static',
  'power inline st': 'power inline static',
  'power inline sta': 'power inline static',
  'power inline stat': 'power inline static',

  // Voice VLAN
  'sw v': 'switchport voice',
  'sw vo': 'switchport voice',
  'sw voi': 'switchport voice',
  'sw voic': 'switchport voice',
  'switchport v': 'switchport voice',
  'switchport vo': 'switchport voice',
  'switchport voi': 'switchport voice',
  'switchport voic': 'switchport voice',
  'switchport voice': 'switchport voice',
  'switchport voice v': 'switchport voice vlan',
  'switchport voice vl': 'switchport voice vlan',
  'switchport voice vla': 'switchport voice vlan',

  // MLs QoS
  'mls': 'mls',
  'mls q': 'mls qos',
  'mls qo': 'mls qos',
  'mls qos': 'mls qos',
  'mls qos t': 'mls qos trust',
  'mls qos tr': 'mls qos trust',
  'mls qos tru': 'mls qos trust',
  'mls qos trust': 'mls qos trust',
  'mls qos trust c': 'mls qos trust cos',
  'mls qos trust co': 'mls qos trust cos',
  'mls qos trust d': 'mls qos trust dscp',
  'mls qos trust ds': 'mls qos trust dscp',
  'mls qos trust dsc': 'mls qos trust dscp',

  // Priority-queue
  'pri': 'priority-queue',
  'prio': 'priority-queue',
  'prior': 'priority-queue',
  'priori': 'priority-queue',
  'priorit': 'priority-queue',
  'priority': 'priority-queue',
  'priority-': 'priority-queue',
  'priority-q': 'priority-queue',
  'priority-qu': 'priority-queue',
  'priority-que': 'priority-queue',
  'priority-queu': 'priority-queue',
  'priority-queue': 'priority-queue',
  'priority-queue o': 'priority-queue out',
  'priority-queue ou': 'priority-queue out',
  'priority-queue out': 'priority-queue out',

  // Queue-set
  'que': 'queue-set',
  'queu': 'queue-set',
  'queue': 'queue-set',
  'queue-': 'queue-set',
  'queue-s': 'queue-set',
  'queue-se': 'queue-set',
  'queue-set': 'queue-set',

  // Test
  'tes': 'test',
  'test': 'test',

  // Setup
  'setu': 'setup',
  'setup': 'setup',

  'sh ipv6 nei': 'show ipv6 neighbors',
  'sh ipv6 neig': 'show ipv6 neighbors',
  'sh ipv6 neigh': 'show ipv6 neighbors',
  'show ipv6 ne': 'show ipv6 neighbors',
  'show ipv6 nei': 'show ipv6 neighbors',
  'show ipv6 neig': 'show ipv6 neighbors',
  'show ipv6 neigh': 'show ipv6 neighbors',
  'show ipv6 neighbor': 'show ipv6 neighbors',
  'show ipv6 neighbors': 'show ipv6 neighbors',

  'clear ipv6 ne': 'clear ipv6 neighbors',
  'clear ipv6 nei': 'clear ipv6 neighbors',
  'clear ipv6 neig': 'clear ipv6 neighbors',
  'clear ipv6 neigh': 'clear ipv6 neighbors',
  'clear ipv6 neighbor': 'clear ipv6 neighbors',
  'clear ipv6 neighbors': 'clear ipv6 neighbors'
};
