import { describe, it, expect } from 'vitest';
import { commandPatterns } from './parser';
import { executeCommand } from './executor';
import { createInitialState } from './initialState';

describe('Command Handlers Validation', () => {
  const state = createInitialState();
  const ctx = {
    language: 'en' as const,
    deviceStates: new Map(),
    devices: [],
    connections: []
  };

  it('should have a handler for every pattern', () => {
    const patterns = Object.keys(commandPatterns);

    // Commands that require specific input to not fail validation immediately
    const mockInputs: Record<string, string> = {
      'hostname': 'hostname Switch1',
      'vlan': 'vlan 10',
      'no vlan': 'no vlan 10',
      'enable password': 'enable password cisco',
      'enable secret': 'enable secret cisco',
      'username': 'username admin password cisco',
      'no username': 'no username admin',
      'banner motd': 'banner motd #welcome#',
      'banner login': 'banner login #login#',
      'banner exec': 'banner exec #exec#',
      'ip domain-name': 'ip domain-name example.com',
      'ip name-server': 'ip name-server 8.8.8.8',
      'ip default-gateway': 'ip default-gateway 192.168.1.1',
      'ip route': 'ip route 10.0.0.0 255.255.255.0 192.168.1.1',
      'no ip route': 'no ip route 10.0.0.0 255.255.255.0',
      'ip ssh version': 'ip ssh version 2',
      'ip ssh authentication-retries': 'ip ssh authentication-retries 3',
      'ip ssh time-out': 'ip ssh time-out 60',
      'router ospf': 'router ospf 1',
      'network': 'network 192.168.1.0 0.0.0.255 area 0',
      'router-id': 'router-id 1.1.1.1',
      'passive-interface': 'passive-interface fa0/1',
      'default-information originate': 'default-information originate',
      'default-information always': 'default-information always',
      'router-config network': 'network 192.168.1.0 0.0.0.255 area 0',
      'cdp timer': 'cdp timer 60',
      'cdp holdtime': 'cdp holdtime 180',
      'vtp mode': 'vtp mode server',
      'vtp domain': 'vtp domain CISCO',
      'vtp password': 'vtp password cisco',
      'spanning-tree mode': 'spanning-tree mode pvst',
      'spanning-tree vlan': 'spanning-tree vlan 1 priority 4096',
      'spanning-tree portfast': 'spanning-tree portfast',
      'spanning-tree bpduguard': 'spanning-tree bpduguard enable',
      'spanning-tree cost': 'spanning-tree cost 19',
      'spanning-tree priority': 'spanning-tree priority 128',
      'no spanning-tree': 'no spanning-tree vlan 1',
      'errdisable recovery': 'errdisable recovery cause bpduguard',
      'errdisable recovery cause': 'errdisable recovery cause bpduguard',
      'ip dhcp snooping vlan': 'ip dhcp snooping vlan 1',
      'ip arp inspection': 'ip arp inspection vlan 1',
      'system mtu': 'system mtu 1500',
      'sdm prefer': 'sdm prefer default',
      'snmp-server community': 'snmp-server community public RO',
      'snmp-server contact': 'snmp-server contact admin',
      'snmp-server location': 'snmp-server location rack1',
      'ntp server': 'ntp server 1.1.1.1',
      'clock timezone': 'clock timezone UTC 0',
      'alias': 'alias exec h show history',
      'macro': 'macro name test',
      'interface': 'interface fa0/1',
      'interface range': 'interface range fa0/1-5',
      'default interface': 'default interface fa0/1',
      'no interface': 'no interface vlan 10',
      'ipv6 address': 'ipv6 address 2001:db8::1/64',
      'speed': 'speed 100',
      'duplex': 'duplex full',
      'description': 'description LAN',
      'switchport mode': 'switchport mode access',
      'switchport access vlan': 'switchport access vlan 10',
      'switchport trunk allowed vlan': 'switchport trunk allowed vlan 10,20',
      'switchport trunk native vlan': 'switchport trunk native vlan 10',
      'switchport trunk encapsulation': 'switchport trunk encapsulation dot1q',
      'encapsulation dot1q': 'encapsulation dot1q 10',
      'switchport port-security maximum': 'switchport port-security maximum 2',
      'switchport port-security violation': 'switchport port-security violation shutdown',
      'switchport port-security mac-address': 'switchport port-security mac-address sticky',
      'switchport port-security aging time': 'switchport port-security aging time 10',
      'switchport port-security aging type': 'switchport port-security aging type absolute',
      'switchport block': 'switchport block unicast',
      'switchport protected': 'switchport protected',
      'switchport voice vlan': 'switchport voice vlan 100',
      'switchport voice': 'switchport voice vlan 100',
      'channel-group': 'channel-group 1 mode on',
      'no channel-group': 'no channel-group 1',
      'channel-protocol': 'channel-protocol lacp',
      'storm-control': 'storm-control broadcast level 10',
      'storm-control action': 'storm-control action shutdown',
      'mls qos trust': 'mls qos trust cos',
      'mls qos cos': 'mls qos cos 3',
      'queue-set': 'queue-set 1',
      'tx-queue': 'tx-queue 1',
      'power inline': 'power inline auto',
      'power inline consumption': 'power inline consumption 1000',
      'wlan': 'wlan test 1 test',
      'security wpa psk set-key': 'security wpa psk set-key ascii 0 password',
      'channel': 'channel 1',
      'station-role': 'station-role root',
      'ip address': 'ip address 192.168.1.1 255.255.255.0',
      'ip helper-address': 'ip helper-address 1.1.1.1',
      'ip verify source': 'ip verify source',
      'ip arp inspection limit': 'ip arp inspection limit rate 10',
      'keepalive': 'keepalive 10',
      'carrier-delay': 'carrier-delay 10',
      'bandwidth': 'bandwidth 1000',
      'delay': 'delay 10',
      'load-interval': 'load-interval 30',
      'name': 'name VLAN10',
      'state': 'state active',
      'line console': 'line console 0',
      'line vty': 'line vty 0 4',
      'line aux': 'line aux 0',
      'line': 'line vty 0 4',
      'password': 'password cisco',
      'login': 'login',
      'transport input': 'transport input ssh',
      'transport output': 'transport output ssh',
      'transport preferred': 'transport preferred ssh',
      'exec-timeout': 'exec-timeout 10 0',
      'history size': 'history size 100',
      'history': 'history enable',
      'privilege level': 'privilege level 15',
      'access-class': 'access-class 1 in',
      'session-limit': 'session-limit 5',
      'autocommand': 'autocommand show version',
      'do': 'do show version',
      'do show': 'do show running-config',
      'show running-config': 'show running-config',
      'show startup-config': 'show startup-config',
      'show interfaces status': 'show interfaces status',
      'show interface trunk': 'show interface trunk',
      'show interfaces trunk': 'show interfaces trunk',
      'show interfaces': 'show interfaces',
      'show interface': 'show interface fa0/1',
      'show vlan brief': 'show vlan brief',
      'show vlan': 'show vlan',
      'show version': 'show version',
      'show mac address-table': 'show mac address-table',
      'show cdp neighbors': 'show cdp neighbors',
      'show cdp': 'show cdp',
      'show ip interface brief': 'show ip interface brief',
      'show ip interface': 'show ip interface fa0/1',
      'show ip route': 'show ip route',
      'show ipv6 interface brief': 'show ipv6 interface brief',
      'show spanning-tree': 'show spanning-tree',
      'show port-security': 'show port-security',
      'show ssh': 'show ssh',
      'show ip ssh': 'show ip ssh',
      'show etherchannel': 'show etherchannel',
      'show vtp status': 'show vtp status',
      'show errdisable recovery': 'show errdisable recovery',
      'show errdisable detect': 'show errdisable detect',
      'show mac address-table static': 'show mac address-table static',
      'show authentication': 'show authentication',
      'show clock': 'show clock',
      'show flash': 'show flash',
      'show boot': 'show boot',
      'show environment': 'show environment',
      'show inventory': 'show inventory',
      'show users': 'show users',
      'show sessions': 'show sessions',
      'show processes': 'show processes',
      'show memory': 'show memory',
      'show wireless': 'show wireless',
      'show wlan summary': 'show wlan summary',
      'show ap summary': 'show ap summary',
      'show debugging': 'show debugging',
      'show ntp associations': 'show ntp associations',
      'show ntp status': 'show ntp status',
      'show ntp': 'show ntp',
      'show snmp': 'show snmp',
      'show arp': 'show arp',
      'show ip arp': 'show ip arp',
      'show ip dhcp snooping': 'show ip dhcp snooping',
      'show ip source binding': 'show ip source binding',
      'show ip verify source': 'show ip verify source',
      'ip dhcp pool': 'ip dhcp pool test',
      'no ip dhcp pool': 'no ip dhcp pool test',
      'ip dhcp excluded-address': 'ip dhcp excluded-address 192.168.1.1 192.168.1.10',
      'no ip dhcp excluded-address': 'no ip dhcp excluded-address 192.168.1.1',
      'default-router': 'default-router 192.168.1.1',
      'dns-server': 'dns-server 8.8.8.8',
      'lease': 'lease 7',
      'domain-name': 'domain-name test.com',
      'show ip dhcp pool': 'show ip dhcp pool',
      'show ip dhcp binding': 'show ip dhcp binding',
      'show arp inspection': 'show ip arp inspection', // Pattern is 'show ip arp inspection'
      'show ip arp inspection': 'show ip arp inspection',
      'show monitor': 'show monitor',
      'show policy-map': 'show policy-map',
      'show class-map': 'show class-map',
      'show access-lists': 'show access-lists',
      'show mac access-lists': 'show mac access-lists',
      'show system mtu': 'show system mtu',
      'show sdm prefer': 'show sdm prefer',
      'show controllers': 'show controllers',
      'show diagnostic': 'show diagnostic',
      'show udld': 'show udld',
      'show lldp': 'show lldp',
      'show mls qos': 'show mls qos',
      'show storm-control': 'show storm-control',
      'show banner motd': 'show banner motd',
      'show alias': 'show alias',
      'show history': 'show history',
      'show redundancy': 'show redundancy',
      'show archive': 'show archive',
      'write memory': 'write memory',
      'copy running-config startup-config': 'copy running-config startup-config',
      'copy running-config flash': 'copy running-config flash:test',
      'copy running-config tftp': 'copy running-config tftp',
      'copy tftp running-config': 'copy tftp running-config',
      'copy startup-config running-config': 'copy startup-config running-config',
      'copy flash startup-config': 'copy flash:test startup-config',
      'erase startup-config': 'erase startup-config',
      'erase nvram': 'erase nvram',
      'delete nvram': 'delete nvram',
      'delete flash:vlan.dat': 'delete flash:vlan.dat',
      'ping': 'ping 1.1.1.1',
      'traceroute': 'traceroute 1.1.1.1',
      'tracert': 'tracert 1.1.1.1',
      'telnet': 'telnet 1.1.1.1',
      'ssh': 'ssh 1.1.1.1',
      'terminal length': 'terminal length 24',
      'terminal width': 'terminal width 80',
      'terminal monitor': 'terminal monitor',
      'terminal no monitor': 'terminal no monitor',
      'terminal': 'terminal length 24',
      'reload': 'reload',
      'clear arp-cache': 'clear arp-cache',
      'clear mac address-table': 'clear mac address-table',
      'clear counters': 'clear counters',
      'clear line': 'clear line 1',
      'clear interface': 'clear interface fa0/1',
      'debug': 'debug ip packet',
      'no debug': 'no debug all',
      'undebug all': 'undebug all',
      'undebug': 'undebug all',
      'setup': 'setup',
      'test': 'test memory',
      'configure replace': 'configure replace flash:config.text',
      'more': 'more flash:config.text',
      'disconnect': 'disconnect 1',
      'resume': 'resume 1',
      'suspend': 'suspend',
      'access-list': 'access-list standard 1',
      'no access-list': 'no access-list 1',
      'mac access-list': 'mac access-list extended test',
      'monitor session': 'monitor session 1 source fa0/1',
      'no monitor session': 'no monitor session 1',
      'class-map': 'class-map match-all test',
      'policy-map': 'policy-map test',
      'template': 'template test',
    };

    patterns.forEach(pattern => {
      const input = mockInputs[pattern] || pattern;

      // We need to set the state to the correct mode for the pattern
      const p = commandPatterns[pattern];
      const mode = p.modes[0];
      const testState = { ...state, currentMode: mode };

      if (mode === 'interface') {
        testState.currentInterface = 'fa0/1';
      } else if (mode === 'vlan') {
        testState.currentVlan = 10;
        testState.vlans = { 10: { id: 10, name: 'VLAN10', status: 'active', ports: [] } };
      } else if (mode === 'router-config') {
        testState.routingProtocol = 'ospf';
      } else if (mode === 'line') {
        testState.currentLine = 'vty 0 4';
      } else if (mode === 'dhcp-config') {
        testState.currentDhcpPool = 'test';
        testState.dhcpPools = { 'test': {} };
      }

      const result = executeCommand(testState, input, 'en', [], [], new Map(), 'source');

      try {
        expect(result, `Pattern "${pattern}" with input "${input}" failed to return a result`).toBeDefined();
        expect(result.success || result.error, `Pattern "${pattern}" failed with unrecognized error: ${result.error}`).toBeDefined();
        // If it failed validation, we want to know why
        if (!result.success && result.error?.includes('Unknown command')) {
           throw new Error(`Pattern "${pattern}" matched by parser but handler not found by executor. Input: "${input}"`);
        }
      } catch (e) {
        console.error(`Validation failed for pattern: ${pattern}`);
        throw e;
      }
    });
  });
});
