// Komut kısaltmaları için eşleşme - Temel ve Show Komutları
export const commandAliasesBasic: Record<string, string> = {
  // Enable/Disable
  'en': 'enable',
  'ena': 'enable',
  'enab': 'enable',
  'dis': 'disable',
  'disa': 'disable',

  // Configure
  'conf': 'configure',
  'conf t': 'configure terminal',
  'config t': 'configure terminal',
  'conf te': 'configure terminal',
  'config te': 'configure terminal',
  'conf ter': 'configure terminal',
  'config ter': 'configure terminal',
  'conf term': 'configure terminal',
  'config term': 'configure terminal',
  'conf termi': 'configure terminal',
  'config termi': 'configure terminal',
  'conf termin': 'configure terminal',
  'config termin': 'configure terminal',
  'conf termina': 'configure terminal',
  'config termina': 'configure terminal',
  'configure t': 'configure terminal',
  'configure te': 'configure terminal',
  'configure ter': 'configure terminal',
  'configure term': 'configure terminal',
  'configure termi': 'configure terminal',
  'configure termin': 'configure terminal',
  'configure termina': 'configure terminal',

  // Show commands
  'sh': 'show',
  'sho': 'show',
  'sh r': 'show running-config',
  'sh ru': 'show running-config',
  'sh run': 'show running-config',
  'sh runn': 'show running-config',
  'sh runni': 'show running-config',
  'sh runnin': 'show running-config',
  'sh running': 'show running-config',
  'sh running-c': 'show running-config',
  'sh running-co': 'show running-config',
  'sh running-con': 'show running-config',
  'sh running-conf': 'show running-config',
  'sh runn-c': 'show running-config',
  'sh runn-co': 'show running-config',

  // Show startup-config commands
  'sh st': 'show startup-config',
  'sh sta': 'show startup-config',
  'sh star': 'show startup-config',
  'sh start': 'show startup-config',
  'sh startu': 'show startup-config',
  'sh startup': 'show startup-config',
  'sh startup-': 'show startup-config',
  'sh startup-c': 'show startup-config',
  'sh startup-co': 'show startup-config',
  'sh startup-con': 'show startup-config',
  'sh startup-conf': 'show startup-config',

  'sh i': 'show interfaces',
  'sh in': 'show interfaces',
  'sh int': 'show interfaces',
  'sh inte': 'show interfaces',
  'sh inter': 'show interfaces',
  'sh interf': 'show interfaces',
  'sh interfa': 'show interfaces',
  'sh interfac': 'show interfaces',
  'sh interface': 'show interfaces',
  'sh interfaces': 'show interfaces',

  'sh vl': 'show vlan',
  'sh vla': 'show vlan',
  'sh vlan': 'show vlan brief',
  'sh vlan b': 'show vlan brief',
  'sh vlan br': 'show vlan brief',
  'sh vlan bre': 'show vlan brief',
  'sh vlanbrie': 'show vlan brief',
  'sh vl b': 'show vlan brief',
  'sh vl br': 'show vlan brief',
  'sh vl bre': 'show vlan brief',

  'sh v': 'show version',
  'sh ve': 'show version',
  'sh ver': 'show version',
  'sh vers': 'show version',
  'sh versi': 'show version',
  'sh versio': 'show version',

  'sh m': 'show mac address-table',
  'sh ma': 'show mac address-table',
  'sh mac': 'show mac address-table',
  'sh mac-': 'show mac address-table',
  'sh mac-a': 'show mac address-table',
  'sh mac-ad': 'show mac address-table',
  'sh mac-addr': 'show mac address-table',
  'sh mac-addre': 'show mac address-table',
  'sh mac-addres': 'show mac address-table',
  'sh mac address': 'show mac address-table',
  'sh mac addres': 'show mac address-table',

  'sh cdp': 'show cdp neighbors',
  'sh cdp n': 'show cdp neighbors',
  'sh cdp ne': 'show cdp neighbors',
  'sh cdp nei': 'show cdp neighbors',
  'sh cdp neig': 'show cdp neighbors',
  'sh cdp neigh': 'show cdp neighbors',
  'sh cdp neighb': 'show cdp neighbors',
  'sh cdp neighbo': 'show cdp neighbors',
  'sh cdp neighbor': 'show cdp neighbors',

  'sh cdp ne de': 'show cdp neighbors detail',
  'sh cdp nei d': 'show cdp neighbors detail',
  'sh cdp det': 'show cdp neighbors detail',
  'sh cdp deta': 'show cdp neighbors detail',

  'sh lldp': 'show lldp neighbors',
  'sh lldp n': 'show lldp neighbors',
  'sh lldp ne': 'show lldp neighbors',
  'sh lldp nei': 'show lldp neighbors',
  'sh lldp neig': 'show lldp neighbors',
  'sh lldp neigh': 'show lldp neighbors',
  'sh lldp neighb': 'show lldp neighbors',
  'sh lldp neighbo': 'show lldp neighbors',
  'sh lldp neighbor': 'show lldp neighbors',

  'sh lldp ne de': 'show lldp neighbors detail',
  'sh lldp nei d': 'show lldp neighbors detail',
  'sh lldp det': 'show lldp neighbors detail',
  'sh lldp deta': 'show lldp neighbors detail',

  'sh ip int br': 'show ip interface brief',
  'sh ip int brie': 'show ip interface brief',
  'sh ip int brief': 'show ip interface brief',
  'sh ip ro': 'show ip route',
  'sh ip rou': 'show ip route',
  'sh ip rout': 'show ip route',
  'sh ip route': 'show ip route',
  'sh ip interface br': 'show ip interface brief',
  'sh ip interface brief': 'show ip interface brief',
  'show ip interfaces br': 'show ip interface brief',
  'show ip interfaces brief': 'show ip interface brief',
  'sh ip int': 'show ip interface brief',
  'show interface trunk': 'show interfaces trunk',
  'show cdp neighbor': 'show cdp neighbors',
  'show lldp neighbor': 'show lldp neighbors',
  'show mac address': 'show mac address-table',

  'sh int sta': 'show interfaces status',
  'sh int stat': 'show interfaces status',
  'sh int statu': 'show interfaces status',
  'sh inte sta': 'show interfaces status',
  'sh inter sta': 'show interfaces status',
  'sh interf sta': 'show interfaces status',

  // EtherChannel aliases
  'sh eth': 'show etherchannel',
  'sh ether': 'show etherchannel',
  'sh etherc': 'show etherchannel',
  'sh etherch': 'show etherchannel',
  'sh ethercha': 'show etherchannel',
  'sh etherchan': 'show etherchannel',
  'sh etherchann': 'show etherchannel',
  'sh etherchannel': 'show etherchannel',

  'sh eth sum': 'show etherchannel summary',
  'sh ether sum': 'show etherchannel summary',
  'sh etherch sum': 'show etherchannel summary',
  'sh ethercha sum': 'show etherchannel summary',
  'sh etherchan sum': 'show etherchannel summary',
  'sh etherchann sum': 'show etherchannel summary',
  'sh etherchannel sum': 'show etherchannel summary',

  'sh eth det': 'show etherchannel detail',
  'sh ether det': 'show etherchannel detail',
  'sh etherch det': 'show etherchannel detail',
  'sh ethercha det': 'show etherchannel detail',
  'sh etherchan det': 'show etherchannel detail',
  'sh etherchann det': 'show etherchannel detail',
  'sh etherchannel det': 'show etherchannel detail',

  'sh eth por': 'show etherchannel port',
  'sh ether por': 'show etherchannel port',
  'sh etherch por': 'show etherchannel port',
  'sh ethercha por': 'show etherchannel port',
  'sh etherchan por': 'show etherchannel port',
  'sh etherchann por': 'show etherchannel port',
  'sh etherchannel por': 'show etherchannel port',

  'sh eth load': 'show etherchannel load-balance',
  'sh ether load': 'show etherchannel load-balance',
  'sh etherch load': 'show etherchannel load-balance',
  'sh ethercha load': 'show etherchannel load-balance',
  'sh etherchan load': 'show etherchannel load-balance',
  'sh etherchann load': 'show etherchannel load-balance',
  'sh etherchannel load': 'show etherchannel load-balance',

  'sh spanning-tree': 'show spanning-tree',
  'sh span': 'show spanning-tree',
  'sh spann': 'show spanning-tree',
  'sh spanni': 'show spanning-tree',
  'sh spannin': 'show spanning-tree',
  'sh spanning': 'show spanning-tree',
  'sh spanning-t': 'show spanning-tree',
  'sh spanning-tr': 'show spanning-tree',
  'sh spanning-tre': 'show spanning-tree',
  'sh sp': 'show spanning-tree',

  'sh port-security': 'show port-security',
  'sh port': 'show port-security',
  'sh port-s': 'show port-security',
  'sh port-se': 'show port-security',
  'sh port-sec': 'show port-security',
  'sh port-secu': 'show port-security',
  'sh port-secur': 'show port-security',
  'sh port-securi': 'show port-security',
  'sh port-securit': 'show port-security',

  'sh run | include': 'show running-config | include',
  'sh run | inc': 'show running-config | include',
  'sh run | i': 'show running-config | include',
  'sh run | section': 'show running-config | section',
  'sh run | sec': 'show running-config | section',
  'sh run | begin': 'show running-config | begin',
  'sh run | beg': 'show running-config | begin',

  // Interface commands
  'int': 'interface',
  'inte': 'interface',
  'inter': 'interface',
  'interf': 'interface',
  'interfa': 'interface',
  'interfac': 'interface',

  // Interface range
  'int r': 'interface range',
  'int ra': 'interface range',
  'int ran': 'interface range',
  'int rang': 'interface range',
  'inter r': 'interface range',
  'inter ra': 'interface range',
  'inter ran': 'interface range',
  'inter rang': 'interface range',
  'inter range': 'interface range',
  'interf r': 'interface range',
  'interf ra': 'interface range',
  'interf ran': 'interface range',
  'interf rang': 'interface range',
  'interf range': 'interface range',
  'interface r': 'interface range',
  'interface ra': 'interface range',
  'interface ran': 'interface range',
  'interface rang': 'interface range',

  // Shutdown commands
  'no sh': 'no shutdown',
  'no shu': 'no shutdown',
  'no shut': 'no shutdown',
  'no shutd': 'no shutdown',
  'no shutdo': 'no shutdown',
  'no shutdow': 'no shutdown',
  'shut': 'shutdown',
  'shutd': 'shutdown',
  'shutdo': 'shutdown',
  'shutdow': 'shutdown',

  // Switchport commands
  'sw': 'switchport',
  'swi': 'switchport',
  'swit': 'switchport',
  'switc': 'switchport',
  'switch': 'switchport',
  'switchp': 'switchport',
  'switchpo': 'switchport',
  'switchpor': 'switchport',

  'sw m': 'switchport mode',
  'sw mo': 'switchport mode',
  'sw mod': 'switchport mode',
  'swi m': 'switchport mode',
  'swi mo': 'switchport mode',
  'swi mod': 'switchport mode',
  'swit m': 'switchport mode',
  'swit mo': 'switchport mode',
  'swit mod': 'switchport mode',
  'switch m': 'switchport mode',
  'switch mo': 'switchport mode',
  'switch mod': 'switchport mode',
  'switchp m': 'switchport mode',
  'switchp mo': 'switchport mode',
  'switchp mod': 'switchport mode',
  'switchpo m': 'switchport mode',
  'switchpo mo': 'switchport mode',
  'switchpo mod': 'switchport mode',
  'switchpor m': 'switchport mode',
  'switchpor mo': 'switchport mode',
  'switchpor mod': 'switchport mode',
  'switchport m': 'switchport mode',
  'switchport mo': 'switchport mode',

  'sw m a': 'switchport mode access',
  'sw mo a': 'switchport mode access',
  'sw mod a': 'switchport mode access',
  'sw m ac': 'switchport mode access',
  'sw mo ac': 'switchport mode access',
  'sw mod ac': 'switchport mode access',
  'sw m acc': 'switchport mode access',
  'sw mo acc': 'switchport mode access',
  'sw mod acc': 'switchport mode access',
  'sw m acce': 'switchport mode access',
  'sw mo acce': 'switchport mode access',
  'sw mod acce': 'switchport mode access',
  'sw m acces': 'switchport mode access',
  'sw mo acces': 'switchport mode access',
  'sw mod acces': 'switchport mode access',

  'sw m t': 'switchport mode trunk',
  'sw mo t': 'switchport mode trunk',
  'sw mod t': 'switchport mode trunk',
  'sw m tr': 'switchport mode trunk',
  'sw mo tr': 'switchport mode trunk',
  'sw mod tr': 'switchport mode trunk',
  'sw m tru': 'switchport mode trunk',
  'sw mo tru': 'switchport mode trunk',
  'sw mod tru': 'switchport mode trunk',
  'sw m trun': 'switchport mode trunk',
  'sw mo trun': 'switchport mode trunk',
  'sw mod trun': 'switchport mode trunk',

  'sw a': 'switchport access',
  'sw ac': 'switchport access',
  'sw acc': 'switchport access',
  'sw acce': 'switchport access',
  'sw acces': 'switchport access',
  'swi a': 'switchport access',
  'swi ac': 'switchport access',
  'swi acc': 'switchport access',
  'swi acce': 'switchport access',
  'swi acces': 'switchport access',

  'sw a v': 'switchport access vlan',
  'sw ac v': 'switchport access vlan',
  'sw acc v': 'switchport access vlan',
  'sw acce v': 'switchport access vlan',
  'sw acces v': 'switchport access vlan',
  'sw a vl': 'switchport access vlan',
  'sw ac vl': 'switchport access vlan',
  'sw acc vl': 'switchport access vlan',
  'sw acce vl': 'switchport access vlan',
  'sw acces vl': 'switchport access vlan',
  'sw a vla': 'switchport access vlan',
  'sw ac vla': 'switchport access vlan',
  'sw acc vla': 'switchport access vlan',
  'sw acce vla': 'switchport access vlan',
  'sw acces vla': 'switchport access vlan',
  'sw acc vlan': 'switchport access vlan',
  'sw acce vlan': 'switchport access vlan',
  'sw acces vlan': 'switchport access vlan',

  'sw t': 'switchport trunk',
  'sw tr': 'switchport trunk',
  'sw tru': 'switchport trunk',
  'sw trun': 'switchport trunk',
  'sw t a': 'switchport trunk allowed',
  'sw tr a': 'switchport trunk allowed',
  'sw tru a': 'switchport trunk allowed',
  'sw trun a': 'switchport trunk allowed',
  'sw t al': 'switchport trunk allowed',
  'sw tr al': 'switchport trunk allowed',
  'sw tru al': 'switchport trunk allowed',
  'sw trun al': 'switchport trunk allowed',
  'sw t all': 'switchport trunk allowed',
  'sw tr all': 'switchport trunk allowed',
  'sw tru all': 'switchport trunk allowed',
  'sw trun all': 'switchport trunk allowed',
  'sw t allo': 'switchport trunk allowed',
  'sw tr allo': 'switchport trunk allowed',
  'sw tru allo': 'switchport trunk allowed',
  'sw trun allo': 'switchport trunk allowed',
  'sw t allow': 'switchport trunk allowed',
  'sw tr allow': 'switchport trunk allowed',
  'sw tru allow': 'switchport trunk allowed',
  'sw trun allow': 'switchport trunk allowed',
  'sw t allowe': 'switchport trunk allowed',
  'sw tr allowe': 'switchport trunk allowed',
  'sw tru allowe': 'switchport trunk allowed',
  'sw trun allowe': 'switchport trunk allowed',
  'sw t allowed': 'switchport trunk allowed',
  'sw tr allowed': 'switchport trunk allowed',
  'sw tru allowed': 'switchport trunk allowed',
  'sw trun allowed': 'switchport trunk allowed',
  'sw t a v': 'switchport trunk allowed vlan',
  'sw tr a v': 'switchport trunk allowed vlan',
  'sw tru a v': 'switchport trunk allowed vlan',
  'sw trun a v': 'switchport trunk allowed vlan',
  'sw t al v': 'switchport trunk allowed vlan',
  'sw tr al v': 'switchport trunk allowed vlan',
  'sw tru al v': 'switchport trunk allowed vlan',
  'sw trun al v': 'switchport trunk allowed vlan',
  'show trunk all vlan': 'switchport trunk allowed vlan',

  // Speed and Duplex
  'spe': 'speed',
  'spee': 'speed',
  'dup': 'duplex',
  'dupl': 'duplex',
  'duple': 'duplex',

  // Reload
  'rel': 'reload',
  'relo': 'reload',
  'reloa': 'reload',

  // Ping
  'pi': 'ping',
  'pin': 'ping',

  // Traceroute
  'trac': 'traceroute',
  'trace': 'traceroute',
  'tracer': 'traceroute',
  'tracero': 'traceroute',
  'tracerou': 'traceroute',
  'tracerout': 'traceroute',

  // Telnet
  'tel': 'telnet',
  'teln': 'telnet',
  'telne': 'telnet',

  // SSH
  'ss': 'ssh',
  'ssh': 'ssh',

  // Crypto key generate
  'cry': 'crypto',
  'cryp': 'crypto',
  'crypt': 'crypto',
  'crypto': 'crypto',
  'cry k': 'crypto key',
  'cryp k': 'crypto key',
  'crypt k': 'crypto key',
  'crypto k': 'crypto key',
  'cry ke': 'crypto key',
  'cryp ke': 'crypto key',
  'crypt ke': 'crypto key',
  'crypto ke': 'crypto key',
  'crypto key': 'crypto key',
  'crypto key g': 'crypto key generate',
  'crypto key ge': 'crypto key generate',
  'crypto key gen': 'crypto key generate',
  'crypto key gene': 'crypto key generate',
  'crypto key gener': 'crypto key generate',
  'crypto key genera': 'crypto key generate',
  'crypto key generat': 'crypto key generate',
  'crypto key generate': 'crypto key generate',
  'crypto key generate r': 'crypto key generate rsa',
  'crypto key generate rs': 'crypto key generate rsa',
  'crypto key generate rsa': 'crypto key generate rsa',

  // Crypto key zeroize
  'crypto key z': 'crypto key zeroize',
  'crypto key ze': 'crypto key zeroize',
  'crypto key zer': 'crypto key zeroize',
  'crypto key zero': 'crypto key zeroize',
  'crypto key zeroi': 'crypto key zeroize',
  'crypto key zeroiz': 'crypto key zeroize',
  'crypto key zeroize': 'crypto key zeroize',
  'crypto key zeroize r': 'crypto key zeroize rsa',
  'crypto key zeroize rs': 'crypto key zeroize rsa',
  'crypto key zeroize rsa': 'crypto key zeroize rsa',

  // Ip domain-name
  'ip dn': 'ip domain-name',
  'ip dom': 'ip domain-name',
  'ip doma': 'ip domain-name',
  'ip domai': 'ip domain-name',
  'ip domain': 'ip domain-name',
  'ip domain-': 'ip domain-name',
  'ip domain-n': 'ip domain-name',
  'ip domain-na': 'ip domain-name',
  'ip domain-nam': 'ip domain-name',

  // Ip ssh version
  'ip ssh': 'ip ssh',
  'ip ssh v': 'ip ssh version',
  'ip ssh ve': 'ip ssh version',
  'ip ssh ver': 'ip ssh version',
  'ip ssh vers': 'ip ssh version',
  'ip ssh versi': 'ip ssh version',
  'ip ssh versio': 'ip ssh version',

  // Mac address-table static
  'mac a': 'mac address-table static',
  'mac ad': 'mac address-table static',
  'mac add': 'mac address-table static',
  'mac addr': 'mac address-table static',
  'mac addre': 'mac address-table static',
  'mac addres': 'mac address-table static',
  'mac address': 'mac address-table static',
  'mac address-': 'mac address-table static',
  'mac address-t': 'mac address-table static',
  'mac address-ta': 'mac address-table static',
  'mac address-tab': 'mac address-table static',
  'mac address-tabl': 'mac address-table static',
  'mac address-table': 'mac address-table static',
  'mac address-table s': 'mac address-table static',
  'mac address-table st': 'mac address-table static',
  'mac address-table sta': 'mac address-table static',
  'mac address-table stat': 'mac address-table static',
  'mac address-table stati': 'mac address-table static',
};

