import { Route, ipToNumber } from './routing';
import { Port, SwitchState } from './types';

/**
 * OSPF LSA Types
 */
enum LSAType {
  Router = 1,       // Type 1: Router LSA (Intra-area)
  Network = 2,      // Type 2: Network LSA (Intra-area, for multi-access links)
  Summary = 3,      // Type 3: Summary LSA (Inter-area, from ABR)
  ASExternal = 5    // Type 5: AS External LSA (From ASBR)
}

/**
 * Basic LSA Interface
 */
interface LSA {
  id: string;             // LSA ID (usually Router ID or Network ID)
  advRouter: string;      // Advertising Router ID
  type: LSAType;
  area: number;
  sequence: number;
  ageNumber: number;
  checksum?: string;
}

/**
 * Type 1: Router LSA
 * Describes the state of the router's links within an area.
 */
interface RouterLSA extends LSA {
  type: LSAType.Router;
  isAbr: boolean;
  isAsbr: boolean;
  links: OSPFLink[];
}

interface OSPFLink {
  id: string;             // Neighbor Router ID or Network ID
  data: string;           // Router's local interface IP or mask
  type: 'p2p' | 'transit' | 'stub';
  metric: number;
}

/**
 * Type 3: Summary LSA
 * Advertises networks from one area into another (generated by ABRs).
 */
interface SummaryLSA extends LSA {
  type: LSAType.Summary;
  network: string;
  mask: string;
  metric: number;
}

/**
 * Link State Database (LSDB)
 */
export interface LSDB {
  [area: number]: {
    routerLSAs: Map<string, RouterLSA>;
    summaryLSAs: Map<string, SummaryLSA>;
  };
}

const OSPF_REFERENCE_BANDWIDTH = 100000; // 100 Mbps in Kbps (Standard default)

/**
 * Calculate OSPF Cost based on interface bandwidth
 * Formula: reference-bandwidth / interface-bandwidth
 */
function calculateOSPFInterfaceCost(port: Port): number {
  if (port.stpCost !== undefined) return port.stpCost; // Manual override if provided

  const bandwidth = getPortBandwidthKbps(port);
  const cost = Math.max(1, Math.floor(OSPF_REFERENCE_BANDWIDTH / bandwidth));
  return cost;
}

function getPortBandwidthKbps(port: Port): number {
  if (port.bandwidth) return port.bandwidth;
  if (port.type === 'gigabitethernet') return 1000000;
  if (port.type === 'fastethernet') return 100000;
  if (port.type === 'serial') return 1544; // Standard T1
  return 100000;
}

/**
 * Dijkstra SPF Algorithm Implementation
 */
interface SPFNode {
  routerId: string;
  cost: number;
  nextHop: string;
  area: number;
}

/**
 * Build LSDB from current network state
 */
export function buildOSPFLinkStateDatabase(
  deviceStates: Map<string, SwitchState>
): LSDB {
  const lsdb: LSDB = {};

  deviceStates.forEach((state, deviceId) => {
    if (state.routingProtocol !== 'ospf') return;

    const routerId = state.ospfRouterId || state.routerId || state.ip || deviceId;
    const areas = state.ospfAreas || [0];

    areas.forEach(area => {
      if (!lsdb[area]) {
        lsdb[area] = {
          routerLSAs: new Map(),
          summaryLSAs: new Map()
        };
      }

      // Create Type 1 Router LSA
      const links: OSPFLink[] = [];
      Object.values(state.ports).forEach(port => {
        if (!port.ipAddress || !port.subnetMask || port.shutdown) return;
        if (port.ospfEnabled === false) return; // Explicitly disabled

        // Check if port is in this area
        const portArea = port.ospfArea !== undefined ? parseInt(port.ospfArea) : area;
        if (portArea !== area) return;

        // Simplify: for our simulator, we treat everything as either p2p or stub
        // In a real SPF, transit would require Type 2 LSAs
        links.push({
          id: getNetworkAddress(port.ipAddress, port.subnetMask),
          data: port.subnetMask,
          type: 'stub',
          metric: calculateOSPFInterfaceCost(port)
        });
      });

      const routerLSA: RouterLSA = {
        id: routerId,
        advRouter: routerId,
        type: LSAType.Router,
        area,
        sequence: 1,
        ageNumber: 0,
        isAbr: !!state.isAbr || areas.length > 1,
        isAsbr: !!state.bgpAs, // Simplified ASBR check
        links
      };

      lsdb[area].routerLSAs.set(routerId, routerLSA);
    });
  });

  // ABRs generate Type 3 Summary LSAs
  // ABRs advertise networks reachable in one area into other areas
  deviceStates.forEach((state, deviceId) => {
    const routerId = state.ospfRouterId || state.routerId || state.ip || deviceId;
    const areas = state.ospfAreas || [0];

    if (areas.length > 1) { // ABR
      areas.forEach(sourceArea => {
        const sourceAreaData = lsdb[sourceArea];
        if (!sourceAreaData) return;

        // For each network (Type 1 Router LSA links) in source area
        sourceAreaData.routerLSAs.forEach((lsa) => {
          lsa.links.forEach(link => {
            if (link.type === 'stub') {
              // Advertise this network to all OTHER areas this ABR is connected to
              areas.forEach(targetArea => {
                if (sourceArea === targetArea) return;

                const summaryLSA: SummaryLSA = {
                  id: link.id,
                  advRouter: routerId,
                  type: LSAType.Summary,
                  area: targetArea,
                  sequence: 1,
                  ageNumber: 0,
                  network: link.id,
                  mask: link.data,
                  metric: link.metric // Simplified: should be cost to reach this link
                };
                if (!lsdb[targetArea]) {
                  lsdb[targetArea] = { routerLSAs: new Map(), summaryLSAs: new Map() };
                }
                lsdb[targetArea].summaryLSAs.set(`${summaryLSA.id}-${routerId}`, summaryLSA);
              });
            }
          });
        });
      });
    }
  });

  return lsdb;
}

/**
 * Run Dijkstra for a specific area and source router
 */
function runOSPFDijkstra(
  sourceRouterId: string,
  area: number,
  lsdb: LSDB
): Map<string, SPFNode> {
  const areaData = lsdb[area];
  if (!areaData) return new Map();

  const spt = new Map<string, SPFNode>();
  const queue: SPFNode[] = [];

  // Initialize source
  queue.push({
    routerId: sourceRouterId,
    cost: 0,
    nextHop: 'self',
    area
  });

  while (queue.length > 0) {
    // Sort by cost (Priority Queue simulation)
    queue.sort((a, b) => a.cost - b.cost);
    const current = queue.shift();
    if (!current) continue;

    if (spt.has(current.routerId)) continue;
    spt.set(current.routerId, current);

    const lsa = areaData.routerLSAs.get(current.routerId);
    if (!lsa) continue;

    lsa.links.forEach(link => {
      // For Dijkstra to work, we need to find neighbors.
      // In OSPF, Type 1 LSAs list links to neighbors (p2p/transit).
      // We look for other Router LSAs that advertise the same link.
      areaData.routerLSAs.forEach((otherLsa, neighborId) => {
        if (neighborId === current.routerId) return;

        const isNeighbor = otherLsa.links.some(otherLink =>
          (otherLink.id === link.id)
        );

        if (isNeighbor) {
          const newCost = current.cost + link.metric;
          const nextHop = current.nextHop === 'self' ? neighborId : current.nextHop;

          queue.push({
            routerId: neighborId,
            cost: newCost,
            nextHop,
            area
          });
        }
      });
    });
  }

  return spt;
}

/**
 * Main function to calculate OSPF routes for a device
 */
export function calculateOSPFRoutes(
  deviceId: string,
  deviceStates: Map<string, SwitchState>
): Route[] {
  const state = deviceStates.get(deviceId);
  if (!state || state.routingProtocol !== 'ospf') return [];

  const routerId = state.ospfRouterId || state.routerId || state.ip || deviceId;
  const areas = state.ospfAreas || [0];
  const lsdb = buildOSPFLinkStateDatabase(deviceStates);
  const routes: Route[] = [];

  areas.forEach(area => {
    const areaData = lsdb[area];
    if (!areaData) return;

    // 1. Run Dijkstra for Intra-area routes (O)
    const spt = runOSPFDijkstra(routerId, area, lsdb);

    spt.forEach((node, targetRouterId) => {
      if (targetRouterId === routerId) return;

      const lsa = areaData.routerLSAs.get(targetRouterId);
      if (!lsa) return;

      lsa.links.forEach(link => {
        if (link.type === 'stub') {
          const dest = link.id;
          const existing = routes.find(r => r.destination === dest);

          if (!existing || (existing.metric || 0) > node.cost + link.metric) {
            if (existing) {
              const idx = routes.indexOf(existing);
              routes.splice(idx, 1);
            }
            routes.push({
              destination: dest,
              subnetMask: link.data,
              nextHop: node.nextHop,
              type: 'dynamic',
              metric: node.cost + link.metric,
              area: area
            });
          }
        }
      });
    });

    // 2. Process Summary LSAs for Inter-area routes (O IA)
    areaData.summaryLSAs.forEach(lsa => {
      // Find the ABR that advertised this Summary LSA in our SPT
      const abrNode = spt.get(lsa.advRouter);
      if (!abrNode && lsa.advRouter !== routerId) return;

      const costToAbr = abrNode ? abrNode.cost : 0;
      const totalCost = costToAbr + lsa.metric;
      const nextHop = abrNode ? abrNode.nextHop : 'self';

      const existing = routes.find(r => r.destination === lsa.network);
      if (!existing || (existing.metric || 0) > totalCost) {
        if (existing) {
          // Intra-area routes (O) always preferred over Inter-area (O IA)
          if (existing.area === area && !areaData.summaryLSAs.has(`${lsa.network}-${lsa.advRouter}`)) {
             // If existing is O and we are O IA, don't replace
             return;
          }
          const idx = routes.indexOf(existing);
          routes.splice(idx, 1);
        }
        routes.push({
          destination: lsa.network,
          subnetMask: lsa.mask,
          nextHop: nextHop === 'self' ? lsa.network : nextHop, // Simplified
          type: 'dynamic',
          metric: totalCost,
          area: area
        });
      }
    });
  });

  return routes;
}

function getNetworkAddress(ip: string, subnetMask: string): string {
  const ipNum = ipToNumber(ip);
  const maskNum = ipToNumber(subnetMask);
  const networkNum = ipNum & maskNum;
  return numberToIp(networkNum);
}

function numberToIp(num: number): string {
  return [
    (num >>> 24) & 255,
    (num >>> 16) & 255,
    (num >>> 8) & 255,
    num & 255
  ].join('.');
}
