import { Route, ipToNumber } from './routing';
import { Port, SwitchState } from './types';

/**
 * OSPF LSA Types
 */
enum LSAType {
  Router = 1,       // Type 1: Router LSA (Intra-area)
  Network = 2,      // Type 2: Network LSA (Intra-area, for multi-access links)
  Summary = 3,      // Type 3: Summary LSA (Inter-area, from ABR)
  ASExternal = 5,   // Type 5: AS External LSA (From ASBR)
  NSSA = 7          // Type 7: NSSA External LSA (From ASBR in NSSA)
}

/**
 * OSPF Area Types
 */
export enum OSPFAreaType {
  Normal = 'normal',
  Stub = 'stub',
  TotallyStubby = 'totally-stubby',
  NSSA = 'nssa',
  TotallyNSSA = 'totally-nssa'
}

/**
 * Basic LSA Interface
 */
interface LSA {
  id: string;             // LSA ID (usually Router ID or Network ID)
  advRouter: string;      // Advertising Router ID
  type: LSAType;
  area: number;
  sequence: number;
  ageNumber: number;
  checksum?: string;
}

/**
 * Type 1: Router LSA
 * Describes the state of the router's links within an area.
 */
interface RouterLSA extends LSA {
  type: LSAType.Router;
  isAbr: boolean;
  isAsbr: boolean;
  links: OSPFLink[];
}

interface OSPFLink {
  id: string;             // Neighbor Router ID or Network ID
  data: string;           // Router's local interface IP or mask
  type: 'p2p' | 'transit' | 'stub';
  metric: number;
}

/**
 * Type 3: Summary LSA
 * Advertises networks from one area into another (generated by ABRs).
 */
interface SummaryLSA extends LSA {
  type: LSAType.Summary;
  network: string;
  mask: string;
  metric: number;
}

/**
 * Type 5: AS-External LSA
 * Advertises external routes (from ASBR).
 */
interface ASExternalLSA extends LSA {
  type: LSAType.ASExternal;
  network: string;
  mask: string;
  metric: number;
  forwardingAddress?: string;
}

/**
 * Type 7: NSSA External LSA
 * Advertises external routes within an NSSA (converted to Type 5 by ABR).
 */
interface NSSAExternalLSA extends LSA {
  type: LSAType.NSSA;
  network: string;
  mask: string;
  metric: number;
  forwardingAddress?: string;
  propagate: boolean; // Converted to Type 5 by ABR
}

/**
 * Link State Database (LSDB)
 */
export interface LSDB {
  [area: number]: {
    routerLSAs: Map<string, RouterLSA>;
    summaryLSAs: Map<string, SummaryLSA>;
    asExternalLSAs?: Map<string, ASExternalLSA>;
    nssaLsas?: Map<string, NSSAExternalLSA>;
    areaType?: OSPFAreaType;
  };
}

const OSPF_REFERENCE_BANDWIDTH = 100000; // 100 Mbps in Kbps (Standard default)

/**
 * Calculate OSPF Cost based on interface bandwidth
 * Formula: reference-bandwidth / interface-bandwidth
 */
function calculateOSPFInterfaceCost(port: Port): number {
  if (port.stpCost !== undefined) return port.stpCost; // Manual override if provided

  const bandwidth = getPortBandwidthKbps(port);
  const cost = Math.max(1, Math.floor(OSPF_REFERENCE_BANDWIDTH / bandwidth));
  return cost;
}

function getPortBandwidthKbps(port: Port): number {
  if (port.bandwidth) return port.bandwidth;
  if (port.type === 'gigabitethernet') return 1000000;
  if (port.type === 'fastethernet') return 100000;
  if (port.type === 'serial') return 1544; // Standard T1
  return 100000;
}

/**
 * Get area type for a given area number from router state
 */
function getAreaType(area: number, state: SwitchState): OSPFAreaType {
  const areaStr = String(area);

  if (state.ospfTotallyNssaAreas?.includes(areaStr)) return OSPFAreaType.TotallyNSSA;
  if (state.ospfTotallyStubAreas?.includes(areaStr)) return OSPFAreaType.TotallyStubby;
  if (state.ospfNssaAreas?.includes(areaStr)) return OSPFAreaType.NSSA;
  if (state.ospfStubAreas?.includes(areaStr)) return OSPFAreaType.Stub;
  return OSPFAreaType.Normal;
}

/**
 * Check if an LSA type should be allowed into the given area type
 */
function isLSAAllowedInArea(areaType: OSPFAreaType, lsaType: LSAType): boolean {
  switch (areaType) {
    case OSPFAreaType.Normal:
      return true; // All LSA types allowed
    case OSPFAreaType.Stub:
      // Stub: no Type 5 (AS-External), Type 7 doesn't exist in stub
      return lsaType !== LSAType.ASExternal;
    case OSPFAreaType.TotallyStubby:
      // Totally Stubby: no Type 3 (Summary), no Type 5
      return lsaType !== LSAType.Summary && lsaType !== LSAType.ASExternal;
    case OSPFAreaType.NSSA:
      // NSSA: no Type 5 (AS-External), Type 7 replaces Type 5
      return lsaType !== LSAType.ASExternal;
    case OSPFAreaType.TotallyNSSA:
      // Totally NSSA: no Type 3, no Type 5. Type 7 replaces Type 5.
      return lsaType !== LSAType.Summary && lsaType !== LSAType.ASExternal;
    default:
      return true;
  }
}

/**
 * Get display string for area type
 */
export function getAreaTypeDisplay(areaType: OSPFAreaType): string {
  switch (areaType) {
    case OSPFAreaType.Normal: return 'normal';
    case OSPFAreaType.Stub: return 'stub';
    case OSPFAreaType.TotallyStubby: return 'totally stubby';
    case OSPFAreaType.NSSA: return 'nssa';
    case OSPFAreaType.TotallyNSSA: return 'totally nssa';
  }
}

/**
 * Dijkstra SPF Algorithm Implementation
 */
interface SPFNode {
  routerId: string;
  cost: number;
  nextHop: string;
  area: number;
}

/**
 * Build LSDB from current network state
 */
function isOspfProtocol(protocol: string | undefined): boolean {
  return protocol === 'ospf' || protocol === 'ospfv3';
}

/**
 * Check if the given routing protocol is OSPFv3 (IPv6)
 */
function isOspfV3(protocol: string | undefined): boolean {
  return protocol === 'ospfv3';
}

export function buildOSPFLinkStateDatabase(
  deviceStates: Map<string, SwitchState>
): LSDB {
  const lsdb: LSDB = {};

  // First pass: detect all area types by checking each router's configuration
  const areaTypes = new Map<number, OSPFAreaType>();
  deviceStates.forEach((state) => {
    if (!isOspfProtocol(state.routingProtocol)) return;
    const areas = state.ospfAreas || [0];
    areas.forEach(area => {
      const existingType = areaTypes.get(area);
      const thisAreaType = getAreaType(area, state);
      // If this is the first router for this area, or it's more restrictive, use it
      if (!existingType || getTypeRestrictiveness(thisAreaType) > getTypeRestrictiveness(existingType)) {
        areaTypes.set(area, thisAreaType);
      }
      // Ensure area entry exists in LSDB
      if (!lsdb[area]) {
        lsdb[area] = {
          routerLSAs: new Map(),
          summaryLSAs: new Map()
        };
      }
    });
  });

  // Apply area types to LSDB
  areaTypes.forEach((areaType, area) => {
    if (lsdb[area]) {
      lsdb[area].areaType = areaType;
    }
  });

  // Second pass: build Router LSAs (Type 1)
  deviceStates.forEach((state, deviceId) => {
    if (!isOspfProtocol(state.routingProtocol)) return;

    const isV6 = isOspfV3(state.routingProtocol);
    const routerId = state.ospfRouterId || state.routerId || state.ip || state.hostname || deviceId;
    const areas = state.ospfAreas || [0];

    areas.forEach(area => {
      if (!lsdb[area]) {
        lsdb[area] = {
          routerLSAs: new Map(),
          summaryLSAs: new Map()
        };
      }

      // Create Type 1 Router LSA
      const links: OSPFLink[] = [];
      Object.values(state.ports).forEach(port => {
        if (port.shutdown) return;

        if (isV6) {
          if (!port.ipv6Address || port.ipv6Prefix === undefined) return;
          if (!port.ipv6Ospf?.enabled) return;

          const portArea = port.ipv6Ospf.area !== undefined ? parseInt(port.ipv6Ospf.area) : area;
          if (portArea !== area) return;

          links.push({
            id: port.ipv6Address,
            data: String(port.ipv6Prefix),
            type: 'stub',
            metric: calculateOSPFInterfaceCost(port)
          });
        } else {
          if (!port.ipAddress || !port.subnetMask) return;
          if (port.ospfEnabled === false) return;

          const portArea = port.ospfArea !== undefined ? parseInt(port.ospfArea) : area;
          if (portArea !== area) return;

          links.push({
            id: getNetworkAddress(port.ipAddress, port.subnetMask),
            data: port.subnetMask,
            type: 'stub',
            metric: calculateOSPFInterfaceCost(port)
          });
        }
      });

      const routerLSA: RouterLSA = {
        id: routerId,
        advRouter: routerId,
        type: LSAType.Router,
        area,
        sequence: 1,
        ageNumber: 0,
        isAbr: !!state.isAbr || areas.length > 1,
        isAsbr: !!state.bgpAs,
        links
      };

      lsdb[area].routerLSAs.set(routerId, routerLSA);
    });
  });

  // Third pass: generate Type 5 (AS-External) and Type 7 (NSSA) LSAs
  deviceStates.forEach((state, deviceId) => {
    if (!isOspfProtocol(state.routingProtocol)) return;
    const isV6 = isOspfV3(state.routingProtocol);
    const routerId = state.ospfRouterId || state.routerId || state.ip || state.hostname || deviceId;
    const areas = state.ospfAreas || [0];

    const isAsbr = !!state.bgpAs;
    if (!isAsbr) return;

    areas.forEach(area => {
      if (!lsdb[area]) return;
      const areaType = lsdb[area].areaType || OSPFAreaType.Normal;

      // Collect external networks from this ASBR
      const externalNetworks: Array<{ network: string; mask: string; metric: number }> = [];
      Object.values(state.ports).forEach(port => {
        if (port.shutdown) return;

        if (isV6) {
          if (!port.ipv6Address || port.ipv6Prefix === undefined) return;
          if (!port.ipv6Ospf?.enabled) return;

          externalNetworks.push({
            network: port.ipv6Address,
            mask: String(port.ipv6Prefix),
            metric: calculateOSPFInterfaceCost(port)
          });
        } else {
          if (!port.ipAddress || !port.subnetMask) return;
          if (port.ospfEnabled === false) return;
          const portArea = port.ospfArea !== undefined ? parseInt(port.ospfArea) : area;
          if (portArea !== area) return;

          const networkAddr = getNetworkAddress(port.ipAddress, port.subnetMask);
          externalNetworks.push({
            network: networkAddr,
            mask: port.subnetMask,
            metric: calculateOSPFInterfaceCost(port)
          });
        }
      });

      if (externalNetworks.length === 0) return;

      if (areaType === OSPFAreaType.NSSA || areaType === OSPFAreaType.TotallyNSSA) {
        const nssaLsas = lsdb[area].nssaLsas ?? (lsdb[area].nssaLsas = new Map());
        externalNetworks.forEach(ext => {
          const nssaLsa: NSSAExternalLSA = {
            id: `7-${ext.network}`,
            advRouter: routerId,
            type: LSAType.NSSA,
            area,
            sequence: 1,
            ageNumber: 0,
            network: ext.network,
            mask: ext.mask,
            metric: ext.metric,
            propagate: true
          };
          nssaLsas.set(nssaLsa.id, nssaLsa);
        });
      } else if (areaType === OSPFAreaType.Normal) {
        // Generate Type 5 LSAs in normal areas
        if (!lsdb[area].asExternalLSAs) {
          lsdb[area].asExternalLSAs = new Map();
        }
        externalNetworks.forEach(ext => {
          const externalLsa: ASExternalLSA = {
            id: ext.network,
            advRouter: routerId,
            type: LSAType.ASExternal,
            area,
            sequence: 1,
            ageNumber: 0,
            network: ext.network,
            mask: ext.mask,
            metric: ext.metric
          };
          const asExtLsas = lsdb[area].asExternalLSAs ?? (lsdb[area].asExternalLSAs = new Map());
          asExtLsas.set(externalLsa.id, externalLsa);
        });
      }
      // Stub areas: no Type 5 allowed (blocked by isLSAAllowedInArea)
    });
  });

  // Fourth pass: ABRs generate Type 3 Summary LSAs (filtered by area type)
  deviceStates.forEach((state, deviceId) => {
    const routerId = state.ospfRouterId || state.routerId || state.ip || deviceId;
    const areas = state.ospfAreas || [0];

    if (areas.length > 1) { // ABR
      areas.forEach(sourceArea => {
        const sourceAreaData = lsdb[sourceArea];
        if (!sourceAreaData) return;

        sourceAreaData.routerLSAs.forEach((lsa) => {
          lsa.links.forEach(link => {
            if (link.type === 'stub') {
              areas.forEach(targetArea => {
                if (sourceArea === targetArea) return;

                if (!lsdb[targetArea]) {
                  lsdb[targetArea] = { routerLSAs: new Map(), summaryLSAs: new Map() };
                }

                const targetAreaType = lsdb[targetArea].areaType || OSPFAreaType.Normal;

                // Check if Summary LSA is allowed in target area
                if (!isLSAAllowedInArea(targetAreaType, LSAType.Summary)) {
                  return; // Totally Stubby and Totally NSSA block Type 3
                }

                const summaryLSA: SummaryLSA = {
                  id: link.id,
                  advRouter: routerId,
                  type: LSAType.Summary,
                  area: targetArea,
                  sequence: 1,
                  ageNumber: 0,
                  network: link.id,
                  mask: link.data,
                  metric: link.metric
                };
                lsdb[targetArea].summaryLSAs.set(`${summaryLSA.id}-${routerId}`, summaryLSA);
              });
            }
          });
        });
      });

      // ABR converts Type 7 NSSA LSAs to Type 5 for other areas
      areas.forEach(sourceArea => {
        const sourceAreaData = lsdb[sourceArea];
        if (!sourceAreaData?.nssaLsas) return;
        const sourceAreaType = sourceAreaData.areaType || OSPFAreaType.Normal;
        if (sourceAreaType !== OSPFAreaType.NSSA && sourceAreaType !== OSPFAreaType.TotallyNSSA) return;

        sourceAreaData.nssaLsas.forEach((nssaLsa) => {
          if (!nssaLsa.propagate) return;

          areas.forEach(targetArea => {
            if (sourceArea === targetArea) return;
            if (!lsdb[targetArea]) {
              lsdb[targetArea] = { routerLSAs: new Map(), summaryLSAs: new Map() };
            }
            if (!lsdb[targetArea].asExternalLSAs) {
              lsdb[targetArea].asExternalLSAs = new Map();
            }

            const targetAreaType = lsdb[targetArea].areaType || OSPFAreaType.Normal;
            // Only inject Type 5 into non-stub/non-nssa areas
            if (!isLSAAllowedInArea(targetAreaType, LSAType.ASExternal)) return;

            const externalLsa: ASExternalLSA = {
              id: nssaLsa.network,
              advRouter: routerId,
              type: LSAType.ASExternal,
              area: targetArea,
              sequence: 1,
              ageNumber: 0,
              network: nssaLsa.network,
              mask: nssaLsa.mask,
              metric: nssaLsa.metric
            };
            const asExtLsas = lsdb[targetArea].asExternalLSAs ?? (lsdb[targetArea].asExternalLSAs = new Map());
            asExtLsas.set(externalLsa.id, externalLsa);
          });
        });
      });
    }
  });

  // Fifth pass: inject default route for stub/totally-stubby areas
  // ABR injects 0.0.0.0/0 as a Type 3 summary into stub areas
  deviceStates.forEach((state, deviceId) => {
    const routerId = state.ospfRouterId || state.routerId || state.ip || deviceId;
    const areas = state.ospfAreas || [0];

    if (areas.length > 1) {
      areas.forEach(targetArea => {
        if (!lsdb[targetArea]) return;
        const targetAreaType = lsdb[targetArea].areaType || OSPFAreaType.Normal;

        if (targetAreaType === OSPFAreaType.Stub ||
            targetAreaType === OSPFAreaType.TotallyStubby ||
            targetAreaType === OSPFAreaType.NSSA ||
            targetAreaType === OSPFAreaType.TotallyNSSA) {
          // Inject default route
          const defaultSummary: SummaryLSA = {
            id: '0.0.0.0',
            advRouter: routerId,
            type: LSAType.Summary,
            area: targetArea,
            sequence: 1,
            ageNumber: 0,
            network: '0.0.0.0',
            mask: '0.0.0.0',
            metric: 1 // Default route cost in stub areas
          };
          lsdb[targetArea].summaryLSAs.set(`0.0.0.0-${routerId}`, defaultSummary);
        }
      });
    }
  });

  return lsdb;
}

/**
 * Helper to determine how restrictive an area type is (higher = more filtering)
 */
function getTypeRestrictiveness(type: OSPFAreaType): number {
  switch (type) {
    case OSPFAreaType.Normal: return 0;
    case OSPFAreaType.Stub: return 1;
    case OSPFAreaType.NSSA: return 2;
    case OSPFAreaType.TotallyStubby: return 3;
    case OSPFAreaType.TotallyNSSA: return 4;
  }
}

/**
 * Run Dijkstra for a specific area and source router
 */
function runOSPFDijkstra(
  sourceRouterId: string,
  area: number,
  lsdb: LSDB
): Map<string, SPFNode> {
  const areaData = lsdb[area];
  if (!areaData) return new Map();

  const spt = new Map<string, SPFNode>();
  const queue: SPFNode[] = [];

  // Initialize source
  queue.push({
    routerId: sourceRouterId,
    cost: 0,
    nextHop: 'self',
    area
  });

  while (queue.length > 0) {
    // Sort by cost (Priority Queue simulation)
    queue.sort((a, b) => a.cost - b.cost);
    const current = queue.shift();
    if (!current) continue;

    if (spt.has(current.routerId)) continue;
    spt.set(current.routerId, current);

    const lsa = areaData.routerLSAs.get(current.routerId);
    if (!lsa) continue;

    lsa.links.forEach(link => {
      // For Dijkstra to work, we need to find neighbors.
      // In OSPF, Type 1 LSAs list links to neighbors (p2p/transit).
      // We look for other Router LSAs that advertise the same link.
      areaData.routerLSAs.forEach((otherLsa, neighborId) => {
        if (neighborId === current.routerId) return;

        const isNeighbor = otherLsa.links.some(otherLink =>
          (otherLink.id === link.id)
        );

        if (isNeighbor) {
          const newCost = current.cost + link.metric;
          const nextHop = current.nextHop === 'self' ? neighborId : current.nextHop;

          queue.push({
            routerId: neighborId,
            cost: newCost,
            nextHop,
            area
          });
        }
      });
    });
  }

  return spt;
}

/**
 * Main function to calculate OSPF routes for a device
 */
export function calculateOSPFRoutes(
  deviceId: string,
  deviceStates: Map<string, SwitchState>
): Route[] {
  const state = deviceStates.get(deviceId);
  if (!state || !isOspfProtocol(state.routingProtocol)) return [];

  const isV6 = isOspfV3(state.routingProtocol);
  const routerId = state.ospfRouterId || state.routerId || state.ip || state.hostname || deviceId;
  const areas = state.ospfAreas || [0];
  const lsdb = buildOSPFLinkStateDatabase(deviceStates);
  const routes: Route[] = [];

  areas.forEach(area => {
    const areaData = lsdb[area];
    if (!areaData) return;
    const areaType = areaData.areaType || OSPFAreaType.Normal;

    // 1. Run Dijkstra for Intra-area routes (O)
    const spt = runOSPFDijkstra(routerId, area, lsdb);

    spt.forEach((node, targetRouterId) => {
      if (targetRouterId === routerId) return;

      const lsa = areaData.routerLSAs.get(targetRouterId);
      if (!lsa) return;

      lsa.links.forEach(link => {
        if (link.type === 'stub') {
          const dest = link.id;
          const existing = routes.find(r => r.destination === dest);

          if (!existing || (existing.metric || 0) > node.cost + link.metric) {
            if (existing) {
              const idx = routes.indexOf(existing);
              routes.splice(idx, 1);
            }
            if (isV6) {
              routes.push({
                destination: dest,
                prefixLength: parseInt(link.data),
                nextHop: node.nextHop,
                type: 'dynamic',
                metric: node.cost + link.metric,
                area: area
              });
            } else {
              routes.push({
                destination: dest,
                subnetMask: link.data,
                nextHop: node.nextHop,
                type: 'dynamic',
                metric: node.cost + link.metric,
                area: area
              });
            }
          }
        }
      });
    });

    // 2. Process Summary LSAs for Inter-area routes (O IA)
    // Excluding default route (0.0.0.0/0) for now - handle separately
    areaData.summaryLSAs.forEach(lsa => {
      // Check if this LSA type is allowed in this area
      if (!isLSAAllowedInArea(areaType, LSAType.Summary)) return;

      const abrNode = spt.get(lsa.advRouter);
      if (!abrNode && lsa.advRouter !== routerId) return;

      const costToAbr = abrNode ? abrNode.cost : 0;
      const totalCost = costToAbr + lsa.metric;
      const nextHop = abrNode ? abrNode.nextHop : 'self';

      const existing = routes.find(r => r.destination === lsa.network);
      if (!existing || (existing.metric || 0) > totalCost) {
        if (existing) {
          // Intra-area routes (O) always preferred over Inter-area (O IA)
          if (existing.area === area && !areaData.summaryLSAs.has(`${lsa.network}-${lsa.advRouter}`)) {
             return;
          }
          const idx = routes.indexOf(existing);
          routes.splice(idx, 1);
        }
        if (isV6) {
          routes.push({
            destination: lsa.network,
            prefixLength: parseInt(lsa.mask),
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: totalCost,
            area: area
          });
        } else {
          routes.push({
            destination: lsa.network,
            subnetMask: lsa.mask,
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: totalCost,
            area: area
          });
        }
      }
    });
  });

  // 3. Process Type 7 (NSSA) LSAs for N1/N2 routes
  areas.forEach(area => {
    const areaData = lsdb[area];
    if (!areaData?.nssaLsas) return;
    const areaType = areaData.areaType || OSPFAreaType.Normal;

    areaData.nssaLsas.forEach(lsa => {
      if (!isLSAAllowedInArea(areaType, LSAType.ASExternal)) return;

      // Find the ASBR in the SPT
      const spt = runOSPFDijkstra(routerId, area, lsdb);
      const asbrNode = spt.get(lsa.advRouter);
      if (!asbrNode && lsa.advRouter !== routerId) return;

      const costToAsbr = asbrNode ? asbrNode.cost : 0;
      // Type N1: cost = cost_to_asbr + external_metric
      // Type N2: cost = external_metric only (cost_to_asbr not added)
      const n1Cost = costToAsbr + lsa.metric;
      const n2Cost = lsa.metric;
      const nextHop = asbrNode ? asbrNode.nextHop : 'self';

      const existingN1 = routes.find(r => r.destination === lsa.network && r.ospfRouteType === 'N1');
      if (!existingN1 || (existingN1.metric ?? 0) > n1Cost) {
        if (isV6) {
          routes.push({
            destination: lsa.network,
            prefixLength: parseInt(lsa.mask),
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: n1Cost,
            area: area,
            ospfRouteType: 'N1'
          });
        } else {
          routes.push({
            destination: lsa.network,
            subnetMask: lsa.mask,
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: n1Cost,
            area: area,
            ospfRouteType: 'N1'
          });
        }
      }

      const existingN2 = routes.find(r => r.destination === lsa.network && r.ospfRouteType === 'N2');
      if (!existingN2 || (existingN2.metric ?? 0) > n2Cost) {
        if (isV6) {
          routes.push({
            destination: lsa.network,
            prefixLength: parseInt(lsa.mask),
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: n2Cost,
            area: area
          });
        } else {
          routes.push({
            destination: lsa.network,
            subnetMask: lsa.mask,
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: n2Cost,
            area: area
          });
        }
      }
    });
  });

  // 4. Process Type 5 (AS-External) LSAs for E1/E2 routes
  areas.forEach(area => {
    const areaData = lsdb[area];
    if (!areaData?.asExternalLSAs) return;
    const areaType = areaData.areaType || OSPFAreaType.Normal;

    if (!isLSAAllowedInArea(areaType, LSAType.ASExternal)) return;

    const spt = runOSPFDijkstra(routerId, area, lsdb);

    areaData.asExternalLSAs.forEach(lsa => {
      const asbrNode = spt.get(lsa.advRouter);
      if (!asbrNode && lsa.advRouter !== routerId) return;

      const costToAsbr = asbrNode ? asbrNode.cost : 0;
      const e1Cost = costToAsbr + lsa.metric;
      const e2Cost = lsa.metric;
      const nextHop = asbrNode ? asbrNode.nextHop : 'self';

      const existingE1 = routes.find(r => r.destination === lsa.network && r.ospfRouteType === 'E1');
      if (!existingE1 || (existingE1.metric ?? 0) > e1Cost) {
        if (isV6) {
          routes.push({
            destination: lsa.network,
            prefixLength: parseInt(lsa.mask),
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: e1Cost,
            area: area,
            ospfRouteType: 'E1'
          });
        } else {
          routes.push({
            destination: lsa.network,
            subnetMask: lsa.mask,
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: e1Cost,
            area: area,
            ospfRouteType: 'E1'
          });
        }
      }

      const existingE2 = routes.find(r => r.destination === lsa.network && r.ospfRouteType === 'E2');
      if (!existingE2 || (existingE2.metric ?? 0) > e2Cost) {
        if (isV6) {
          routes.push({
            destination: lsa.network,
            prefixLength: parseInt(lsa.mask),
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: e2Cost,
            area: area,
            ospfRouteType: 'E2'
          });
        } else {
          routes.push({
            destination: lsa.network,
            subnetMask: lsa.mask,
            nextHop: nextHop === 'self' ? lsa.network : nextHop,
            type: 'dynamic',
            metric: e2Cost,
            area: area,
            ospfRouteType: 'E2'
          });
        }
      }
    });
  });

  return routes;
}

function getNetworkAddress(ip: string, subnetMask: string): string {
  const ipNum = ipToNumber(ip);
  const maskNum = ipToNumber(subnetMask);
  const networkNum = ipNum & maskNum;
  return numberToIp(networkNum);
}

function numberToIp(num: number): string {
  return [
    (num >>> 24) & 255,
    (num >>> 16) & 255,
    (num >>> 8) & 255,
    num & 255
  ].join('.');
}
